// Class: ReadD2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::D2
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : jlang
Date           : Tue Dec  8 16:22:07 2015
Host           : Linux ekpams2 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 21:44:51 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /usr/users/jlang/BDT/Test/BDT_Training
Training events: 1332
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "10" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
MaxDepth: "2" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1332" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
v0                            v0                            v0                            v0                                                              'F'    [-0.490635514259,1.48405468464]
v1                            v1                            v1                            v1                                                              'F'    [-7.37883806229,7.25839614868]
v2                            v2                            v2                            v2                                                              'F'    [-1.8986569643,6.2026591301]
v3                            v3                            v3                            v3                                                              'F'    [1.46819293499,2.39548110962]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new D2Node
   
#ifndef D2Node__def
#define D2Node__def
   
class D2Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   D2Node ( D2Node* left,D2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~D2Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   D2Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   D2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   D2Node*   fLeft;     // pointer to the left daughter node
   D2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   D2Node::~D2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool D2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool D2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadD2 : public IClassifierReader {

 public:

   // constructor
   ReadD2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadD2" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "v0", "v1", "v2", "v3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.490635514259338;
      fVmax[0] = 1.48405468463898;
      fVmin[1] = -7.37883806228638;
      fVmax[1] = 7.25839614868164;
      fVmin[2] = -1.89865696430206;
      fVmax[2] = 6.20265913009644;
      fVmin[3] = 1.46819293498993;
      fVmax[3] = 2.39548110961914;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadD2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<D2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadD2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      D2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(D2Node*)current->GetRight();
         else current=(D2Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadD2::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(2.14975248896722);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.93313, 0, 1, 0.963093,-99) , 
NN(
0, 
0, 
-1, 1.80449, 0, -1, 0.154653,-99) , 
3, 1.90976, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.71988);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.854158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449769,-99) , 
0, 0.825578, 1, 0, 0.800802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.654133,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.04013);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241707,-99) , 
2, 2.09797, 0, 0, 0.422736,-99) , 
3, 1.95392, 0, 0, 0.516639,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.723387);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.114801,-99) , 
3, 1.90749, 1, 0, 0.413827,-99) , 
3, 1.95392, 0, 0, 0.478352,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.862289);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444319,-99) , 
3, 1.95841, 0, 0, 0.508716,-99) , 
NN(
0, 
0, 
-1, 1.80427, 0, -1, 0.0718171,-99) , 
3, 1.82145, 0, 0, 0.378104,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.958586);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.793489, 0, 1, 0.680489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0384384,-99) , 
3, 1.80427, 0, 0, 0.154881,-99) , 
3, 1.82145, 0, 0, 0.557771,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.606206);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.367837,-99) , 
3, 1.95392, 0, 0, 0.393465,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.385474);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.825578, 0, 1, 0.567575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.531326,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.846802);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80681, 0, 0, 0.661941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.73751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330109,-99) , 
0, -0.115391, 1, 0, 0.387855,-99) , 
0, 0.825825, 0, 0, 0.446348,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.287351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.65783, 0, 1, 0.553306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.530959,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.427586);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.915411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167819,-99) , 
0, 0.757283, 1, 0, 0.83247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425523,-99) , 
3, 1.95392, 0, 0, 0.440916,-99) , 
2, 3.888, 0, 0, 0.464655,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.450147);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0255121,-99) , 
0, 1.20164, 1, 0, 0.572601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.555773,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.554063);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.734998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457071,-99) , 
3, 1.88856, 0, 0, 0.514885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.174876,-99) , 
3, 1.93313, 0, 0, 0.29284,-99) , 
3, 1.90976, 1, 0, 0.455368,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.633398);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78347, 0, 0, 0.598162,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29022,-99) , 
3, 1.95625, 0, 0, 0.334317,-99) , 
3, 1.90976, 1, 0, 0.533316,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.36382);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258242,-99) , 
2, 0.815863, 0, 0, 0.512805,-99) , 
NN(
0, 
0, 
-1, 1.82183, 0, -1, 0.348808,-99) , 
0, 0.543726, 1, 0, 0.453459,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.303385);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.429846,-99) , 
3, 1.95392, 0, 0, 0.436632,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.176412);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490202,-99) , 
0, 0.875938, 0, 0, 0.519419,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.030322,-99) , 
0, 1.20196, 1, 0, 0.510345,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.229098);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.36145, 0, 1, 0.549922,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0359616,-99) , 
0, 1.20196, 1, 0, 0.541106,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.286777);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.970708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41513,-99) , 
2, 2.14552, 1, 0, 0.478353,-99) , 
2, 4.65955, 0, 0, 0.485853,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.331095);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482776,-99) , 
1, -0.409489, 1, 0, 0.535628,-99) , 
NN(
0, 
0, 
-1, 0.356604, 1, -1, 0.353701,-99) , 
2, 1.57334, 0, 0, 0.485974,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.229708);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.98967, 1, 1, 0.706346,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.013438,-99) , 
2, 0.416005, 0, 0, 0.500012,-99) , 
1, 1.68231, 0, 0, 0.526548,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.266625);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.98967, 1, 1, 0.656559,-99) , 
NN(
0, 
0, 
-1, 0.416005, 0, -1, 0.446536,-99) , 
1, 1.68231, 0, 0, 0.472613,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.325661);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0256002,-99) , 
2, 0.385905, 0, 0, 0.549326,-99) , 
NN(
0, 
0, 
-1, 0.648228, 1, -1, 0.369151,-99) , 
3, 1.82145, 0, 0, 0.522823,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.245182);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.99565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446499,-99) , 
0, 0.691095, 1, 0, 0.821455,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452319,-99) , 
3, 1.95392, 0, 0, 0.457876,-99) , 
2, 4.27377, 0, 0, 0.468335,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.152297);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.62496, 0, 1, 0.532493,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0556544,-99) , 
0, 1.20196, 1, 0, 0.526116,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0896041);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.959845,-99) , 
NN(
0, 
0, 
-1, 1.77729, 0, -1, 0.483131,-99) , 
2, 4.65955, 0, 0, 0.489068,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.081719);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.515819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.510918,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.112787);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.953693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48097,-99) , 
3, 1.95392, 0, 0, 0.485476,-99) , 
2, 4.65955, 0, 0, 0.490873,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.113012);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.62496, 0, 1, 0.523369,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0650384,-99) , 
0, 1.20196, 1, 0, 0.517964,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.110954);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485479,-99) , 
1, 2.81803, 0, 0, 0.49487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.490376,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.103056);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.521625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.517136,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.29375);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405155,-99) , 
1, 1.28648, 1, 0, 0.519943,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289612,-99) , 
0, 0.356604, 1, 0, 0.412087,-99) , 
2, 1.57334, 0, 0, 0.491817,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.30896);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307153,-99) , 
0, -0.0245024, 0, 0, 0.59528,-99) , 
NN(
0, 
0, 
-1, 0.416005, 0, -1, 0.438547,-99) , 
1, 1.68231, 0, 0, 0.457541,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.113078);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.65783, 0, 1, 0.524551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.520482,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0626167);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.488408,-99) , 
3, 1.95392, 0, 0, 0.492657,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.104304);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.944483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224754,-99) , 
2, 0.590069, 0, 0, 0.503375,-99) , 
2, 4.65955, 0, 0, 0.508054,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.131344);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.938753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474994,-99) , 
3, 1.95392, 0, 0, 0.478997,-99) , 
2, 4.65955, 0, 0, 0.483661,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0951946);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.62496, 0, 1, 0.519767,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0803189,-99) , 
0, 1.20196, 1, 0, 0.515356,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0599015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.488451,-99) , 
3, 1.95392, 0, 0, 0.492034,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0555166);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.510412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.506802,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0868294);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.995199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.925724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485476,-99) , 
2, 4.65955, 0, 0, 0.489569,-99) , 
0, -0.396603, 1, 0, 0.493117,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0830253);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.517554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.514132,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0518958);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.490276,-99) , 
3, 1.95392, 0, 0, 0.493651,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0856921);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496081,-99) , 
2, 3.62496, 0, 0, 0.510414,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0842252,-99) , 
0, 1.20196, 1, 0, 0.506455,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.129494);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.62496, 0, 1, 0.528918,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0910746,-99) , 
0, 1.20196, 1, 0, 0.524989,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0781062);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.994804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486677,-99) , 
3, 1.95392, 0, 0, 0.489929,-99) , 
0, -0.396603, 1, 0, 0.493212,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0740805);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.70673, 0, 1, 0.515479,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.00860679,-99) , 
2, -0.355549, 0, 0, 0.512248,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0793954);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490013,-99) , 
1, 2.81803, 0, 0, 0.497097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.493964,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0773893);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.516406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.513276,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0470555);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.491149,-99) , 
3, 1.95392, 0, 0, 0.494164,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.141378);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.994666,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48082,-99) , 
0, 0.68039, 0, 0, 0.502743,-99) , 
0, -0.396603, 1, 0, 0.505789,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.128824);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.62496, 0, 1, 0.528778,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0847601,-99) , 
0, 1.20196, 1, 0, 0.524892,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0796615);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489462,-99) , 
1, 2.81803, 0, 0, 0.496226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.493265,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0736522);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.515625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.512666,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0448537);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.491579,-99) , 
3, 1.95392, 0, 0, 0.494465,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0617493);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497855,-99) , 
2, 3.70673, 0, 0, 0.508537,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.00926943,-99) , 
2, -0.355549, 0, 0, 0.505552,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.12032);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.522167,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.00985404,-99) , 
2, -0.355549, 0, 0, 0.519195,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0624143);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.487017,-99) , 
3, 1.95392, 0, 0, 0.489773,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0470239);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.72969, 0, 1, 0.50855,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0917425,-99) , 
0, 1.20196, 1, 0, 0.505209,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0674132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.994283,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488273,-99) , 
3, 1.95392, 0, 0, 0.490882,-99) , 
0, -0.396603, 1, 0, 0.49364,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0855568);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0965912,-99) , 
0, 1.20196, 1, 0, 0.512784,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.010602,-99) , 
2, -0.355549, 0, 0, 0.510143,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.118724);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.993344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431567,-99) , 
0, 0.591094, 1, 0, 0.486717,-99) , 
0, -0.396603, 1, 0, 0.489295,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.111087);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.474531,-99) , 
3, 1.95392, 0, 0, 0.477049,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.124286);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.993287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482809,-99) , 
0, 0.68039, 0, 0, 0.502044,-99) , 
0, -0.396603, 1, 0, 0.50454,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.104362);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.523849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.52141,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0420145);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.375459, 1, 1, 0.886713,-99) , 
NN(
0, 
0, 
-1, 0.590069, 0, -1, 0.492477,-99) , 
2, 4.65955, 0, 0, 0.495574,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0467559);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.72969, 0, 1, 0.508864,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.0976598,-99) , 
0, 1.20196, 1, 0, 0.505914,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0858127);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488144,-99) , 
2, 3.70673, 0, 0, 0.496783,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.0107108,-99) , 
2, -0.355549, 0, 0, 0.494391,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0888433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.515774,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.0116593,-99) , 
2, -0.355549, 0, 0, 0.513394,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0689701);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.992992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487056,-99) , 
3, 1.95392, 0, 0, 0.48929,-99) , 
0, -0.396603, 1, 0, 0.491577,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0557521);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.72969, 0, 1, 0.511302,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.101951,-99) , 
0, 1.20196, 1, 0, 0.508517,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0375446);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.79189, 0, -1, 0.492661,-99) , 
3, 1.95392, 0, 0, 0.494768,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0538742);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.108034,-99) , 
0, 1.20196, 1, 0, 0.506257,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.0120551,-99) , 
2, -0.355549, 0, 0, 0.504076,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.069026);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.991936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486715,-99) , 
3, 1.95392, 0, 0, 0.488764,-99) , 
0, -0.396603, 1, 0, 0.490898,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0846466);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303698,-99) , 
2, 0.586827, 0, 0, 0.50994,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.0127138,-99) , 
2, -0.355549, 0, 0, 0.507874,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.140637);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.99061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45763,-99) , 
0, 0.323206, 1, 0, 0.485885,-99) , 
0, -0.396603, 1, 0, 0.487873,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.252111);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43106,-99) , 
3, 1.90976, 1, 0, 0.503421,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.987222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317422,-99) , 
1, -0.993099, 1, 0, 0.4029,-99) , 
0, -0.114504, 0, 0, 0.491858,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.263366);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449223,-99) , 
3, 1.93061, 0, 0, 0.470076,-99) , 
3, 1.95392, 0, 0, 0.472409,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.125585);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.529487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.527384,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0326431);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.993439,-99) , 
NN(
0, 
0, 
-1, 1.21617, 1, -1, 0.494025,-99) , 
0, -0.396603, 1, 0, 0.496263,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0363024);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.993223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.105905,-99) , 
0, 1.21617, 1, 0, 0.502185,-99) , 
0, -0.396603, 1, 0, 0.504351,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0501783);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.992974,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491352,-99) , 
3, 1.95392, 0, 0, 0.493218,-99) , 
0, -0.396603, 1, 0, 0.495384,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0454008);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.992615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.505671,-99) , 
0, -0.396603, 1, 0, 0.50773,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0501192);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.992275,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.853395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491877,-99) , 
2, 4.65955, 0, 0, 0.494403,-99) , 
0, -0.396603, 1, 0, 0.496462,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0528206);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.991881,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.10999,-99) , 
0, 1.21617, 1, 0, 0.506759,-99) , 
0, -0.396603, 1, 0, 0.508717,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0468763);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.991444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491913,-99) , 
3, 1.95392, 0, 0, 0.493705,-99) , 
0, -0.396603, 1, 0, 0.495664,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0806992);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297788,-99) , 
2, 0.586827, 0, 0, 0.509052,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.0133362,-99) , 
2, -0.355549, 0, 0, 0.50721,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0754663);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.990291,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484516,-99) , 
3, 1.95392, 0, 0, 0.486243,-99) , 
0, -0.396603, 1, 0, 0.488108,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0408015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.508484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.50671,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0273758);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.989538,-99) , 
NN(
0, 
0, 
-1, 1.21617, 1, -1, 0.49485,-99) , 
0, -0.396603, 1, 0, 0.49658,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0418855);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498108,-99) , 
1, 2.81803, 0, 0, 0.505081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.503377,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0674966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.515266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.513562,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0347979);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496205,-99) , 
2, 4.72969, 0, 0, 0.498992,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.115332,-99) , 
0, 1.20196, 1, 0, 0.496803,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0388066);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.72969, 0, 1, 0.507597,-99) , 
NN(
0, 
0, 
-1, 1.88826, 0, -1, 0.11893,-99) , 
0, 1.20196, 1, 0, 0.505407,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.04278);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.989647,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492511,-99) , 
3, 1.95392, 0, 0, 0.494128,-99) , 
0, -0.396603, 1, 0, 0.495814,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.128358);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478566,-99) , 
2, 2.14678, 1, 0, 0.508071,-99) , 
NN(
0, 
0, 
-1, -0.962197, 1, -1, 0.0138685,-99) , 
2, -0.355549, 0, 0, 0.50637,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.166212);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.54013, 1, 1, 0.533181,-99) , 
NN(
0, 
0, 
-1, 0.908667, 1, -1, 0.434407,-99) , 
2, 1.57334, 0, 0, 0.50796,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.150553);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0331408,-99) , 
0, 0.910249, 1, 0, 0.555225,-99) , 
NN(
0, 
0, 
-1, 1.4272, 0, -1, 0.47475,-99) , 
2, 1.18756, 1, 0, 0.487589,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0679265);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.515463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.513854,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0390949);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.375459, 1, 1, 0.848941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255081,-99) , 
2, 0.590069, 0, 0, 0.494579,-99) , 
2, 4.65955, 0, 0, 0.496981,-99)    );
   return;
};
 
// Clean up
inline void ReadD2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadD2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
