// Class: ReadD4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::D4
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : jlang
Date           : Tue Dec  8 16:22:07 2015
Host           : Linux ekpams2 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 21:44:51 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /usr/users/jlang/BDT/Test/BDT_Training
Training events: 1332
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "10" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
MaxDepth: "4" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1332" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
v0                            v0                            v0                            v0                                                              'F'    [-0.490635514259,1.48405468464]
v1                            v1                            v1                            v1                                                              'F'    [-7.37883806229,7.25839614868]
v2                            v2                            v2                            v2                                                              'F'    [-1.8986569643,6.2026591301]
v3                            v3                            v3                            v3                                                              'F'    [1.46819293499,2.39548110962]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new D4Node
   
#ifndef D4Node__def
#define D4Node__def
   
class D4Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   D4Node ( D4Node* left,D4Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~D4Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   D4Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   D4Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   D4Node*   fLeft;     // pointer to the left daughter node
   D4Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   D4Node::~D4Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool D4Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool D4Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadD4 : public IClassifierReader {

 public:

   // constructor
   ReadD4( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadD4" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "v0", "v1", "v2", "v3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.490635514259338;
      fVmax[0] = 1.48405468463898;
      fVmin[1] = -7.37883806228638;
      fVmax[1] = 7.25839614868164;
      fVmin[2] = -1.89865696430206;
      fVmax[2] = 6.20265913009644;
      fVmin[3] = 1.46819293498993;
      fVmax[3] = 2.39548110961914;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadD4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<D4Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadD4::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      D4Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(D4Node*)current->GetRight();
         else current=(D4Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadD4::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(2.80495400674181);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95556, 0, 1, 0.99604,-99) , 
NN(
NN(
0, 
0, 
-1, 1.91869, 0, 1, 0.909091,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.272727,-99) , 
0, 0.614518, 1, 0, 0.595238,-99) , 
2, 3.02924, 0, 0, 0.703125,-99) , 
3, 1.93313, 0, 0, 0.963093,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.784314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344262,-99) , 
2, 1.93214, 0, 0, 0.619632,-99) , 
NN(
0, 
0, 
-1, 1.69779, 0, -1, 0.131579,-99) , 
0, 0.601282, 1, 0, 0.418773,-99) , 
NN(
0, 
0, 
-1, 1.7884, 0, -1, 0.00411523,-99) , 
3, 1.80449, 0, 0, 0.154653,-99) , 
3, 1.90976, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.18871);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.980612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440285,-99) , 
2, 1.98415, 1, 0, 0.860373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416606,-99) , 
0, 0.641929, 0, 0, 0.486558,-99) , 
0, -0.285284, 1, 0, 0.517538,-99) , 
3, 1.95514, 0, 0, 0.627749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.518543,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.27039);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95514, 0, 1, 0.749783,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.737063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.23349,-99) , 
2, 1.3018, 0, 0, 0.640423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0786166,-99) , 
1, -0.544062, 1, 0, 0.213908,-99) , 
3, 1.88177, 0, 0, 0.38192,-99) , 
0, 0.825578, 1, 0, 0.694841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.615991,-99)    );
  // itree = 3
  fBoostWeights.push_back(1.13041);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.913162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334089,-99) , 
2, 2.05509, 1, 0, 0.606044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314721,-99) , 
2, 3.58869, 0, 0, 0.332928,-99) , 
0, -0.00597324, 1, 0, 0.388136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.351667,-99) , 
3, 1.95392, 0, 0, 0.405333,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.624542);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 1.97917, 1, 1, 0.603871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.20437, 1, 0, 0.592332,-99) , 
3, 1.95514, 0, 0, 0.615625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.586034,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.776622);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.160551,-99) , 
3, 1.90923, 1, 0, 0.536026,-99) , 
NN(
0, 
0, 
-1, 0.664659, 1, -1, 0.374291,-99) , 
2, 1.97917, 1, 0, 0.448982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.425793,-99) , 
3, 1.95392, 0, 0, 0.44993,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.342514);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.9585, 0, 1, 0.541131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78193, 0, 0, 0.528119,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756828,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0.543527, 0, -1, 0.0929006,-99) , 
3, 1.94995, 0, 0, 0.123757,-99) , 
1, 2.19006, 0, 0, 0.21869,-99) , 
2, 0.801782, 0, 0, 0.497981,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.59392);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.847287,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407626,-99) , 
1, -1.76484, 1, 0, 0.431354,-99) , 
NN(
0, 
0, 
-1, 0.555358, 1, -1, 0.139357,-99) , 
3, 1.81501, 0, 0, 0.397458,-99) , 
2, 4.64128, 0, 0, 0.412963,-99) , 
3, 1.95392, 0, 0, 0.428365,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.826931);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.741315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313574,-99) , 
2, 3.08725, 1, 0, 0.689753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.301351,-99) , 
0, 0.29549, 1, 0, 0.501888,-99) , 
0, 0.496705, 0, 0, 0.58832,-99) , 
0, -0.215466, 1, 0, 0.604508,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.0304545, 1, 1, 0.76757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.25535,-99) , 
2, 2.38911, 1, 0, 0.443967,-99) , 
2, 2.79526, 0, 0, 0.528147,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209708,-99) , 
2, 2.51218, 0, 0, 0.321588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.81192, 0, 0, 0.217676,-99) , 
0, 0.648228, 1, 0, 0.438507,-99) , 
3, 1.8656, 0, 0, 0.532535,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.75248);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.92297, 0, 1, 0.625254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.90527, 0, -1, 0.31347,-99) , 
3, 1.95011, 0, 0, 0.342655,-99) , 
1, 0.721156, 1, 0, 0.532892,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.4836, 0, 1, 0.801826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209792,-99) , 
0, 0.601282, 1, 0, 0.66787,-99) , 
NN(
NN(
0, 
0, 
-1, -1.34574, 0, -1, 0.323958,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.9182, 0, 0, 0.0250178,-99) , 
2, 0.487514, 0, 0, 0.301524,-99) , 
1, 1.68231, 0, 0, 0.352214,-99) , 
2, 1.95911, 0, 0, 0.448485,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.392604);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.90732, 1, 1, 0.577004,-99) , 
NN(
0, 
0, 
-1, -0.0800569, 0, -1, 0.42255,-99) , 
3, 1.89219, 0, 0, 0.479282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.46547,-99) , 
3, 1.95392, 0, 0, 0.47516,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.207444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 3.32381, 0, 1, 0.519993,-99) , 
NN(
0, 
0, 
-1, 3.62285, 0, -1, 0.284746,-99) , 
2, 3.56219, 1, 0, 0.500589,-99) , 
2, 4.74847, 0, 0, 0.50918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.500695,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.334149);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273232,-99) , 
0, -0.192181, 0, 0, 0.495095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208608,-99) , 
0, 0.224511, 0, 0, 0.363368,-99) , 
3, 1.90758, 1, 0, 0.461504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.45076,-99) , 
3, 1.95392, 0, 0, 0.458537,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.472267);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407321,-99) , 
2, 4.36687, 0, 0, 0.416648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.20437, 1, 0, 0.409461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.401299,-99) , 
3, 1.95392, 0, 0, 0.408572,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.566134);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426784,-99) , 
0, 0.630767, 1, 0, 0.635344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198568,-99) , 
0, -0.245229, 1, 0, 0.386297,-99) , 
0, 0.0050911, 0, 0, 0.588461,-99) , 
NN(
NN(
0, 
0, 
-1, -0.193603, 0, 1, 0.742555,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320151,-99) , 
2, 2.52023, 1, 0, 0.43151,-99) , 
0, -0.00831538, 1, 0, 0.478405,-99) , 
1, 0.288285, 0, 0, 0.523352,-99) , 
NN(
0, 
0, 
-1, 0.184785, 0, -1, 0.00666634,-99) , 
0, 1.20196, 1, 0, 0.515764,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.5436);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.98452, 0, 1, 0.908111,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332876,-99) , 
0, 0.619336, 1, 0, 0.790209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444953,-99) , 
3, 1.90148, 0, 0, 0.49473,-99) , 
3, 1.92304, 0, 0, 0.538923,-99) , 
1, -1.61104, 1, 0, 0.568684,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.80199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435465,-99) , 
0, 0.952207, 0, 0, 0.470163,-99) , 
NN(
0, 
0, 
-1, 0.494814, 0, -1, 0.0389193,-99) , 
0, 1.10792, 1, 0, 0.457484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.94819,-99) , 
NN(
0, 
0, 
-1, 1.88048, 0, -1, 0.120688,-99) , 
0, -0.115028, 1, 0, 0.162454,-99) , 
1, -1.80275, 0, 0, 0.428515,-99) , 
2, 2.73067, 0, 0, 0.467754,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.497602);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00680704,-99) , 
2, -0.34119, 0, 0, 0.587472,-99) , 
NN(
0, 
0, 
-1, 0.487572, 0, -1, 0.0178966,-99) , 
0, 1.20164, 1, 0, 0.581956,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0772539,-99) , 
3, 1.92855, 0, 0, 0.107636,-99) , 
2, 3.10648, 0, 0, 0.312744,-99) , 
1, -2.25668, 0, 0, 0.56779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.561913,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.417795);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440657,-99) , 
0, 0.366441, 1, 0, 0.496147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338059,-99) , 
0, -0.110549, 1, 0, 0.362444,-99) , 
3, 1.89988, 1, 0, 0.455519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.448436,-99) , 
3, 1.95392, 0, 0, 0.453441,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.758094);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.734252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487682,-99) , 
2, 2.85515, 1, 0, 0.653304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.220497,-99) , 
2, 0.780805, 1, 0, 0.377126,-99) , 
2, 1.47655, 0, 0, 0.592217,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.798267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 2.33487, 0, 0, 0.499946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.553381, 1, 0, 0.12536,-99) , 
3, 1.81605, 0, 0, 0.553234,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -1.24169, 1, 1, 0.998119,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366701,-99) , 
3, 1.91364, 0, 0, 0.47721,-99) , 
1, -0.731778, 1, 0, 0.584313,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.995504,-99) , 
NN(
0, 
0, 
-1, 0.697477, 0, -1, 0.369504,-99) , 
1, 2.66099, 0, 0, 0.382652,-99) , 
2, 2.768, 0, 0, 0.42643,-99) , 
0, 0.449693, 0, 0, 0.484003,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.554929);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.995417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303581,-99) , 
1, 1.20793, 1, 0, 0.863452,-99) , 
NN(
0, 
0, 
-1, 1.22257, 1, 1, 0.580537,-99) , 
2, 3.73291, 0, 0, 0.597008,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.870475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224943,-99) , 
2, 2.1675, 0, 0, 0.683815,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.117428,-99) , 
0, 0.983939, 0, 0, 0.285916,-99) , 
1, 0.147059, 0, 0, 0.447413,-99) , 
0, 0.825825, 1, 0, 0.573762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.9182, 0, 0, 0.0154792,-99) , 
1, 1.22077, 0, 0, 0.160978,-99) , 
2, 0.416005, 0, 0, 0.561768,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.431505);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.997039,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0102097,-99) , 
3, 1.81861, 0, 0, 0.440642,-99) , 
1, -1.22304, 1, 0, 0.520012,-99) , 
3, 1.92362, 0, 0, 0.584564,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, -0.192128, 0, -1, 0.435565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.951929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.154529,-99) , 
0, -0.0273964, 1, 0, 0.207472,-99) , 
1, -1.80275, 0, 0, 0.419579,-99) , 
3, 1.94995, 0, 0, 0.425659,-99) , 
2, 3.11644, 0, 0, 0.449576,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.362651);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.950132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.135091,-99) , 
2, 0.716469, 0, 0, 0.81462,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.252305,-99) , 
0, 0.730341, 0, 0, 0.475858,-99) , 
0, 0.359767, 1, 0, 0.672944,-99) , 
NN(
NN(
0, 
0, 
-1, 1.70462, 1, 1, 0.532255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0135453,-99) , 
1, -0.625942, 0, 0, 0.378644,-99) , 
2, 1.47953, 0, 0, 0.514057,-99) , 
2, 0.979773, 1, 0, 0.533309,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547023,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.9182, 0, 0, 0.0154792,-99) , 
1, 1.22077, 0, 0, 0.207658,-99) , 
2, 0.416005, 0, 0, 0.526177,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.603378);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.162576, 0, 1, 0.926683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0581914,-99) , 
0, 0.205974, 0, 0, 0.608826,-99) , 
0, -0.00647524, 1, 0, 0.659308,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.868452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0415689,-99) , 
0, 0.0761878, 0, 0, 0.529305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.94848, 0, 0, 0.0124854,-99) , 
0, 0.1679, 1, 0, 0.162535,-99) , 
2, 0.597373, 0, 0, 0.583498,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.997261,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.717247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414269,-99) , 
2, 1.58894, 1, 0, 0.434508,-99) , 
2, 4.83827, 0, 0, 0.439321,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.890159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.041121,-99) , 
2, 1.29112, 0, 0, 0.444747,-99) , 
NN(
0, 
0, 
-1, 1.27912, 1, -1, 0.0316021,-99) , 
3, 1.88466, 0, 0, 0.179678,-99) , 
2, 1.4272, 0, 0, 0.422911,-99) , 
2, 1.18756, 1, 0, 0.449127,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.568798);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.36891, 0, 1, 0.59289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.135988,-99) , 
2, 3.68735, 0, 0, 0.442636,-99) , 
2, 3.56059, 1, 0, 0.577081,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0571383,-99) , 
1, 0.934155, 1, 0, 0.104305,-99) , 
NN(
0, 
0, 
-1, 2.7115, 0, -1, 0.00106812,-99) , 
1, 0.184785, 0, 0, 0.0169515,-99) , 
0, 1.20196, 1, 0, 0.573254,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.810286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0334874,-99) , 
2, 0.724296, 0, 0, 0.723029,-99) , 
NN(
0, 
0, 
-1, 0.775853, 1, -1, 0.382159,-99) , 
1, 0.825742, 0, 0, 0.492106,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.947991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.337922, 1, 0, 0.615722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, -0.0829259, 1, 0, 0.0868995,-99) , 
3, 1.81856, 0, 0, 0.43475,-99) , 
2, 1.57334, 0, 0, 0.541404,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.423017);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.333641, 1, 1, 0.675442,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.92965, 0, 0, 0.0533375,-99) , 
2, 0.561697, 0, 0, 0.633745,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.75783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.165853, 1, 0, 0.519409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.00730645, 1, 0, 0.127224,-99) , 
3, 1.81856, 0, 0, 0.571743,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.996212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0139905,-99) , 
2, 2.74766, 0, 0, 0.805153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44141,-99) , 
3, 1.95723, 0, 0, 0.44431,-99) , 
1, 2.41712, 0, 0, 0.44898,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.870443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.101961,-99) , 
2, 1.29112, 0, 0, 0.538559,-99) , 
NN(
0, 
0, 
-1, 1.27912, 1, -1, 0.0466138,-99) , 
3, 1.88466, 0, 0, 0.228098,-99) , 
2, 1.4272, 0, 0, 0.438585,-99) , 
2, 1.18756, 1, 0, 0.457525,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.328305);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.27819, 0, 1, 0.959635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.188825,-99) , 
3, 1.83783, 0, 0, 0.567446,-99) , 
1, -1.21588, 1, 0, 0.611764,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0917529, 1, 1, 0.537402,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.028716,-99) , 
0, -0.199841, 1, 0, 0.323031,-99) , 
0, -0.169089, 0, 0, 0.516805,-99) , 
2, 2.88848, 0, 0, 0.537086,-99) , 
NN(
0, 
0, 
-1, 0.406791, 0, -1, 0.0176384,-99) , 
0, 1.20196, 1, 0, 0.533813,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.24405);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.993007,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.732659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453311,-99) , 
3, 1.93835, 0, 0, 0.45969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.454775,-99) , 
3, 1.95392, 0, 0, 0.457585,-99) , 
0, -0.396603, 1, 0, 0.46089,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.337265);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.87104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153911,-99) , 
0, 0.61129, 1, 0, 0.696841,-99) , 
NN(
0, 
0, 
-1, 3.20776, 0, 1, 0.524483,-99) , 
2, 1.70267, 1, 0, 0.542747,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32183,-99) , 
0, 0.333089, 1, 0, 0.452211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.808, 0, 0, 0.419885,-99) , 
2, 1.47655, 0, 0, 0.520517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.517781,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.26083);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.991092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442997,-99) , 
2, 3.34357, 0, 0, 0.454258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.450118,-99) , 
3, 1.95392, 0, 0, 0.452505,-99) , 
0, -0.396603, 1, 0, 0.455051,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.349994);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.60361, 1, 1, 0.967675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.201701,-99) , 
0, 0.671504, 1, 0, 0.793857,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389416,-99) , 
2, 2.99608, 1, 0, 0.517762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0619324,-99) , 
3, 1.83555, 0, 0, 0.345707,-99) , 
1, -1.80275, 0, 0, 0.507649,-99) , 
2, 3.24166, 0, 0, 0.516043,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.917848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.154428,-99) , 
1, 1.20793, 1, 0, 0.673827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.996574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0642769,-99) , 
2, 3.56282, 1, 0, 0.220877,-99) , 
2, 3.63634, 0, 0, 0.486189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0420696,-99) , 
0, 0.848696, 1, 0, 0.392382,-99) , 
2, 3.50222, 1, 0, 0.506095,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.427518);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0122502,-99) , 
2, 2.9964, 1, 0, 0.334216,-99) , 
2, 3.06372, 0, 0, 0.761527,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349475,-99) , 
2, 3.51054, 1, 0, 0.503894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.259306,-99) , 
1, 1.31866, 1, 0, 0.474785,-99) , 
3, 1.92304, 0, 0, 0.501753,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 2.51947, 1, -1, 0.444402,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.986057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.18014,-99) , 
1, -0.859834, 1, 0, 0.283099,-99) , 
0, -0.186879, 0, 0, 0.429777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.941291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0057852,-99) , 
1, 0.990074, 1, 0, 0.328654,-99) , 
NN(
0, 
0, 
-1, 0.190259, 0, -1, 0.000447405,-99) , 
1, 0.494814, 0, 0, 0.0570879,-99) , 
0, 1.10792, 1, 0, 0.421494,-99) , 
2, 2.73067, 0, 0, 0.443133,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.62407);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487433,-99) , 
1, 0.102428, 1, 0, 0.574297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.70065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0998153,-99) , 
0, 0.930886, 0, 0, 0.392217,-99) , 
0, 0.800329, 1, 0, 0.551454,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.912706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.990074, 1, 0, 0.324956,-99) , 
NN(
0, 
0, 
-1, 0.190259, 0, -1, 0.000995917,-99) , 
1, 0.494814, 0, 0, 0.0762687,-99) , 
0, 1.10792, 1, 0, 0.542614,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 2.50656, 1, 1, 0.651149,-99) , 
NN(
0, 
0, 
-1, 1.28044, 1, -1, 0.220709,-99) , 
0, -0.0125554, 0, 0, 0.572966,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.994033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442525,-99) , 
0, -0.00820514, 1, 0, 0.484562,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.136204,-99) , 
2, 2.47365, 1, 0, 0.244725,-99) , 
2, 2.71977, 0, 0, 0.375076,-99) , 
1, 0.155834, 0, 0, 0.473715,-99) , 
2, 2.34489, 1, 0, 0.510592,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.526597);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.993191,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205154,-99) , 
2, 0.821414, 0, 0, 0.645647,-99) , 
NN(
0, 
0, 
-1, 1.83714, 0, -1, 0.398171,-99) , 
2, 2.519, 1, 0, 0.545208,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398243,-99) , 
0, 0.766402, 1, 0, 0.592803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386449,-99) , 
0, 0.144509, 1, 0, 0.438145,-99) , 
2, 2.73067, 0, 0, 0.47533,-99) , 
1, 0.288285, 0, 0, 0.504129,-99) , 
0, -0.396603, 1, 0, 0.506795,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.585972);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.500757, 1, 1, 0.618434,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.9779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374947,-99) , 
1, -1.21588, 1, 0, 0.446921,-99) , 
2, 2.93073, 1, 0, 0.579136,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.858788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.520083, 0, 0, 0.543425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.553381, 1, 0, 0.24041,-99) , 
3, 1.81605, 0, 0, 0.562179,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.749176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0203105,-99) , 
2, 2.85308, 1, 0, 0.703359,-99) , 
NN(
0, 
0, 
-1, -0.0123578, 1, -1, 0.0507983,-99) , 
1, -0.764874, 0, 0, 0.613322,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258744,-99) , 
2, 1.57869, 0, 0, 0.846362,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417239,-99) , 
2, 3.39558, 0, 0, 0.436377,-99) , 
3, 1.93501, 0, 0, 0.454311,-99) , 
3, 1.82576, 1, 0, 0.481151,-99) , 
0, 0.449693, 0, 0, 0.516555,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.576664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.90318, 0, 1, 0.592871,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.962683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377723,-99) , 
2, 1.67572, 0, 0, 0.660257,-99) , 
NN(
0, 
0, 
-1, -0.634118, 1, -1, 0.183753,-99) , 
2, 1.99771, 1, 0, 0.433756,-99) , 
3, 1.82145, 0, 0, 0.569083,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.796785, 1, 1, 0.67738,-99) , 
NN(
0, 
0, 
-1, 0.588737, 1, -1, 0.251696,-99) , 
0, 0.636034, 0, 0, 0.612806,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00524719,-99) , 
2, 0.609676, 0, 0, 0.634792,-99) , 
NN(
0, 
0, 
-1, 2.6206, 1, -1, 0.350725,-99) , 
2, 0.737519, 1, 0, 0.384544,-99) , 
2, 2.73067, 0, 0, 0.452772,-99) , 
0, 0.543726, 1, 0, 0.532728,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.246446);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.890329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44687,-99) , 
0, 0.347247, 0, 0, 0.697706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.99875,-99) , 
NN(
0, 
0, 
-1, -0.192128, 0, -1, 0.453317,-99) , 
2, 4.74506, 0, 0, 0.455433,-99) , 
3, 1.93061, 0, 0, 0.469007,-99) , 
3, 1.95392, 0, 0, 0.471316,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.152726);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 2.87969, 0, 1, 0.528209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.92398, 0, 0, 0.0286697,-99) , 
2, 0.385905, 0, 0, 0.524947,-99) , 
1, 2.81803, 0, 0, 0.530135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.528193,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.234376);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.982086,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.622192, 1, 1, 0.547355,-99) , 
NN(
0, 
0, 
-1, -0.130401, 0, -1, 0.459323,-99) , 
1, 0.288285, 0, 0, 0.494389,-99) , 
NN(
NN(
0, 
0, 
-1, 2.21531, 0, 1, 0.973919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0522554,-99) , 
1, 0.433924, 1, 0, 0.311251,-99) , 
0, -0.301866, 0, 0, 0.488572,-99) , 
0, -0.396603, 1, 0, 0.490787,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.528942);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.904549, 0, 1, 0.634523,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.96662, 0, 0, 0.0263269,-99) , 
2, 0.783165, 0, 0, 0.612596,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.967221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356781,-99) , 
0, -0.383766, 0, 0, 0.947615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224971,-99) , 
0, -0.126413, 0, 0, 0.508874,-99) , 
0, -0.302605, 1, 0, 0.514345,-99) , 
1, 0.183874, 0, 0, 0.539482,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.611697, 1, 1, 0.79996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.179586,-99) , 
1, 2.1064, 0, 0, 0.339024,-99) , 
2, 2.9461, 1, 0, 0.591287,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.992115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323664,-99) , 
1, 2.10119, 1, 0, 0.544001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195462,-99) , 
2, 1.62271, 1, 0, 0.27466,-99) , 
1, 1.7884, 0, 0, 0.357711,-99) , 
3, 1.89609, 0, 0, 0.405134,-99) , 
1, 0.985296, 1, 0, 0.502803,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.563015);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.030328,-99) , 
0, 0.0812667, 0, 0, 0.821623,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00118517,-99) , 
2, 1.9915, 1, 0, 0.502359,-99) , 
2, 2.29503, 0, 0, 0.621805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.968643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 2.48928, 0, 0, 0.244063,-99) , 
3, 1.82343, 0, 0, 0.544741,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.82773, 0, 0, 0.714872,-99) , 
NN(
0, 
0, 
-1, 1.52337, 1, -1, 0.411648,-99) , 
1, -1.63929, 1, 0, 0.420656,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 2.23661, 0, -1, 0.158502,-99) , 
2, 3.06885, 0, 0, 0.257804,-99) , 
1, -2.20185, 0, 0, 0.41319,-99) , 
1, 1.68231, 0, 0, 0.426648,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.332605);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.988487,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416043,-99) , 
0, -0.16159, 0, 0, 0.548475,-99) , 
NN(
0, 
0, 
-1, 1.43307, 0, -1, 0.0208899,-99) , 
0, 1.21617, 1, 0, 0.546631,-99) , 
0, -0.396603, 1, 0, 0.548935,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335266,-99) , 
3, 1.85044, 0, 0, 0.678775,-99) , 
NN(
0, 
0, 
-1, 0.839831, 1, -1, 0.0971391,-99) , 
2, 1.45, 0, 0, 0.529927,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0153344,-99) , 
1, -2.23253, 0, 0, 0.0307295,-99) , 
2, 2.26189, 0, 0, 0.133077,-99) , 
3, 1.91564, 1, 0, 0.407741,-99) , 
1, -1.80275, 0, 0, 0.541291,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.277048);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.312545, 0, 1, 0.994635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326193,-99) , 
2, 1.53684, 0, 0, 0.855977,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236738,-99) , 
1, 0.0330029, 1, 0, 0.413999,-99) , 
0, -0.360595, 0, 0, 0.679689,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.785797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460355,-99) , 
3, 1.93835, 0, 0, 0.466426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.462254,-99) , 
3, 1.95392, 0, 0, 0.464193,-99) , 
0, -0.208537, 1, 0, 0.476363,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.338814);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.279192, 1, 1, 0.999792,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.50941, 1, -1, 0.319252,-99) , 
3, 1.86534, 0, 0, 0.555081,-99) , 
2, 3.02258, 0, 0, 0.690314,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452322,-99) , 
1, -0.746808, 0, 0, 0.57436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00293215,-99) , 
0, 1.02422, 1, 0, 0.510428,-99) , 
1, -0.408727, 1, 0, 0.532705,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.872691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0738217,-99) , 
1, 0.982454, 1, 0, 0.434656,-99) , 
NN(
0, 
0, 
-1, 0.137769, 0, -1, 0.00501724,-99) , 
1, 0.406791, 0, 0, 0.0814641,-99) , 
0, 1.16187, 1, 0, 0.530402,-99) , 
0, -0.208537, 1, 0, 0.538633,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.527695);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.0465421, 1, 1, 0.971222,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.984281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348878,-99) , 
1, -0.854378, 1, 0, 0.703798,-99) , 
0, -0.289448, 0, 0, 0.877287,-99) , 
NN(
NN(
0, 
0, 
-1, 1.78375, 1, 1, 0.606009,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.861651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260493,-99) , 
1, -0.628975, 0, 0, 0.427417,-99) , 
0, 0.194222, 0, 0, 0.553126,-99) , 
0, -0.021085, 1, 0, 0.586564,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.867569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47361,-99) , 
2, 2.44883, 1, 0, 0.510385,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290597,-99) , 
0, 0.308626, 1, 0, 0.394857,-99) , 
2, 2.27588, 0, 0, 0.453125,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.92118, 0, 0, 0.0265599,-99) , 
0, 1.01845, 1, 0, 0.443215,-99) , 
1, -0.408727, 1, 0, 0.491792,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.547913);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.965673, 1, 1, 0.679587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429419,-99) , 
0, 0.23052, 1, 0, 0.507386,-99) , 
1, 0.155834, 0, 0, 0.592915,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0584836,-99) , 
0, -0.0434966, 0, 0, 0.473491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.646755, 1, 0, 0.386527,-99) , 
3, 1.83706, 0, 0, 0.559075,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.963438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.8255, 0, 0, 0.921668,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33906,-99) , 
2, 1.58882, 1, 0, 0.430973,-99) , 
1, 1.91415, 0, 0, 0.452927,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00110108,-99) , 
1, 2.61542, 0, 0, 0.170746,-99) , 
1, 2.37932, 1, 0, 0.436653,-99) , 
2, 1.95911, 0, 0, 0.50695,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.67036);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.378623, 0, 1, 0.616279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.164085,-99) , 
0, 0.153554, 1, 0, 0.465426,-99) , 
0, 0.261487, 0, 0, 0.568919,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379971,-99) , 
3, 1.8673, 1, 0, 0.517453,-99) , 
NN(
0, 
0, 
-1, 2.03689, 1, -1, 0.318292,-99) , 
2, 2.57013, 0, 0, 0.43448,-99) , 
1, 0.721156, 1, 0, 0.52858,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.778295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346592,-99) , 
1, 1.23796, 0, 0, 0.389995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0661756,-99) , 
1, 2.3102, 1, 0, 0.362443,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.947664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.782065, 0, 0, 0.792585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, -0.0829259, 1, 0, 0.0763336,-99) , 
3, 1.81856, 0, 0, 0.328845,-99) , 
2, 1.57334, 0, 0, 0.480948,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.518874);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.721156, 1, 1, 0.894737,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.133657,-99) , 
2, 1.89812, 0, 0, 0.427781,-99) , 
0, 0.426597, 0, 0, 0.668308,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.860344,-99) , 
NN(
0, 
0, 
-1, 1.83709, 0, -1, 0.446007,-99) , 
3, 1.82702, 1, 0, 0.460767,-99) , 
3, 1.93109, 0, 0, 0.474609,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.968606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.745331, 1, 0, 0.923457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.968389, 1, 0, 0.289918,-99) , 
2, 1.64484, 0, 0, 0.544059,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.824523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.215101,-99) , 
1, 1.12479, 0, 0, 0.348639,-99) , 
NN(
0, 
0, 
-1, -1.34729, 1, -1, 0.0497637,-99) , 
2, 2.72458, 0, 0, 0.188707,-99) , 
2, 2.01785, 1, 0, 0.344915,-99) , 
3, 1.82145, 0, 0, 0.457008,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.590322);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.436624, 0, 1, 0.65327,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477149,-99) , 
3, 1.87606, 0, 0, 0.567446,-99) , 
1, 0.280671, 0, 0, 0.600263,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.692231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0466976,-99) , 
2, 0.532405, 0, 0, 0.630832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.13466,-99) , 
1, -0.0733901, 1, 0, 0.27458,-99) , 
2, 0.869647, 1, 0, 0.469197,-99) , 
2, 1.113, 0, 0, 0.585339,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.256538,-99) , 
0, 0.275644, 0, 0, 0.475408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.648228, 1, 0, 0.414457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.815989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 2.47617, 0, 0, 0.0649884,-99) , 
1, 1.65846, 1, 0, 0.355345,-99) , 
3, 1.82145, 0, 0, 0.558379,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.400066);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282495,-99) , 
1, 0.853371, 1, 0, 0.859685,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365114,-99) , 
3, 1.83736, 0, 0, 0.557373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470897,-99) , 
0, -0.215466, 1, 0, 0.480499,-99) , 
3, 1.87646, 1, 0, 0.513349,-99) , 
2, 4.38492, 0, 0, 0.519039,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.89188, 1, 1, 0.658597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341268,-99) , 
3, 1.81468, 1, 0, 0.477199,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.817718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.346397, 1, 0, 0.381839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, -0.467965, 1, 0, 0.210659,-99) , 
3, 1.80427, 0, 0, 0.35897,-99) , 
3, 1.82145, 0, 0, 0.50185,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.362931);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370038,-99) , 
1, 0.853371, 1, 0, 0.863398,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.206443,-99) , 
2, 4.11369, 1, 0, 0.576761,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.828236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475821,-99) , 
3, 1.827, 1, 0, 0.498932,-99) , 
3, 1.87646, 0, 0, 0.544082,-99) , 
2, 4.38492, 0, 0, 0.54854,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.653757, 1, 0, 0.490762,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.750428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.346397, 1, 0, 0.366493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, -0.467965, 1, 0, 0.205903,-99) , 
3, 1.80427, 0, 0, 0.373632,-99) , 
3, 1.82145, 0, 0, 0.531228,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.492391);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.829861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479286,-99) , 
1, -0.740307, 0, 0, 0.747581,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.107996,-99) , 
1, 1.39929, 0, 0, 0.358133,-99) , 
1, 0.565251, 1, 0, 0.636068,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.188452,-99) , 
0, 0.800717, 1, 0, 0.62362,-99) , 
NN(
0, 
0, 
-1, -0.129398, 0, -1, 0.476659,-99) , 
2, 2.93073, 0, 0, 0.507719,-99) , 
3, 1.84914, 1, 0, 0.531784,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.961226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.73781, 0, 0, 0.884384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.968389, 1, 0, 0.262063,-99) , 
2, 1.64484, 0, 0, 0.47712,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.101094,-99) , 
2, 3.47641, 1, 0, 0.396796,-99) , 
NN(
0, 
0, 
-1, -1.34729, 1, -1, 0.0556716,-99) , 
2, 2.72458, 0, 0, 0.229018,-99) , 
2, 2.01785, 1, 0, 0.333297,-99) , 
3, 1.82145, 0, 0, 0.513112,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.451115);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.0412564, 1, 1, 0.644019,-99) , 
NN(
NN(
0, 
0, 
-1, 0.704166, 0, 1, 0.566027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.91811, 0, 0, 0.0312049,-99) , 
0, 0.981494, 1, 0, 0.556265,-99) , 
1, -0.353667, 1, 0, 0.589679,-99) , 
NN(
NN(
0, 
0, 
-1, 0.653757, 1, -1, 0.401972,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.346397, 1, 0, 0.342447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, -0.467965, 1, 0, 0.187527,-99) , 
3, 1.80427, 0, 0, 0.317064,-99) , 
3, 1.82145, 0, 0, 0.566778,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.560901);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.403836, 1, 1, 0.971096,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.903652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, -1.32185, 1, 0, 0.229341,-99) , 
3, 1.81451, 0, 0, 0.878585,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.745315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.148012,-99) , 
3, 1.91564, 1, 0, 0.580278,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0619511,-99) , 
2, 2.5783, 1, 0, 0.201128,-99) , 
1, -1.69729, 1, 0, 0.484017,-99) , 
1, -1.40634, 0, 0, 0.617056,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.83604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473578,-99) , 
1, -0.46557, 0, 0, 0.57662,-99) , 
NN(
0, 
0, 
-1, 1.01845, 1, -1, 0.438171,-99) , 
1, -0.320694, 1, 0, 0.468777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.833436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0591747,-99) , 
3, 1.91754, 1, 0, 0.559587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0477851,-99) , 
3, 1.92435, 0, 0, 0.105634,-99) , 
0, 0.408123, 1, 0, 0.343911,-99) , 
1, -0.706392, 0, 0, 0.455258,-99) , 
1, -1.10574, 1, 0, 0.473402,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.42177);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.63119, 0, 1, 0.595953,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.118421,-99) , 
2, 3.53388, 1, 0, 0.502513,-99) , 
3, 1.84197, 0, 0, 0.58081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78193, 0, 0, 0.578079,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.945659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374122,-99) , 
3, 1.84214, 1, 0, 0.769777,-99) , 
NN(
0, 
0, 
-1, 0.00538216, 1, -1, 0.0148825,-99) , 
0, 0.982326, 1, 0, 0.616891,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.986148,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0822951,-99) , 
3, 1.90615, 0, 0, 0.211638,-99) , 
0, -0.182369, 1, 0, 0.257219,-99) , 
0, 0.726755, 0, 0, 0.40454,-99) , 
2, 0.801782, 0, 0, 0.570131,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.266184);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.457075, 0, 1, 0.993422,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.0262359, 0, 1, 0.99859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270294,-99) , 
0, 0.707107, 1, 0, 0.729534,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.73389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471342,-99) , 
0, 0.796316, 1, 0, 0.530042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.997515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447882,-99) , 
1, 2.81803, 0, 0, 0.451945,-99) , 
0, 0.68039, 0, 0, 0.468123,-99) , 
2, 4.27377, 0, 0, 0.472066,-99) , 
0, -0.396603, 1, 0, 0.474079,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.350487);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452732,-99) , 
3, 1.83843, 0, 0, 0.553891,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.864581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380492,-99) , 
0, -0.0228951, 1, 0, 0.441861,-99) , 
1, -0.762258, 0, 0, 0.534164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.530637,-99) , 
3, 1.95392, 0, 0, 0.532262,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.559254);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.57603, 0, 1, 0.603203,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.748647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430705,-99) , 
0, 1.06736, 0, 0, 0.53267,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0518874,-99) , 
1, 0.395345, 0, 0, 0.135386,-99) , 
0, 0.511265, 0, 0, 0.464726,-99) , 
0, 0.462488, 1, 0, 0.554924,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.91772, 1, 1, 0.770981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0207039,-99) , 
3, 1.99229, 0, 0, 0.068682,-99) , 
2, 1.54293, 0, 0, 0.67721,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309824,-99) , 
2, 2.9461, 1, 0, 0.506947,-99) , 
NN(
0, 
0, 
-1, -0.0313111, 1, -1, 0.367938,-99) , 
1, 0.193071, 0, 0, 0.43376,-99) , 
1, -0.988006, 1, 0, 0.458808,-99) , 
3, 1.8656, 1, 0, 0.494013,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.503675);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.97769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244912,-99) , 
0, 0.754642, 0, 0, 0.916922,-99) , 
NN(
0, 
0, 
-1, 3.75427, 0, 1, 0.56624,-99) , 
0, 0.742947, 0, 0, 0.596125,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478775,-99) , 
3, 1.92433, 0, 0, 0.52157,-99) , 
NN(
0, 
0, 
-1, 1.30207, 1, -1, 0.00234075,-99) , 
0, 0.828748, 0, 0, 0.458268,-99) , 
0, 0.795762, 1, 0, 0.550041,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347842,-99) , 
3, 1.83334, 0, 0, 0.876706,-99) , 
NN(
0, 
0, 
-1, -0.17784, 0, -1, 0.455298,-99) , 
2, 3.07707, 0, 0, 0.489557,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.248828,-99) , 
0, -0.00568646, 0, 0, 0.420016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.137369,-99) , 
2, 2.95332, 0, 0, 0.179521,-99) , 
0, 0.229668, 1, 0, 0.305392,-99) , 
1, 0.936966, 1, 0, 0.435729,-99) , 
0, 0.449693, 0, 0, 0.485571,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.637821);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.795396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35332,-99) , 
3, 1.91341, 1, 0, 0.72602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297695,-99) , 
2, 3.02258, 0, 0, 0.398093,-99) , 
0, -0.178352, 0, 0, 0.652128,-99) , 
NN(
NN(
0, 
0, 
-1, 0.292016, 1, 1, 0.542314,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.970833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000855213,-99) , 
0, 0.198057, 0, 0, 0.279232,-99) , 
0, 0.231095, 0, 0, 0.51934,-99) , 
0, 0.167595, 1, 0, 0.552532,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.826912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.88788, 0, 0, 0.652262,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344259,-99) , 
0, 0.458956, 0, 0, 0.446652,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0155347,-99) , 
3, 1.95011, 0, 0, 0.0181906,-99) , 
0, 0.614342, 1, 0, 0.389421,-99) , 
0, 0.870871, 0, 0, 0.420485,-99) , 
1, 0.985296, 1, 0, 0.520086,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.792638);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 1.87369, 0, 1, 0.888615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.114523,-99) , 
0, 0.088444, 1, 0, 0.529981,-99) , 
0, 0.121412, 0, 0, 0.624195,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394105,-99) , 
0, 0.189559, 1, 0, 0.831807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.123768,-99) , 
1, 1.11296, 0, 0, 0.175056,-99) , 
2, 2.05551, 0, 0, 0.422278,-99) , 
3, 1.91341, 1, 0, 0.586959,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.832639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0129312,-99) , 
1, 1.1327, 1, 0, 0.791585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195405,-99) , 
2, 2.50918, 1, 0, 0.529519,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382142,-99) , 
2, 2.34489, 0, 0, 0.463738,-99) , 
NN(
0, 
0, 
-1, 1.35229, 0, -1, 0.314274,-99) , 
0, 0.653063, 0, 0, 0.362096,-99) , 
0, 0.320216, 1, 0, 0.380481,-99) , 
0, 0.261627, 1, 0, 0.443453,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.593115);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.151427, 1, 1, 0.611257,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250628,-99) , 
1, 0.18886, 0, 0, 0.389289,-99) , 
3, 1.8875, 0, 0, 0.538562,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.77839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2701,-99) , 
2, 2.34145, 1, 0, 0.612859,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237867,-99) , 
2, 1.8273, 0, 0, 0.411773,-99) , 
0, 0.741097, 0, 0, 0.446143,-99) , 
3, 1.86236, 0, 0, 0.500025,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.364751, 1, 1, 0.624094,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257764,-99) , 
3, 1.91364, 0, 0, 0.325353,-99) , 
0, 0.465433, 0, 0, 0.465567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90473, 0, 0, 0.0554042,-99) , 
0, 0.848696, 1, 0, 0.393634,-99) , 
2, 3.11644, 1, 0, 0.485429,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.378278);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.89988, 1, -1, 0.431329,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.151108,-99) , 
3, 1.85217, 1, 0, 0.308276,-99) , 
0, -0.192181, 0, 0, 0.421952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.416856,-99) , 
3, 1.95392, 0, 0, 0.41906,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.462191);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.984396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240646,-99) , 
2, 0.815863, 0, 0, 0.555437,-99) , 
1, 2.66099, 0, 0, 0.563687,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278079,-99) , 
2, 1.12624, 0, 0, 0.521328,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294008,-99) , 
2, 2.91144, 1, 0, 0.395431,-99) , 
2, 2.34489, 1, 0, 0.45956,-99) , 
0, 0.494704, 1, 0, 0.517894,-99) , 
NN(
NN(
0, 
0, 
-1, 3.31645, 1, 1, 0.999581,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.907571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425997,-99) , 
3, 1.88195, 0, 0, 0.516765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.028705,-99) , 
2, 2.42954, 1, 0, 0.362136,-99) , 
2, 2.80899, 0, 0, 0.411039,-99) , 
0, -0.114504, 0, 0, 0.50812,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.465738);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.528112, 0, 1, 0.996306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0664185,-99) , 
1, 0.14111, 1, 0, 0.400895,-99) , 
2, 0.641699, 0, 0, 0.84786,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.867823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0208564,-99) , 
0, 0.913238, 1, 0, 0.767617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000167719,-99) , 
0, 0.491483, 1, 0, 0.389729,-99) , 
0, 0.693935, 0, 0, 0.516708,-99) , 
0, -0.00722063, 1, 0, 0.572547,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 4.73778, 0, 1, 0.901037,-99) , 
NN(
0, 
0, 
-1, 0.637759, 1, -1, 0.438541,-99) , 
2, 4.38347, 0, 0, 0.442608,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.815015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.115451,-99) , 
2, 1.29112, 0, 0, 0.564917,-99) , 
NN(
0, 
0, 
-1, 1.38502, 0, -1, 0.0047981,-99) , 
3, 1.88466, 0, 0, 0.150508,-99) , 
2, 1.4272, 0, 0, 0.427034,-99) , 
2, 1.18756, 1, 0, 0.447249,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.44523);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.59696, 0, 1, 0.583136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247399,-99) , 
0, 0.718255, 0, 0, 0.47755,-99) , 
0, 0.637548, 1, 0, 0.558658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78193, 0, 0, 0.555347,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.939721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451843,-99) , 
0, 0.774231, 0, 0, 0.614844,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.881105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344091,-99) , 
2, 1.506, 0, 0, 0.420434,-99) , 
2, 0.866528, 1, 0, 0.470556,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.774581,-99) , 
NN(
0, 
0, 
-1, 0.0821405, 1, -1, 0.0202622,-99) , 
1, -1.35812, 1, 0, 0.0246647,-99) , 
0, 0.908667, 1, 0, 0.456261,-99) , 
2, 1.57334, 0, 0, 0.535487,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.494536);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.528112, 0, 1, 0.996229,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0963785,-99) , 
2, 0.253597, 0, 0, 0.468413,-99) , 
2, 0.641699, 0, 0, 0.875939,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.84769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0346733,-99) , 
1, 0.147059, 1, 0, 0.74246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000416968,-99) , 
0, 0.491483, 1, 0, 0.437318,-99) , 
0, 0.693935, 0, 0, 0.532218,-99) , 
0, -0.00722063, 1, 0, 0.596403,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.93156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233956,-99) , 
0, -0.00395658, 0, 0, 0.790112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00835729,-99) , 
0, 0.93246, 1, 0, 0.720679,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424035,-99) , 
2, 1.73525, 1, 0, 0.446343,-99) , 
NN(
0, 
0, 
-1, 1.88229, 0, -1, 0.0690014,-99) , 
2, 1.302, 0, 0, 0.439187,-99) , 
2, 3.57616, 0, 0, 0.452334,-99) , 
2, 1.18756, 1, 0, 0.470646,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.474066);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 1.93894, 0, 1, 0.575604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.7941, 0, 0, 0.569968,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.896351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321548,-99) , 
2, 1.71484, 0, 0, 0.72272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0126065,-99) , 
2, 1.70514, 1, 0, 0.245423,-99) , 
0, 0.412502, 0, 0, 0.435779,-99) , 
2, 1.7992, 0, 0, 0.554752,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.995109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415733,-99) , 
2, 0.654121, 0, 0, 0.862458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.14879,-99) , 
2, 1.34276, 1, 0, 0.636113,-99) , 
NN(
NN(
0, 
0, 
-1, -1.10574, 0, -1, 0.468405,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.824863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0407069,-99) , 
2, 0.575324, 1, 0, 0.158503,-99) , 
0, 0.198926, 0, 0, 0.408404,-99) , 
0, -0.0114385, 1, 0, 0.448944,-99) , 
2, 1.57334, 0, 0, 0.535316,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.615745);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.937416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.027103,-99) , 
1, 0.0964863, 1, 0, 0.91378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.968767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0621638,-99) , 
1, -0.856394, 1, 0, 0.410671,-99) , 
0, 0.793812, 1, 0, 0.776965,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350264,-99) , 
2, 0.73128, 0, 0, 0.617235,-99) , 
NN(
0, 
0, 
-1, 0.310813, 1, -1, 0.00109563,-99) , 
0, 0.477485, 1, 0, 0.539169,-99) , 
0, 0.635008, 0, 0, 0.604976,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.953334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342543,-99) , 
1, -0.125778, 1, 0, 0.626725,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415717,-99) , 
2, 2.95021, 0, 0, 0.445008,-99) , 
0, 0.530224, 0, 0, 0.468186,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.907772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377997,-99) , 
1, -1.6166, 1, 0, 0.454007,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0347119,-99) , 
2, 2.64563, 0, 0, 0.118686,-99) , 
3, 1.91623, 1, 0, 0.379778,-99) , 
0, 0.637759, 1, 0, 0.448274,-99) , 
2, 1.18756, 1, 0, 0.466593,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.715923);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.965889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386326,-99) , 
3, 1.82761, 0, 0, 0.797124,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320386,-99) , 
2, 2.05648, 1, 0, 0.544565,-99) , 
2, 2.26056, 0, 0, 0.58586,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239561,-99) , 
0, -0.00217563, 0, 0, 0.558089,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153705,-99) , 
3, 1.99269, 0, 0, 0.154336,-99) , 
2, 2.52207, 0, 0, 0.511712,-99) , 
2, 2.47061, 1, 0, 0.555756,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.874519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224186,-99) , 
0, 0.757283, 1, 0, 0.769802,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0038848,-99) , 
1, 1.61056, 0, 0, 0.0949434,-99) , 
1, 1.20793, 1, 0, 0.54659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.993029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0187883,-99) , 
2, 3.56282, 1, 0, 0.136444,-99) , 
2, 3.63634, 0, 0, 0.282695,-99) , 
2, 3.50222, 1, 0, 0.532157,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.579166);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.033607, 0, 1, 0.739992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.130742,-99) , 
2, 1.8892, 0, 0, 0.47682,-99) , 
0, 0.166735, 1, 0, 0.538085,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0.459721, 0, -1, 0.365933,-99) , 
3, 1.94995, 0, 0, 0.374648,-99) , 
2, 1.84616, 0, 0, 0.471056,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998638,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293298,-99) , 
2, 2.90202, 1, 0, 0.49304,-99) , 
NN(
0, 
0, 
-1, -0.891009, 0, -1, 0.305441,-99) , 
0, 0.636841, 0, 0, 0.352211,-99) , 
1, 2.34054, 0, 0, 0.362665,-99) , 
2, 2.73067, 1, 0, 0.437538,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.514225);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.86534, 0, 1, 0.729319,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398005,-99) , 
1, 1.61815, 1, 0, 0.540623,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.915131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329125,-99) , 
0, 0.887891, 0, 0, 0.366918,-99) , 
2, 2.84023, 1, 0, 0.491147,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0176706,-99) , 
0, -0.169801, 0, 0, 0.671215,-99) , 
NN(
0, 
0, 
-1, -0.0818056, 1, -1, 0.400464,-99) , 
0, -0.0457909, 1, 0, 0.416551,-99) , 
1, 0.288285, 0, 0, 0.443367,-99) , 
0, -0.208537, 1, 0, 0.455972,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.468181);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.05642, 0, 1, 0.909451,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417271,-99) , 
1, -2.00359, 0, 0, 0.628577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.161519,-99) , 
2, 2.66647, 1, 0, 0.547743,-99) , 
2, 2.88848, 0, 0, 0.614919,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.559155, 1, 1, 0.868951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.979003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0237278,-99) , 
1, 1.13971, 1, 0, 0.250702,-99) , 
0, 0.0593369, 0, 0, 0.765597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.708528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459243,-99) , 
0, 0.459721, 0, 0, 0.558513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.741383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442604,-99) , 
3, 1.92297, 0, 0, 0.460764,-99) , 
2, 2.03124, 1, 0, 0.501923,-99) , 
2, 3.60975, 0, 0, 0.511496,-99) , 
1, -1.10574, 1, 0, 0.523741,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.741376);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.99615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.126207,-99) , 
3, 1.9141, 1, 0, 0.944798,-99) , 
NN(
NN(
0, 
0, 
-1, -1.04147, 1, 1, 0.62282,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.91396, 0, 0, 0.0245837,-99) , 
0, 0.105085, 1, 0, 0.602705,-99) , 
0, 0.135251, 0, 0, 0.649289,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0517395,-99) , 
0, 0.20035, 0, 0, 0.621477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.987428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399788,-99) , 
1, -1.688, 1, 0, 0.474218,-99) , 
0, 0.773758, 1, 0, 0.590699,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382348,-99) , 
1, 0.14717, 1, 0, 0.560077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.155504,-99) , 
3, 1.82383, 1, 0, 0.308615,-99) , 
1, -0.999571, 0, 0, 0.500021,-99) , 
3, 1.85953, 0, 0, 0.560465,-99) , 
0, 0.167595, 1, 0, 0.581131,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.465055);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.87203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.8733, 0, 0, 0.811666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0143808,-99) , 
2, 3.17497, 1, 0, 0.749677,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.159073,-99) , 
2, 2.79335, 1, 0, 0.606952,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.735817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00387727,-99) , 
0, 0.890236, 1, 0, 0.180955,-99) , 
1, -0.220348, 1, 0, 0.517534,-99) , 
1, 0.147059, 0, 0, 0.609397,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999333,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394329,-99) , 
2, 1.81531, 0, 0, 0.49116,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.864791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318022,-99) , 
2, 3.30914, 0, 0, 0.371654,-99) , 
0, 0.572556, 1, 0, 0.470592,-99) , 
1, 2.81803, 0, 0, 0.477473,-99) , 
0, 0.825825, 0, 0, 0.49588,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.677566);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.14362, 1, 1, 0.864067,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30607,-99) , 
3, 1.90658, 1, 0, 0.574529,-99) , 
2, 2.56261, 0, 0, 0.68485,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.847733, 1, 0, 0.480862,-99) , 
NN(
0, 
0, 
-1, 3.57631, 0, -1, 0.0216937,-99) , 
2, 2.79403, 1, 0, 0.425615,-99) , 
3, 1.88557, 0, 0, 0.556935,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.821723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449959,-99) , 
0, 0.20814, 0, 0, 0.681297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394898,-99) , 
0, -0.0121979, 1, 0, 0.442105,-99) , 
1, 0.698758, 0, 0, 0.529675,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380745,-99) , 
0, 0.227654, 1, 0, 0.420224,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.144819,-99) , 
1, -0.383099, 1, 0, 0.231396,-99) , 
0, -0.0250316, 0, 0, 0.391513,-99) , 
2, 2.03857, 1, 0, 0.444453,-99) , 
0, 0.731792, 0, 0, 0.462343,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.507474);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.163897, 1, 1, 0.755426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436487,-99) , 
2, 1.47066, 0, 0, 0.558997,-99) , 
3, 1.90615, 0, 0, 0.622318,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350414,-99) , 
3, 1.9163, 1, 0, 0.533279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.148216,-99) , 
0, -0.110985, 1, 0, 0.326114,-99) , 
0, 0.0417831, 0, 0, 0.501651,-99) , 
2, 1.78682, 1, 0, 0.534857,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.968497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00428635,-99) , 
0, 1.27288, 1, 0, 0.889461,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.801483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00271841,-99) , 
1, 0.990074, 1, 0, 0.393478,-99) , 
NN(
0, 
0, 
-1, 0.190259, 0, -1, 0.000758634,-99) , 
1, 0.494814, 0, 0, 0.0168255,-99) , 
2, 2.67061, 0, 0, 0.252966,-99) , 
0, 1.10792, 1, 0, 0.528222,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.742709);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.890034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0063691,-99) , 
1, 0.227386, 1, 0, 0.840824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.716918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000588235,-99) , 
0, 0.484333, 1, 0, 0.627219,-99) , 
0, 0.646858, 0, 0, 0.675659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539222,-99) , 
NN(
0, 
0, 
-1, 1.25234, 0, -1, 0.0199149,-99) , 
1, 1.15051, 0, 0, 0.0527423,-99) , 
0, 0.910249, 1, 0, 0.652217,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.0094594, 1, 1, 0.761128,-99) , 
NN(
0, 
0, 
-1, -0.630099, 1, -1, 0.278734,-99) , 
1, -0.353667, 0, 0, 0.560743,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.954682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41846,-99) , 
3, 1.89246, 0, 0, 0.510598,-99) , 
NN(
0, 
0, 
-1, 0.19563, 0, -1, 0.361426,-99) , 
1, -0.277359, 1, 0, 0.411031,-99) , 
3, 1.91341, 0, 0, 0.439254,-99) , 
2, 1.18756, 1, 0, 0.467157,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.600115);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.992274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.83054, 0, 0, 0.959447,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.86126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0173413,-99) , 
1, 2.5041, 0, 0, 0.616452,-99) , 
1, 2.22212, 1, 0, 0.846208,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498799,-99) , 
2, 2.69883, 1, 0, 0.732191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00192793,-99) , 
2, 2.35747, 0, 0, 0.513871,-99) , 
2, 1.98967, 1, 0, 0.693436,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.16283, 1, 1, 0.600196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.7941, 0, 0, 0.592937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425703,-99) , 
3, 1.82287, 1, 0, 0.491726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.735786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00135532,-99) , 
2, 1.52404, 1, 0, 0.21298,-99) , 
1, 1.24118, 1, 0, 0.46097,-99) , 
2, 1.95911, 0, 0, 0.54976,-99) , 
1, 1.68231, 0, 0, 0.564572,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.755669);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.986009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.83054, 0, 0, 0.953589,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.77306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0311572,-99) , 
1, 2.5041, 0, 0, 0.571901,-99) , 
1, 2.22212, 1, 0, 0.821116,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.844645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0470705,-99) , 
0, 0.0820445, 0, 0, 0.780334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00350776,-99) , 
2, 2.35747, 0, 0, 0.578788,-99) , 
2, 1.98967, 1, 0, 0.702978,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.816984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318154,-99) , 
2, 2.5859, 1, 0, 0.717208,-99) , 
NN(
0, 
0, 
-1, 1.55798, 0, -1, 0.444108,-99) , 
3, 1.88835, 0, 0, 0.548204,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.982524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409325,-99) , 
0, 0.335845, 1, 0, 0.488098,-99) , 
NN(
0, 
0, 
-1, 0.170589, 1, -1, 0.282909,-99) , 
0, 0.276749, 0, 0, 0.413071,-99) , 
1, -0.0447773, 1, 0, 0.478691,-99) , 
1, 1.68231, 0, 0, 0.498176,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.737239);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.39957, 0, 1, 0.75526,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.918361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257275,-99) , 
2, 3.69599, 0, 0, 0.514256,-99) , 
2, 3.56215, 1, 0, 0.70817,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.931579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255801,-99) , 
2, 3.55949, 1, 0, 0.709005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241347,-99) , 
2, 2.87607, 0, 0, 0.468297,-99) , 
0, 0.268243, 0, 0, 0.653742,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.33025, 1, 1, 0.894932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.75825, 0, 0, 0.881523,-99) , 
NN(
NN(
0, 
0, 
-1, 0.379567, 1, 1, 0.598007,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0707337,-99) , 
0, 0.174822, 1, 0, 0.465806,-99) , 
0, 0.195426, 0, 0, 0.561575,-99) , 
0, -0.208537, 1, 0, 0.57669,-99) , 
2, 2.73067, 0, 0, 0.603949,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.547489);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.996019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48631,-99) , 
0, 0.757283, 1, 0, 0.89148,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.029762,-99) , 
1, 1.61056, 0, 0, 0.273821,-99) , 
1, 1.20793, 1, 0, 0.795474,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.893375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0272724,-99) , 
0, 0.58601, 1, 0, 0.761665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429481,-99) , 
3, 1.88009, 0, 0, 0.528649,-99) , 
1, 1.12899, 0, 0, 0.562394,-99) , 
2, 3.72455, 0, 0, 0.579427,-99) , 
NN(
NN(
0, 
0, 
-1, 1.86534, 0, 1, 0.792149,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, -1.80275, 0, -1, 0.391166,-99) , 
3, 1.94995, 0, 0, 0.396305,-99) , 
0, -0.208537, 1, 0, 0.411036,-99) , 
2, 2.73067, 0, 0, 0.465792,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.711983);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.90016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432101,-99) , 
2, 3.03257, 1, 0, 0.783212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0174226,-99) , 
0, 0.323378, 1, 0, 0.598405,-99) , 
0, 0.370258, 0, 0, 0.694161,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78927, 0, 0, 0.602487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273373,-99) , 
1, -0.118499, 1, 0, 0.468314,-99) , 
3, 1.86351, 1, 0, 0.528346,-99) , 
1, 0.183874, 0, 0, 0.571918,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 3.77071, 1, 1, 0.997787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264857,-99) , 
2, 4.12932, 1, 0, 0.857486,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.819301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424472,-99) , 
3, 1.89609, 0, 0, 0.499665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.869343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.140925,-99) , 
3, 1.88294, 1, 0, 0.28292,-99) , 
2, 2.83434, 1, 0, 0.434895,-99) , 
2, 3.48268, 0, 0, 0.461956,-99) , 
1, 0.985296, 1, 0, 0.546354,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.619431);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.528911, 0, 1, 0.673836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 1.8571e-05,-99) , 
0, 0.651989, 0, 0, 0.379263,-99) , 
0, 0.607895, 1, 0, 0.618753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998563,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.734196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0630921,-99) , 
2, 1.70977, 1, 0, 0.264475,-99) , 
2, 2.91199, 0, 0, 0.366489,-99) , 
0, -0.192128, 0, 0, 0.592936,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.353753, 1, 1, 0.951603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.148314,-99) , 
0, -0.437201, 0, 0, 0.946924,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416007,-99) , 
3, 1.88196, 0, 0, 0.504817,-99) , 
NN(
0, 
0, 
-1, -1.90874, 0, -1, 0.382945,-99) , 
2, 2.73067, 0, 0, 0.417725,-99) , 
0, -0.302605, 1, 0, 0.422917,-99) , 
1, 0.288285, 0, 0, 0.48283,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.424492);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.994747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332067,-99) , 
0, 0.757283, 1, 0, 0.832656,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00922929,-99) , 
2, 3.56418, 1, 0, 0.539967,-99) , 
2, 3.73291, 0, 0, 0.547249,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.9182, 0, 0, 0.111259,-99) , 
2, 0.416005, 0, 0, 0.543757,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.824713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46268,-99) , 
0, 0.00215002, 0, 0, 0.611631,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.957589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370456,-99) , 
2, 3.29735, 0, 0, 0.405976,-99) , 
0, 0.243691, 1, 0, 0.471787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.81051, 0, 0, 0.445428,-99) , 
1, 0.985296, 1, 0, 0.522011,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.349179);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.889513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00944436,-99) , 
0, 0.468202, 1, 0, 0.0852959,-99) , 
3, 1.90603, 1, 0, 0.815224,-99) , 
NN(
NN(
0, 
0, 
-1, 0.332352, 1, 1, 0.850826,-99) , 
NN(
0, 
0, 
-1, 1.83695, 0, -1, 0.315561,-99) , 
1, 2.71518, 0, 0, 0.407125,-99) , 
1, 1.95066, 1, 0, 0.595712,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.780356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443936,-99) , 
2, 3.58869, 0, 0, 0.452731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.448107,-99) , 
3, 1.95392, 0, 0, 0.450857,-99) , 
1, 1.68231, 0, 0, 0.462088,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.347396);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.83864, 0, 1, 0.592591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.178463,-99) , 
3, 1.85891, 0, 0, 0.511843,-99) , 
3, 1.85373, 1, 0, 0.540442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.535924,-99) , 
3, 1.95392, 0, 0, 0.53784,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.469642);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.997665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00241432,-99) , 
2, 1.39929, 0, 0, 0.921019,-99) , 
NN(
0, 
0, 
-1, 1.82145, 0, -1, 0.473575,-99) , 
0, 0.532209, 0, 0, 0.499294,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000641113,-99) , 
2, 1.9474, 0, 0, 0.399015,-99) , 
NN(
0, 
0, 
-1, 1.93136, 0, -1, 0.0013656,-99) , 
2, 2.34301, 1, 0, 0.180046,-99) , 
0, 0.583954, 1, 0, 0.480817,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.918492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00922987,-99) , 
1, 0.0964863, 1, 0, 0.877633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.949787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0221573,-99) , 
1, -0.856394, 1, 0, 0.27165,-99) , 
0, 0.798527, 1, 0, 0.630042,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.853807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376698,-99) , 
0, 1.08122, 0, 0, 0.462356,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.105367,-99) , 
2, 3.10562, 0, 0, 0.211527,-99) , 
1, -0.771632, 0, 0, 0.373873,-99) , 
2, 1.18756, 1, 0, 0.404745,-99) , 
0, 0.637759, 1, 0, 0.462836,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.781173);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 1.49249, 0, 1, 0.892545,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189638,-99) , 
0, 0.502065, 0, 0, 0.537192,-99) , 
2, 2.51369, 1, 0, 0.700151,-99) , 
NN(
NN(
0, 
0, 
-1, 2.57603, 0, 1, 0.639311,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.187052,-99) , 
0, 0.400131, 1, 0, 0.483397,-99) , 
3, 1.86958, 1, 0, 0.565905,-99) , 
0, 0.444987, 0, 0, 0.595431,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.955621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0864452,-99) , 
1, 0.262107, 0, 0, 0.814073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.829671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279268,-99) , 
0, 0.593193, 1, 0, 0.445947,-99) , 
1, 0.432974, 1, 0, 0.567187,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.86411, 1, -1, 0.351888,-99) , 
3, 1.92937, 0, 0, 0.384828,-99) , 
1, 0.157103, 0, 0, 0.452198,-99) , 
0, 0.543726, 1, 0, 0.555785,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.683309);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.876131, 0, 1, 0.678665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451776,-99) , 
1, -0.676916, 0, 0, 0.568398,-99) , 
0, 0.549943, 1, 0, 0.603952,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.997884,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.92365, 0, 0, 0.0396405,-99) , 
0, 0.908336, 0, 0, 0.321872,-99) , 
1, 2.04109, 1, 0, 0.590733,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.398927, 0, 1, 0.999577,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.144093,-99) , 
2, 2.91609, 0, 0, 0.385069,-99) , 
0, 0.361378, 0, 0, 0.522444,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.785004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377257,-99) , 
0, -0.0881475, 1, 0, 0.408986,-99) , 
NN(
0, 
0, 
-1, -0.223119, 1, -1, 0.200648,-99) , 
0, -0.17784, 0, 0, 0.38571,-99) , 
2, 2.768, 0, 0, 0.408697,-99) , 
0, 0.449693, 0, 0, 0.481809,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.508159);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 2.97552, 0, 1, 0.963308,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.724442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.109825,-99) , 
2, 2.47335, 1, 0, 0.572335,-99) , 
2, 2.78553, 0, 0, 0.685171,-99) , 
NN(
0, 
0, 
-1, 0.171658, 1, -1, 0.0204506,-99) , 
3, 1.80571, 0, 0, 0.622406,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49365,-99) , 
3, 1.86236, 1, 0, 0.5344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000868695,-99) , 
2, 2.31281, 1, 0, 0.391933,-99) , 
0, -0.114504, 0, 0, 0.519692,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.992943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316956,-99) , 
0, 0.0581217, 0, 0, 0.581086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271883,-99) , 
2, 3.63229, 0, 0, 0.332555,-99) , 
0, 0.453808, 1, 0, 0.396247,-99) , 
2, 2.8753, 1, 0, 0.495394,-99) , 
1, -1.10574, 1, 0, 0.512315,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.838164);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41216,-99) , 
1, 1.54935, 1, 0, 0.621459,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.91633, 0, 0, 0.126252,-99) , 
2, 0.585461, 0, 0, 0.610504,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.23522,-99) , 
0, 0.465433, 0, 0, 0.465224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0692346,-99) , 
0, 0.848696, 1, 0, 0.346337,-99) , 
2, 3.12577, 1, 0, 0.579412,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278851,-99) , 
3, 1.81229, 0, 0, 0.663802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0605333,-99) , 
1, 1.31866, 1, 0, 0.616081,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0884243,-99) , 
2, 1.6471, 0, 0, 0.490293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.175668,-99) , 
1, 1.48183, 0, 0, 0.256658,-99) , 
1, 0.0636401, 1, 0, 0.375061,-99) , 
2, 2.67061, 0, 0, 0.454746,-99) , 
3, 1.8656, 0, 0, 0.523586,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.474142);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296289,-99) , 
3, 1.85419, 0, 0, 0.540134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40374,-99) , 
2, 3.58869, 0, 0, 0.410331,-99) , 
1, 1.24291, 0, 0, 0.427728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.424404,-99) , 
3, 1.95392, 0, 0, 0.426833,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.276968);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.771945, 0, 1, 0.709299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00743386,-99) , 
2, 0.014085, 1, 0, 0.0224114,-99) , 
0, 1.002, 1, 0, 0.67072,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295443,-99) , 
2, 3.56194, 1, 0, 0.526757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0779886,-99) , 
2, 0.964373, 1, 0, 0.303368,-99) , 
2, 1.1584, 0, 0, 0.513148,-99) , 
2, 0.898818, 1, 0, 0.522338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.899383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, -0.576211, 0, 0, 0.00496145,-99) , 
2, -0.962197, 1, 0, 0.111057,-99) , 
2, -0.355549, 0, 0, 0.520102,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.204133);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456903,-99) , 
3, 1.94312, 0, 0, 0.723799,-99) , 
NN(
0, 
0, 
-1, 1.92412, 1, -1, 0.457842,-99) , 
3, 1.93835, 0, 0, 0.462647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79189, 0, 0, 0.459348,-99) , 
3, 1.95392, 0, 0, 0.461015,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.347519);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.282799, 0, 1, 0.58336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333817,-99) , 
0, 0.384658, 0, 0, 0.488907,-99) , 
0, 0.30659, 1, 0, 0.523127,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.913261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342284,-99) , 
1, 0.577033, 0, 0, 0.58468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00114304,-99) , 
0, -0.200971, 1, 0, 0.368288,-99) , 
0, -0.186396, 0, 0, 0.514896,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.969634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0103493,-99) , 
1, -0.651447, 1, 0, 0.883644,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00116221,-99) , 
1, 0.990074, 1, 0, 0.339122,-99) , 
NN(
0, 
0, 
-1, 0.190259, 0, -1, 0.000271037,-99) , 
1, 0.494814, 0, 0, 0.0152406,-99) , 
2, 2.67061, 0, 0, 0.299866,-99) , 
0, 1.10792, 1, 0, 0.510776,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.530051);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0721413,-99) , 
2, 1.33568, 0, 0, 0.9831,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198473,-99) , 
0, 0.264249, 0, 0, 0.48603,-99) , 
0, 0.248555, 1, 0, 0.51312,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.876192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412552,-99) , 
0, 0.13165, 0, 0, 0.456137,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0141929,-99) , 
3, 1.93327, 0, 0, 0.0757217,-99) , 
0, 0.162981, 1, 0, 0.405407,-99) , 
0, 0.198771, 0, 0, 0.471305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.829953,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361368,-99) , 
1, 0.0678444, 0, 0, 0.451248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.129686,-99) , 
0, 0.586662, 1, 0, 0.227287,-99) , 
0, 0.682279, 0, 0, 0.384266,-99) , 
1, -2.35488, 1, 0, 0.404289,-99) , 
0, 0.543726, 1, 0, 0.45123,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.826398);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457591,-99) , 
0, -0.157747, 0, 0, 0.644352,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.920697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.043438,-99) , 
0, -0.154582, 1, 0, 0.172708,-99) , 
3, 1.809, 0, 0, 0.603825,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.25349,-99) , 
0, 0.189559, 1, 0, 0.78166,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0658997,-99) , 
2, 1.72425, 1, 0, 0.185892,-99) , 
2, 2.05551, 0, 0, 0.36054,-99) , 
3, 1.91341, 1, 0, 0.555346,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.968545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0129672,-99) , 
2, 1.72188, 0, 0, 0.84563,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 2.28097e-05,-99) , 
1, -0.76972, 0, 0, 0.311855,-99) , 
2, 2.34423, 1, 0, 0.607908,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386905,-99) , 
0, 0.649718, 0, 0, 0.475805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318249,-99) , 
1, -2.06278, 1, 0, 0.336896,-99) , 
3, 1.90302, 0, 0, 0.380164,-99) , 
0, 1.07671, 0, 0, 0.395008,-99) , 
0, 0.261627, 1, 0, 0.442174,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.485378);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.36266, 0, 1, 0.961469,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.982257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.148766,-99) , 
0, -0.298957, 1, 0, 0.873305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.113346,-99) , 
1, 0.102309, 1, 0, 0.732613,-99) , 
1, 0.577033, 0, 0, 0.844069,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0294251,-99) , 
2, 1.34719, 0, 0, 0.936756,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417633,-99) , 
0, 0.782855, 1, 0, 0.538687,-99) , 
0, 0.256846, 1, 0, 0.547168,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367965,-99) , 
2, 2.6459, 0, 0, 0.426074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0968637,-99) , 
0, 0.17558, 1, 0, 0.375503,-99) , 
0, 0.195305, 0, 0, 0.50746,-99) , 
0, -0.208537, 1, 0, 0.522734,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.360815);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.997779,-99) , 
NN(
NN(
0, 
0, 
-1, 1.18905, 1, 1, 0.920919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.762598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0094176,-99) , 
0, -0.375081, 0, 0, 0.557903,-99) , 
1, 0.577033, 0, 0, 0.75684,-99) , 
2, 1.13895, 1, 0, 0.83292,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.06377, 0, 1, 0.596212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.106007,-99) , 
3, 1.92177, 0, 0, 0.229115,-99) , 
2, 3.11644, 1, 0, 0.560925,-99) , 
NN(
NN(
0, 
0, 
-1, 0.666004, 0, -1, 0.461998,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.948586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211541,-99) , 
1, 2.64155, 0, 0, 0.297172,-99) , 
1, 1.54935, 1, 0, 0.445939,-99) , 
0, 0.678586, 0, 0, 0.468664,-99) , 
0, -0.208537, 1, 0, 0.482383,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.534023);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -1.28173, 0, 1, 0.980463,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.964536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0457169,-99) , 
0, -0.0252086, 1, 0, 0.75738,-99) , 
1, -1.76282, 0, 0, 0.884336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80409, 0, 0, 0.701962,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.773634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.13055,-99) , 
2, 1.74874, 1, 0, 0.39359,-99) , 
3, 1.87874, 1, 0, 0.589496,-99) , 
1, -1.04147, 1, 0, 0.648538,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477399,-99) , 
1, -0.196002, 0, 0, 0.548657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253247,-99) , 
3, 1.85218, 0, 0, 0.436314,-99) , 
1, 0.789738, 1, 0, 0.523428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.88226, 0, -1, 0.196866,-99) , 
2, 3.10685, 0, 0, 0.300614,-99) , 
1, -1.80275, 0, 0, 0.510373,-99) , 
0, 0.0735617, 1, 0, 0.533852,-99)    );
   return;
};
 
// Clean up
inline void ReadD4::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadD4::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
