// Class: ReadADAC3D2T50
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::ADAC3D2T50
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : jlang
Date           : Tue Dec  8 16:30:03 2015
Host           : Linux ekpams2 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 21:44:51 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /usr/users/jlang/BDT/Test/BDT_Training
Training events: 1332
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "10" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "3" [Number of steps during node cut optimisation]
MaxDepth: "2" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1332" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
v0                            v0                            v0                            v0                                                              'F'    [-0.490635514259,1.48405468464]
v1                            v1                            v1                            v1                                                              'F'    [-7.37883806229,7.25839614868]
v2                            v2                            v2                            v2                                                              'F'    [-1.8986569643,6.2026591301]
v3                            v3                            v3                            v3                                                              'F'    [1.46819293499,2.39548110962]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new ADAC3D2T50Node
   
#ifndef ADAC3D2T50Node__def
#define ADAC3D2T50Node__def
   
class ADAC3D2T50Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   ADAC3D2T50Node ( ADAC3D2T50Node* left,ADAC3D2T50Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~ADAC3D2T50Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   ADAC3D2T50Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   ADAC3D2T50Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   ADAC3D2T50Node*   fLeft;     // pointer to the left daughter node
   ADAC3D2T50Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   ADAC3D2T50Node::~ADAC3D2T50Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool ADAC3D2T50Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool ADAC3D2T50Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadADAC3D2T50 : public IClassifierReader {

 public:

   // constructor
   ReadADAC3D2T50( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadADAC3D2T50" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "v0", "v1", "v2", "v3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.490635514259338;
      fVmax[0] = 1.48405468463898;
      fVmin[1] = -7.37883806228638;
      fVmax[1] = 7.25839614868164;
      fVmin[2] = -1.89865696430206;
      fVmax[2] = 6.20265913009644;
      fVmin[3] = 1.46819293498993;
      fVmax[3] = 2.39548110961914;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadADAC3D2T50() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<ADAC3D2T50Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadADAC3D2T50::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      ADAC3D2T50Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(ADAC3D2T50Node*)current->GetRight();
         else current=(ADAC3D2T50Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadADAC3D2T50::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.97716269255942);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04777, 0, 1, 0.994118,-99) , 
NN(
0, 
0, 
-1, 1.81546, 0, -1, 0.193431,-99) , 
3, 1.93184, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.72236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.49671, 1, 1, 0.823549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.707407,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.17376);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.837368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429575,-99) , 
2, 2.31504, 0, 0, 0.6098,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.76852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.144084,-99) , 
3, 1.92943, 0, 0, 0.202127,-99) , 
0, 0.49671, 1, 0, 0.416891,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.831337);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.675278,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211523,-99) , 
2, 2.152, 0, 0, 0.368723,-99) , 
0, 0.49671, 1, 0, 0.548031,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.851097);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0549845,-99) , 
3, 1.81576, 0, 0, 0.408255,-99) , 
3, 2.16366, 0, 0, 0.435612,-99)    );
  // itree = 5
  fBoostWeights.push_back(1.04693);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278375,-99) , 
3, 1.98954, 0, 0, 0.303513,-99) , 
3, 2.16366, 0, 0, 0.326486,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.361529);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.27313, 1, 1, 0.74065,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0889842,-99) , 
0, 1.11385, 1, 0, 0.499898,-99) , 
0, 0.00303704, 1, 0, 0.545036,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.464059);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.557439, 1, 1, 0.665481,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.823091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405493,-99) , 
2, 4.17733, 0, 0, 0.420824,-99) , 
0, 0.00303704, 1, 0, 0.464132,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.231529);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.546253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.532562,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.317186);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239944,-99) , 
3, 1.81576, 0, 0, 0.467269,-99) , 
3, 2.16366, 0, 0, 0.477527,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.430454);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407741,-99) , 
3, 1.98954, 0, 0, 0.417991,-99) , 
3, 2.16366, 0, 0, 0.427675,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.293181);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.155042,-99) , 
2, 0.476791, 0, 0, 0.536365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.527771,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.305736);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484954,-99) , 
3, 1.90901, 0, 0, 0.534607,-99) , 
NN(
0, 
0, 
-1, 0.995168, 1, -1, 0.411206,-99) , 
1, -0.060221, 1, 0, 0.462651,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.146503);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.530863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.524416,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.142155);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476023,-99) , 
3, 1.98954, 0, 0, 0.482421,-99) , 
3, 2.16366, 0, 0, 0.488683,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.395563);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346632,-99) , 
0, 0.995168, 1, 0, 0.543049,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241296,-99) , 
3, 2.04777, 0, 0, 0.364501,-99) , 
3, 1.93184, 1, 0, 0.522561,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.250233);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446915,-99) , 
3, 1.98954, 0, 0, 0.453067,-99) , 
3, 2.16366, 0, 0, 0.458237,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.198369);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.214587,-99) , 
2, 0.476791, 0, 0, 0.523938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.518204,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.159629);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470956,-99) , 
3, 2.04801, 0, 0, 0.477865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.473106,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0848462);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.516741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.511975,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0813913);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489621,-99) , 
3, 2.04801, 0, 0, 0.495536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.491151,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0782069);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.515421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.511039,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0752625);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490416,-99) , 
3, 2.04801, 0, 0, 0.495875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.491817,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0725318);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.514294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.510238,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0699924);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491099,-99) , 
3, 2.04801, 0, 0, 0.496165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.492389,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0676248);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.513321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.509546,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0654123);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491691,-99) , 
3, 2.04801, 0, 0, 0.496418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.492887,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.205502);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459197,-99) , 
2, 2.38541, 1, 0, 0.512472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.508942,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0804855);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.68515, 0, 1, 0.509397,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.822101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0228183,-99) , 
1, 1.42051, 0, 0, 0.250732,-99) , 
2, 0.126672, 0, 0, 0.502855,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.205925);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0296251,-99) , 
2, 0.40284, 0, 0, 0.528818,-99) , 
NN(
0, 
0, 
-1, 0.995168, 1, -1, 0.448891,-99) , 
1, -0.060221, 1, 0, 0.483445,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.107278);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.784146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484898,-99) , 
2, 4.29404, 0, 0, 0.494524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.49137,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0902728);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.519645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.516498,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0583753);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492597,-99) , 
3, 2.04801, 0, 0, 0.497086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.494207,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0567194);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.511426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.508547,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0551548);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493011,-99) , 
3, 2.04801, 0, 0, 0.497248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.494526,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0536742);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.29404, 0, 1, 0.510809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.508088,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0522711);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493381,-99) , 
3, 2.04801, 0, 0, 0.497393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.494812,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0509395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.29404, 0, 1, 0.510256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.507676,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0805826);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.749479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489563,-99) , 
2, 4.29404, 0, 0, 0.497523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.49507,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.132413);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27065,-99) , 
2, 0.476791, 0, 0, 0.516448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.514,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.10906);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372494,-99) , 
3, 1.81576, 0, 0, 0.480897,-99) , 
3, 2.16366, 0, 0, 0.483249,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.18319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459372,-99) , 
3, 1.98954, 0, 0, 0.462998,-99) , 
3, 2.16366, 0, 0, 0.465305,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.05569);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.04801, 0, 1, 0.512034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.510056,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.054181);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491264,-99) , 
3, 1.98954, 0, 0, 0.494305,-99) , 
3, 2.16366, 0, 0, 0.496242,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0527516);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.29404, 0, 1, 0.511397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.509526,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0513957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491718,-99) , 
3, 1.98954, 0, 0, 0.494599,-99) , 
3, 2.16366, 0, 0, 0.496435,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0501077);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.29404, 0, 1, 0.510824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.70001, 0, 0, 0.509048,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.290283);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42531,-99) , 
2, 1.77287, 0, 0, 0.505965,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326062,-99) , 
1, -0.126828, 1, 0, 0.401489,-99) , 
3, 1.93184, 1, 0, 0.496609,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.2982);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454624,-99) , 
2, 1.13825, 0, 0, 0.529212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419576,-99) , 
3, 1.94445, 0, 0, 0.436736,-99) , 
2, 2.152, 1, 0, 0.481738,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.262254);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00986829,-99) , 
0, 1.23741, 1, 0, 0.538934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454519,-99) , 
0, -0.243812, 1, 0, 0.475537,-99) , 
0, 0.49671, 0, 0, 0.501283,-99)    );
   return;
};
 
// Clean up
inline void ReadADAC3D2T50::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadADAC3D2T50::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
