// Class: ReadCUTS_10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::CUTS_10
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : jlang
Date           : Tue Dec  8 16:22:08 2015
Host           : Linux ekpams2 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 21:44:51 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /usr/users/jlang/BDT/Test/BDT_Training
Training events: 1332
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "10" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "10" [Number of steps during node cut optimisation]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1332" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
v0                            v0                            v0                            v0                                                              'F'    [-0.490635514259,1.48405468464]
v1                            v1                            v1                            v1                                                              'F'    [-7.37883806229,7.25839614868]
v2                            v2                            v2                            v2                                                              'F'    [-1.8986569643,6.2026591301]
v3                            v3                            v3                            v3                                                              'F'    [1.46819293499,2.39548110962]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new CUTS_10Node
   
#ifndef CUTS_10Node__def
#define CUTS_10Node__def
   
class CUTS_10Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   CUTS_10Node ( CUTS_10Node* left,CUTS_10Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~CUTS_10Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   CUTS_10Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   CUTS_10Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   CUTS_10Node*   fLeft;     // pointer to the left daughter node
   CUTS_10Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   CUTS_10Node::~CUTS_10Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool CUTS_10Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool CUTS_10Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCUTS_10 : public IClassifierReader {

 public:

   // constructor
   ReadCUTS_10( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCUTS_10" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "v0", "v1", "v2", "v3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.490635514259338;
      fVmax[0] = 1.48405468463898;
      fVmin[1] = -7.37883806228638;
      fVmax[1] = 7.25839614868164;
      fVmin[2] = -1.89865696430206;
      fVmax[2] = 6.20265913009644;
      fVmin[3] = 1.46819293498993;
      fVmax[3] = 2.39548110961914;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCUTS_10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<CUTS_10Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadCUTS_10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      CUTS_10Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(CUTS_10Node*)current->GetRight();
         else current=(CUTS_10Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadCUTS_10::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(2.53304872579476);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.97764, 0, 1, 0.995992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.770115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393939,-99) , 
0, 0.552882, 1, 0, 0.666667,-99) , 
3, 1.93572, 0, 0, 0.932149,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.141414,-99) , 
0, 0.55252, 1, 0, 0.394366,-99) , 
NN(
0, 
0, 
-1, 1.78033, 0, -1, 0.01,-99) , 
3, 1.81232, 0, 0, 0.124825,-99) , 
3, 1.88969, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.47591);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.7987, 0, 0, 0.520296,-99) , 
NN(
0, 
0, 
-1, 1.54271, 0, -1, 0.16405,-99) , 
2, 2.30776, 0, 0, 0.289443,-99) , 
3, 1.97399, 0, 0, 0.420153,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.19952);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302088,-99) , 
0, 0.594969, 0, 0, 0.419829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78983, 0, 0, 0.366344,-99) , 
3, 1.97399, 0, 0, 0.437948,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.835328);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338681,-99) , 
2, 2.51996, 1, 0, 0.52737,-99) , 
3, 1.96638, 0, 0, 0.568899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.535362,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.820296);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230609,-99) , 
2, 1.07481, 0, 0, 0.606118,-99) , 
3, 1.98169, 0, 0, 0.658396,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.941056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420538,-99) , 
2, 3.98813, 0, 0, 0.470818,-99) , 
NN(
0, 
0, 
-1, -0.120178, 1, -1, 0.135491,-99) , 
2, 1.43909, 0, 0, 0.377533,-99) , 
3, 1.88969, 0, 0, 0.48514,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.401322);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.068297,-99) , 
2, 0.544063, 0, 0, 0.529209,-99) , 
3, 1.96638, 0, 0, 0.550325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.533401,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.644707);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.771919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425178,-99) , 
0, 0.497762, 0, 0, 0.491729,-99) , 
NN(
0, 
0, 
-1, 0.839355, 1, -1, 0.283021,-99) , 
0, 0.59517, 1, 0, 0.428103,-99) , 
3, 1.97399, 0, 0, 0.446375,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.393318);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.929992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.837676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242163,-99) , 
0, -0.224553, 1, 0, 0.666813,-99) , 
0, -0.165038, 0, 0, 0.773529,-99) , 
NN(
NN(
0, 
0, 
-1, 4.79762, 0, 1, 0.53906,-99) , 
NN(
0, 
0, 
-1, 1.86735, 0, -1, 0.01152,-99) , 
0, 1.19065, 1, 0, 0.522035,-99) , 
0, -0.131601, 1, 0, 0.557576,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.575866);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.899641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.776905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321358,-99) , 
0, -0.224553, 1, 0, 0.642909,-99) , 
0, -0.165038, 0, 0, 0.743789,-99) , 
NN(
NN(
0, 
0, 
-1, 0.34252, 1, 1, 0.99573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402441,-99) , 
3, 1.97399, 0, 0, 0.413981,-99) , 
2, 4.72969, 0, 0, 0.429759,-99) , 
0, -0.131601, 1, 0, 0.469403,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.437611);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95028, 0, 1, 0.594481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78248, 0, 0, 0.586997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.575116,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.228545);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.993003,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.78983, 0, -1, 0.456847,-99) , 
3, 1.97399, 0, 0, 0.46446,-99) , 
2, 4.72969, 0, 0, 0.473199,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.216357);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.750609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492929,-99) , 
3, 1.81017, 1, 0, 0.525986,-99) , 
3, 1.96638, 0, 0, 0.535001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.526987,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.363934);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95028, 0, 1, 0.580025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78248, 0, 0, 0.574021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.566259,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.253453);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.420684, 1, 1, 0.93158,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353768,-99) , 
2, 1.47767, 0, 0, 0.483575,-99) , 
2, 4.59613, 0, 0, 0.490852,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.721706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.95824, 0, 0, 0.00910585,-99) , 
1, 1.2934, 0, 0, 0.161597,-99) , 
2, 0.310793, 0, 0, 0.479887,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.535492);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.989563,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374298,-99) , 
2, 1.54775, 0, 0, 0.500014,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307237,-99) , 
1, -0.666454, 1, 0, 0.363825,-99) , 
2, 2.31546, 1, 0, 0.437853,-99) , 
2, 4.72969, 0, 0, 0.443893,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.318816);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486729,-99) , 
0, 0.379492, 1, 0, 0.621577,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444671,-99) , 
3, 1.97399, 0, 0, 0.44992,-99) , 
2, 3.39258, 0, 0, 0.470012,-99) , 
NN(
0, 
0, 
-1, 1.15995, 1, -1, 0.145284,-99) , 
0, 1.12502, 1, 0, 0.458016,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.233689);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.96792, 0, 1, 0.545028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.540023,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507136,-99) , 
NN(
0, 
0, 
-1, 1.19056, 1, -1, 0.028672,-99) , 
0, 1.15995, 1, 0, 0.1895,-99) , 
0, 1.12502, 1, 0, 0.528231,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.284944);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.79843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411423,-99) , 
1, 0.253798, 1, 0, 0.608222,-99) , 
NN(
0, 
0, 
-1, -2.05621, 0, -1, 0.460584,-99) , 
0, -0.0512354, 1, 0, 0.482736,-99) , 
NN(
0, 
0, 
-1, 1.15995, 1, -1, 0.185491,-99) , 
0, 1.12502, 1, 0, 0.473343,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.360209);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.590005, 1, 1, 0.621933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.797895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468984,-99) , 
3, 1.80539, 1, 0, 0.499193,-99) , 
0, 0.534631, 0, 0, 0.543469,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.757661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0961103,-99) , 
1, -0.408525, 1, 0, 0.483661,-99) , 
NN(
0, 
0, 
-1, 1.86735, 0, -1, 0.0179089,-99) , 
0, 1.19236, 1, 0, 0.232431,-99) , 
0, 1.12502, 1, 0, 0.534332,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.640218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.886, 0, 1, 0.912039,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.173084,-99) , 
2, 0.725004, 0, 0, 0.59156,-99) , 
1, 2.41436, 0, 0, 0.605645,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397661,-99) , 
0, 0.832011, 1, 0, 0.538784,-99) , 
NN(
0, 
0, 
-1, 1.89037, 0, -1, 0.117824,-99) , 
1, 1.01346, 1, 0, 0.431485,-99) , 
0, 0.586468, 1, 0, 0.551092,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.384812);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499514,-99) , 
0, 0.384871, 1, 0, 0.663605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80263, 0, 0, 0.621322,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.877584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419731,-99) , 
3, 1.90652, 0, 0, 0.793529,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428119,-99) , 
3, 1.97715, 0, 0, 0.432886,-99) , 
1, 2.41436, 0, 0, 0.441518,-99) , 
2, 1.04728, 1, 0, 0.465111,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.217679);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.96638, 0, 1, 0.549895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.544629,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.176728);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476951,-99) , 
3, 1.94365, 0, 0, 0.487836,-99) , 
3, 1.96638, 0, 0, 0.495642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.49136,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.162348);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.96638, 0, 1, 0.53682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.532558,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.340722);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.63179, 1, 1, 0.607953,-99) , 
NN(
0, 
0, 
-1, 1.87058, 0, -1, 0.0320422,-99) , 
0, 1.22373, 1, 0, 0.581468,-99) , 
NN(
NN(
0, 
0, 
-1, 1.886, 0, 1, 0.791775,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433041,-99) , 
0, 0.536553, 0, 0, 0.462121,-99) , 
1, 2.41436, 0, 0, 0.470963,-99) , 
0, 0.765986, 0, 0, 0.492654,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.380714);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.860665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77461, 0, 0, 0.745849,-99) , 
NN(
0, 
0, 
-1, -0.392755, 1, 1, 0.530397,-99) , 
3, 1.80539, 1, 0, 0.549387,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80618, 0, 0, 0.525466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0166819,-99) , 
1, 1.89037, 0, 0, 0.152815,-99) , 
1, 1.01346, 1, 0, 0.439156,-99) , 
0, 0.586468, 1, 0, 0.515152,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.318624);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.99551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.78983, 0, -1, 0.426521,-99) , 
3, 1.97399, 0, 0, 0.429967,-99) , 
2, 4.72969, 0, 0, 0.43394,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0825817);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497924,-99) , 
3, 1.94365, 0, 0, 0.507936,-99) , 
3, 1.96638, 0, 0, 0.513972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.511155,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.143415);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.96638, 0, 1, 0.533336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.530529,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.17367);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.994291,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475508,-99) , 
2, 1.22665, 1, 0, 0.495702,-99) , 
NN(
0, 
0, 
-1, 0.433301, 1, -1, 0.0134714,-99) , 
2, -0.0926065, 0, 0, 0.492135,-99) , 
2, 4.72969, 0, 0, 0.495088,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.172364);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.126706, 0, 1, 0.904326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.526996,-99) , 
2, 4.59613, 0, 0, 0.530804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.95824, 0, 0, 0.0192103,-99) , 
1, 1.2934, 0, 0, 0.235442,-99) , 
2, 0.310793, 0, 0, 0.525221,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.102658);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.99195,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481806,-99) , 
3, 1.97399, 0, 0, 0.484096,-99) , 
NN(
0, 
0, 
-1, 0.433301, 1, -1, 0.0156441,-99) , 
2, -0.0926065, 0, 0, 0.48109,-99) , 
2, 4.72969, 0, 0, 0.483642,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.261542);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.854192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1.57712, 0, 0, 0.775473,-99) , 
NN(
0, 
0, 
-1, -0.392755, 1, 1, 0.508733,-99) , 
3, 1.80539, 1, 0, 0.531219,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80618, 0, 0, 0.520087,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0294329,-99) , 
1, 1.89037, 0, 0, 0.195576,-99) , 
1, 1.01346, 1, 0, 0.455941,-99) , 
0, 0.586468, 1, 0, 0.508827,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.230209);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.991087,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449153,-99) , 
3, 1.97399, 0, 0, 0.45124,-99) , 
NN(
0, 
0, 
-1, 0.433301, 1, -1, 0.0139021,-99) , 
2, -0.0926065, 0, 0, 0.448297,-99) , 
2, 4.72969, 0, 0, 0.450581,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.153701);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.791887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.597572, 1, 0, 0.638124,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496916,-99) , 
3, 1.96774, 0, 0, 0.501586,-99) , 
3, 1.80539, 1, 0, 0.511527,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.95824, 0, 0, 0.017719,-99) , 
1, 1.2934, 0, 0, 0.250149,-99) , 
2, 0.310793, 0, 0, 0.507061,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.218879);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.126706, 0, 1, 0.910608,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.541783,-99) , 
2, 4.59613, 0, 0, 0.544932,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.779174,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.95824, 0, 0, 0.017719,-99) , 
1, 1.2934, 0, 0, 0.247772,-99) , 
2, 0.310793, 0, 0, 0.540172,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.242189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460492,-99) , 
0, 0.323851, 1, 0, 0.496918,-99) , 
NN(
0, 
0, 
-1, 1.42314, 0, -1, 0.0129825,-99) , 
0, 1.30454, 1, 0, 0.494953,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182306,-99) , 
0, 0.0523319, 1, 0, 0.257766,-99) , 
2, 3.00062, 0, 0, 0.370639,-99) , 
1, -2.05621, 0, 0, 0.487078,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.506279);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0114027,-99) , 
2, 0.582497, 0, 0, 0.53935,-99) , 
NN(
0, 
0, 
-1, 0.335243, 0, -1, 0.103993,-99) , 
0, 1.14182, 1, 0, 0.531405,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.981475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202632,-99) , 
1, 1.10671, 1, 0, 0.631262,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32089,-99) , 
1, 1.46763, 0, 0, 0.372804,-99) , 
2, 2.78614, 0, 0, 0.431561,-99) , 
0, 0.227434, 0, 0, 0.496363,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.53885);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40885,-99) , 
0, -0.00121265, 1, 0, 0.657402,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.219378,-99) , 
2, 1.63554, 1, 0, 0.336311,-99) , 
1, 0.945469, 1, 0, 0.551997,-99) , 
NN(
NN(
0, 
0, 
-1, 0.531183, 1, 1, 0.743822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399902,-99) , 
3, 1.96986, 0, 0, 0.404242,-99) , 
2, 3.99321, 0, 0, 0.415017,-99) , 
0, 0.0479164, 1, 0, 0.442764,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.25272);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.741268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.150631,-99) , 
2, 1.70015, 0, 0, 0.676344,-99) , 
NN(
0, 
0, 
-1, 1.14306, 0, -1, 0.00987886,-99) , 
2, 3.10027, 1, 0, 0.629705,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78467, 0, 0, 0.529566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.527894,-99) , 
0, 0.945503, 0, 0, 0.538512,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.317228);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.793529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197304,-99) , 
2, 1.67406, 0, 0, 0.710045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0119,-99) , 
1, -0.42417, 1, 0, 0.357945,-99) , 
2, 2.4754, 1, 0, 0.594942,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46901,-99) , 
0, 0.219479, 0, 0, 0.499205,-99) , 
NN(
0, 
0, 
-1, 1.93577, 1, -1, 0.444393,-99) , 
0, 0.290857, 1, 0, 0.466084,-99) , 
0, 0.945503, 0, 0, 0.478812,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.182654);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.96638, 0, 1, 0.543077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.541687,-99) , 
NN(
0, 
0, 
-1, -0.972735, 1, -1, 0.016349,-99) , 
2, -0.42569, 0, 0, 0.540144,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.155951);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 3.02629, 0, 1, 0.642846,-99) , 
NN(
0, 
0, 
-1, 1.76014, 0, -1, 0.47529,-99) , 
3, 1.92767, 0, 0, 0.493838,-99) , 
3, 1.97399, 0, 0, 0.495066,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.28622);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.816528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1.57712, 0, 0, 0.749428,-99) , 
NN(
0, 
0, 
-1, -0.392755, 1, 1, 0.525101,-99) , 
3, 1.80539, 1, 0, 0.541925,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80618, 0, 0, 0.546877,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0311676,-99) , 
1, 1.89037, 0, 0, 0.207479,-99) , 
1, 1.01346, 1, 0, 0.486109,-99) , 
0, 0.586468, 1, 0, 0.525347,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.394892);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.78062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77461, 0, 0, 0.708285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.597572, 1, 0, 0.573105,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.759052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462228,-99) , 
1, 1.6828, 0, 0, 0.506473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417964,-99) , 
0, -0.395304, 1, 0, 0.425783,-99) , 
0, 0.560012, 0, 0, 0.453022,-99) , 
3, 1.80539, 1, 0, 0.46027,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.176627);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.96638, 0, 1, 0.542084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.541094,-99) , 
NN(
0, 
0, 
-1, -0.972735, 1, -1, 0.0207367,-99) , 
2, -0.42569, 0, 0, 0.539757,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.118648);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.847717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487672,-99) , 
3, 1.94026, 0, 0, 0.499956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78983, 0, 0, 0.494927,-99) , 
3, 1.97399, 0, 0, 0.496071,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.147263);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44097,-99) , 
0, -0.164841, 0, 0, 0.525822,-99) , 
NN(
0, 
0, 
-1, 1.42462, 0, -1, 0.0277178,-99) , 
0, 1.30454, 1, 0, 0.524769,-99) , 
NN(
0, 
0, 
-1, -0.972735, 1, -1, 0.024644,-99) , 
2, -0.42569, 0, 0, 0.52365,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.115766);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.812422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486381,-99) , 
3, 1.94026, 0, 0, 0.49674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78983, 0, 0, 0.49172,-99) , 
3, 1.97399, 0, 0, 0.492772,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0918371);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.990289,-99) , 
NN(
NN(
0, 
0, 
-1, 0.789535, 1, 1, 0.520405,-99) , 
NN(
0, 
0, 
-1, -0.916518, 1, -1, 0.0281657,-99) , 
2, -0.0926065, 0, 0, 0.518769,-99) , 
2, 4.72969, 0, 0, 0.519813,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0698633);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.989365,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490703,-99) , 
2, 0.789535, 1, 0, 0.497457,-99) , 
NN(
0, 
0, 
-1, -0.916518, 1, -1, 0.0307914,-99) , 
2, -0.0926065, 0, 0, 0.49597,-99) , 
2, 4.72969, 0, 0, 0.497016,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.359376);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.976637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405935,-99) , 
1, 1.10671, 1, 0, 0.713828,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297493,-99) , 
2, 2.4611, 1, 0, 0.497554,-99) , 
2, 2.78614, 0, 0, 0.543361,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451917,-99) , 
0, 0.457365, 0, 0, 0.508398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.98978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.186589,-99) , 
2, 2.8969, 0, 0, 0.330707,-99) , 
1, 1.93577, 1, 0, 0.497274,-99) , 
0, 0.227434, 1, 0, 0.51247,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.414534);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300682,-99) , 
3, 1.82153, 0, 0, 0.580042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.996107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427902,-99) , 
1, 2.53512, 0, 0, 0.445856,-99) , 
2, 1.99703, 0, 0, 0.52073,-99) , 
NN(
0, 
0, 
-1, 1.01346, 1, -1, 0.406085,-99) , 
0, 0.586468, 1, 0, 0.485832,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.305555);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.50243, 1, 1, 0.764036,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425298,-99) , 
0, 0.182824, 0, 0, 0.533911,-99) , 
0, -0.311118, 1, 0, 0.542548,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.99007,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429973,-99) , 
0, 0.234734, 1, 0, 0.466518,-99) , 
1, 2.5713, 0, 0, 0.472185,-99) , 
2, 2.52024, 1, 0, 0.515683,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0720476);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.824613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497535,-99) , 
3, 1.94026, 0, 0, 0.507458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78983, 0, 0, 0.502481,-99) , 
3, 1.97399, 0, 0, 0.503491,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.156541);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.80982, 1, 1, 0.55777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80024, 0, 0, 0.496534,-99) , 
0, 0.323851, 1, 0, 0.521368,-99) , 
NN(
0, 
0, 
-1, 2.24172, 0, -1, 0.0329166,-99) , 
0, 1.30454, 1, 0, 0.520369,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.227825);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.768094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1.57712, 0, 0, 0.704901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.597572, 1, 0, 0.579853,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467873,-99) , 
3, 1.95276, 0, 0, 0.474144,-99) , 
3, 1.96757, 0, 0, 0.476528,-99) , 
3, 1.80539, 1, 0, 0.482678,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.373588);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77408, 0, 0, 0.575254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.689584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443202,-99) , 
2, 1.46254, 1, 0, 0.493861,-99) , 
3, 1.88969, 1, 0, 0.544315,-99) , 
NN(
NN(
0, 
0, 
-1, 4.16837, 1, 1, 0.951058,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.312111,-99) , 
2, 2.47861, 1, 0, 0.457248,-99) , 
2, 3.39063, 0, 0, 0.490547,-99) , 
1, -0.72555, 0, 0, 0.532982,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.278371);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.436729, 0, 1, 0.725539,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.918653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487031,-99) , 
0, -0.110068, 1, 0, 0.506281,-99) , 
0, 0.910228, 0, 0, 0.544874,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342986,-99) , 
0, -0.0818547, 0, 0, 0.521613,-99) , 
NN(
0, 
0, 
-1, 0.59517, 1, -1, 0.415993,-99) , 
2, 2.10665, 0, 0, 0.470921,-99) , 
3, 1.88969, 0, 0, 0.49923,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.351578);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310689,-99) , 
2, 0.816588, 0, 0, 0.885061,-99) , 
NN(
0, 
0, 
-1, -0.00766451, 1, 1, 0.57686,-99) , 
0, -0.14042, 1, 0, 0.586153,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.749052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364997,-99) , 
0, -0.18253, 0, 0, 0.580671,-99) , 
NN(
0, 
0, 
-1, 1.09707, 1, -1, 0.446301,-99) , 
0, 0.0618393, 1, 0, 0.47648,-99) , 
3, 1.88969, 0, 0, 0.518509,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.236715);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.985874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300426,-99) , 
1, 1.0177, 1, 0, 0.819042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498336,-99) , 
2, 2.07141, 1, 0, 0.536992,-99) , 
2, 4.34401, 0, 0, 0.540206,-99) , 
NN(
NN(
0, 
0, 
-1, 4.16837, 1, 1, 0.934011,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.995024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417969,-99) , 
0, -0.311388, 1, 0, 0.442456,-99) , 
2, 3.39063, 0, 0, 0.473067,-99) , 
1, -0.72555, 0, 0, 0.526428,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.212869);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.127909, 1, 1, 0.591273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0383168,-99) , 
2, 3.07801, 0, 0, 0.329791,-99) , 
0, -0.293031, 0, 0, 0.582074,-99) , 
NN(
NN(
0, 
0, 
-1, -0.197702, 1, 1, 0.516155,-99) , 
NN(
0, 
0, 
-1, 0.585762, 0, -1, 0.102041,-99) , 
0, 1.12502, 1, 0, 0.51108,-99) , 
2, 2.52024, 0, 0, 0.538319,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.243646);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.948352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0835489,-99) , 
1, -0.34123, 1, 0, 0.814873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462743,-99) , 
0, 0.390451, 0, 0, 0.523893,-99) , 
0, 1.11434, 0, 0, 0.532375,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.997499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394823,-99) , 
2, 1.50243, 1, 0, 0.674057,-99) , 
NN(
0, 
0, 
-1, -2.05621, 0, -1, 0.451503,-99) , 
0, -0.311118, 1, 0, 0.459182,-99) , 
2, 2.52024, 0, 0, 0.486954,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.277113);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.392755, 1, 1, 0.546923,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.991722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.15753,-99) , 
0, -0.179319, 1, 0, 0.277526,-99) , 
2, 0.725004, 0, 0, 0.536764,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80618, 0, 0, 0.528601,-99) , 
NN(
0, 
0, 
-1, 0.88567, 0, -1, 0.201466,-99) , 
1, 1.01346, 1, 0, 0.482331,-99) , 
0, 0.586468, 1, 0, 0.519908,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.218277);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45625,-99) , 
3, 1.94026, 0, 0, 0.464078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78983, 0, 0, 0.4596,-99) , 
3, 1.97399, 0, 0, 0.460453,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0985429);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.990401,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0308402,-99) , 
2, -0.257625, 0, 0, 0.516101,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0421897,-99) , 
2, 4.23282, 0, 0, 0.351158,-99) , 
2, 4.12151, 1, 0, 0.511194,-99) , 
2, 4.72969, 0, 0, 0.511978,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.105001);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.989417,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46445,-99) , 
2, 1.93042, 0, 0, 0.491586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0463564,-99) , 
2, 4.23282, 0, 0, 0.342376,-99) , 
2, 4.12151, 1, 0, 0.487226,-99) , 
2, 4.72969, 0, 0, 0.48801,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.293961);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.907417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.109479,-99) , 
0, 0.900209, 1, 0, 0.743707,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00034055,-99) , 
0, 0.532329, 1, 0, 0.492463,-99) , 
0, 0.760118, 0, 0, 0.553936,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472389,-99) , 
1, -1.74571, 1, 0, 0.485729,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270353,-99) , 
2, 1.17578, 1, 0, 0.375676,-99) , 
2, 1.51674, 0, 0, 0.474144,-99) , 
2, 1.04728, 1, 0, 0.483157,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.306484);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.7868, 0, 1, 0.54826,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.739631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338295,-99) , 
0, 0.369551, 1, 0, 0.470825,-99) , 
2, 3.25673, 1, 0, 0.538605,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.20748,-99) , 
0, 0.0523319, 1, 0, 0.284642,-99) , 
2, 3.00062, 0, 0, 0.368248,-99) , 
1, -2.05621, 0, 0, 0.530635,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.280798);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250679,-99) , 
0, -0.288911, 0, 0, 0.50749,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371808,-99) , 
0, -0.295835, 1, 0, 0.402183,-99) , 
2, 1.56949, 0, 0, 0.483799,-99) , 
NN(
NN(
0, 
0, 
-1, 4.16837, 1, 1, 0.907807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.986433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37931,-99) , 
0, -0.311388, 1, 0, 0.397437,-99) , 
2, 3.39063, 0, 0, 0.419994,-99) , 
1, -0.72555, 0, 0, 0.471152,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.213894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.98954,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448151,-99) , 
2, 0.789535, 1, 0, 0.453241,-99) , 
NN(
0, 
0, 
-1, -0.916518, 1, -1, 0.0309844,-99) , 
2, -0.0926065, 0, 0, 0.452141,-99) , 
2, 4.72969, 0, 0, 0.45293,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.036198);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 1.95694, 0, 1, 0.504111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78983, 0, 0, 0.499808,-99) , 
3, 1.97399, 0, 0, 0.500525,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0670491);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491479,-99) , 
3, 1.95694, 0, 0, 0.495062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78983, 0, 0, 0.490912,-99) , 
3, 1.97399, 0, 0, 0.491628,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.122278);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.416625, 1, 1, 0.548645,-99) , 
NN(
0, 
0, 
-1, 1.80024, 0, -1, 0.482529,-99) , 
0, 0.323851, 1, 0, 0.50883,-99) , 
NN(
0, 
0, 
-1, 2.24172, 0, -1, 0.0334343,-99) , 
0, 1.30454, 1, 0, 0.508112,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.22319);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.750648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0953886,-99) , 
2, 1.67406, 0, 0, 0.679763,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0133671,-99) , 
1, -0.42417, 1, 0, 0.360025,-99) , 
2, 2.4754, 1, 0, 0.576124,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.812918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44628,-99) , 
0, 0.776387, 1, 0, 0.5739,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.948566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491951,-99) , 
0, -0.384515, 1, 0, 0.496569,-99) , 
0, 0.681603, 0, 0, 0.50786,-99) , 
0, 0.945503, 0, 0, 0.514443,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.40974);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.194526, 0, 1, 0.580549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0127128,-99) , 
0, 0.107318, 1, 0, 0.262073,-99) , 
2, 0.725004, 0, 0, 0.569722,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.81629, 0, 0, 0.574643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00670957,-99) , 
1, 0.775601, 1, 0, 0.36958,-99) , 
0, 0.668824, 0, 0, 0.524214,-99) , 
0, 0.586468, 1, 0, 0.556387,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.254772);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47558,-99) , 
2, 3.02629, 0, 0, 0.613997,-99) , 
NN(
0, 
0, 
-1, 1.76014, 0, -1, 0.446372,-99) , 
3, 1.92767, 0, 0, 0.462273,-99) , 
3, 1.97399, 0, 0, 0.462993,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.140492);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27272,-99) , 
2, 0.582497, 0, 0, 0.52601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.739186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000399905,-99) , 
1, 0.421246, 0, 0, 0.160873,-99) , 
0, 1.13834, 1, 0, 0.524139,-99) , 
NN(
0, 
0, 
-1, 1.42314, 0, -1, 0.0266353,-99) , 
0, 1.30454, 1, 0, 0.523381,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0978963);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.990561,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487474,-99) , 
2, 3.57145, 0, 0, 0.492647,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0404835,-99) , 
2, 4.23282, 0, 0, 0.373197,-99) , 
2, 4.12151, 1, 0, 0.48898,-99) , 
2, 4.72969, 0, 0, 0.489615,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0666378);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95028, 0, 1, 0.513965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78248, 0, 0, 0.511772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.511122,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.167362);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.902485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1.49964, 0, 0, 0.743199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 2.97567, 0, 0, 0.313,-99) , 
2, 1.83983, 1, 0, 0.572129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484514,-99) , 
3, 1.95276, 0, 0, 0.48813,-99) , 
3, 1.96757, 0, 0, 0.489983,-99) , 
3, 1.80539, 1, 0, 0.494647,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.151635);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95028, 0, 1, 0.535385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78248, 0, 0, 0.533215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.532561,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.106055);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480473,-99) , 
0, 0.54327, 0, 0, 0.497365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000404851,-99) , 
1, 0.421246, 0, 0, 0.160996,-99) , 
0, 1.13834, 1, 0, 0.495754,-99) , 
NN(
0, 
0, 
-1, 1.42314, 0, -1, 0.0271006,-99) , 
0, 1.30454, 1, 0, 0.495095,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.355431);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.550473, 0, 1, 0.569662,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344678,-99) , 
0, 0.0694605, 1, 0, 0.465212,-99) , 
0, 0.194526, 0, 0, 0.527484,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.180786,-99) , 
1, -2.14845, 0, 0, 0.524964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321478,-99) , 
2, 0.660992, 1, 0, 0.370436,-99) , 
1, -0.185439, 1, 0, 0.44835,-99) , 
0, 0.586468, 1, 0, 0.504638,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.182018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.262398, 1, 1, 0.988595,-99) , 
NN(
NN(
0, 
0, 
-1, -0.131601, 0, -1, 0.460888,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0342467,-99) , 
0, -0.0132616, 0, 0, 0.310079,-99) , 
2, 4.12151, 1, 0, 0.455804,-99) , 
2, 4.72969, 0, 0, 0.456468,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.241961);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412802,-99) , 
3, 1.90223, 1, 0, 0.548663,-99) , 
NN(
0, 
0, 
-1, 1.80024, 0, -1, 0.48388,-99) , 
0, 0.310447, 1, 0, 0.505564,-99) , 
NN(
NN(
0, 
0, 
-1, -0.458601, 0, 1, 0.995949,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.980006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356681,-99) , 
1, -1.3573, 1, 0, 0.399288,-99) , 
0, -0.392956, 1, 0, 0.441107,-99) , 
0, -0.131601, 0, 0, 0.499986,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.325977);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.15562, 1, 1, 0.552574,-99) , 
NN(
0, 
0, 
-1, 0.285697, 0, -1, 0.050234,-99) , 
0, 1.22314, 1, 0, 0.550797,-99) , 
NN(
NN(
0, 
0, 
-1, 2.37779, 0, 1, 0.713008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328737,-99) , 
3, 1.9154, 0, 0, 0.367161,-99) , 
1, -0.493345, 1, 0, 0.470286,-99) , 
0, 0.0479164, 0, 0, 0.535701,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.250452);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.458601, 0, 1, 0.996233,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.931476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.171346,-99) , 
1, 0.292787, 1, 0, 0.450031,-99) , 
0, -0.394876, 1, 0, 0.580972,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455283,-99) , 
3, 1.92767, 0, 0, 0.471274,-99) , 
3, 1.97399, 0, 0, 0.471864,-99) , 
0, -0.311118, 1, 0, 0.47477,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.119695);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95028, 0, 1, 0.527401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78248, 0, 0, 0.525258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.524626,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0555092);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492966,-99) , 
3, 1.95028, 0, 0, 0.497505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78248, 0, 0, 0.495597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.495034,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0540098);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95028, 0, 1, 0.511137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78248, 0, 0, 0.50923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.72109, 0, 0, 0.508668,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.209576);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.754002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48493,-99) , 
2, 3.08512, 0, 0, 0.567146,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419695,-99) , 
2, 2.3565, 1, 0, 0.487349,-99) , 
2, 2.7868, 0, 0, 0.501304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335942,-99) , 
0, 0.369551, 1, 0, 0.417983,-99) , 
1, -1.35958, 1, 0, 0.450775,-99) , 
2, 3.25673, 1, 0, 0.495295,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.312412);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.906962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42895,-99) , 
1, -2.13937, 0, 0, 0.672299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40208,-99) , 
1, -0.350521, 0, 0, 0.492766,-99) , 
1, -1.74571, 1, 0, 0.503699,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409062,-99) , 
1, 0.605108, 0, 0, 0.472717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.161461,-99) , 
0, 0.0443097, 1, 0, 0.358808,-99) , 
0, 0.239616, 0, 0, 0.432734,-99) , 
2, 1.78376, 0, 0, 0.480489,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.41133);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.676888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324802,-99) , 
0, 0.73715, 1, 0, 0.596781,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254024,-99) , 
1, -1.33378, 1, 0, 0.385706,-99) , 
2, 1.98461, 0, 0, 0.525741,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.98236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338152,-99) , 
1, -0.430228, 1, 0, 0.588019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433874,-99) , 
1, 2.90459, 0, 0, 0.435833,-99) , 
0, 0.950724, 0, 0, 0.447864,-99) , 
1, -0.72555, 1, 0, 0.462635,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.240758);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.7868, 0, 1, 0.54624,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.99701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45138,-99) , 
1, 1.76202, 0, 0, 0.48203,-99) , 
2, 3.25673, 1, 0, 0.538602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198664,-99) , 
0, 0.710766, 0, 0, 0.353769,-99) , 
2, 3.00062, 0, 0, 0.437237,-99) , 
1, -2.05621, 0, 0, 0.534532,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.202127);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495959,-99) , 
0, 0.68126, 0, 0, 0.535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.993776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.144937,-99) , 
2, 2.78515, 1, 0, 0.342591,-99) , 
0, 0.938421, 1, 0, 0.522165,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466135,-99) , 
0, -0.197702, 1, 0, 0.474042,-99) , 
NN(
0, 
0, 
-1, 0.585762, 0, -1, 0.122713,-99) , 
0, 1.12502, 1, 0, 0.471128,-99) , 
2, 2.52024, 0, 0, 0.490362,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.212419);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.19468, 0, 1, 0.572738,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.992392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.171825,-99) , 
2, 2.78515, 1, 0, 0.358453,-99) , 
0, 0.938421, 1, 0, 0.559384,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494403,-99) , 
0, 0.534631, 0, 0, 0.519934,-99) , 
NN(
0, 
0, 
-1, 0.585762, 0, -1, 0.146182,-99) , 
0, 1.12502, 1, 0, 0.517045,-99) , 
2, 2.52024, 0, 0, 0.532953,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.23712);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.392755, 1, 1, 0.543445,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.81629, 0, 0, 0.53469,-99) , 
NN(
0, 
0, 
-1, 0.775601, 1, -1, 0.322415,-99) , 
0, 0.668824, 0, 0, 0.483516,-99) , 
0, 0.586468, 1, 0, 0.526868,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.26831);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0586474,-99) , 
0, 0.895367, 1, 0, 0.546397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.80263, 0, 0, 0.532625,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.68927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465117,-99) , 
1, -1.74571, 1, 0, 0.477485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257772,-99) , 
1, 0.673182, 0, 0, 0.408394,-99) , 
2, 1.51674, 0, 0, 0.469957,-99) , 
2, 1.04728, 1, 0, 0.476402,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.21353);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.985742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264672,-99) , 
1, 1.0177, 1, 0, 0.893055,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47203,-99) , 
2, 1.50425, 0, 0, 0.528715,-99) , 
2, 4.34401, 0, 0, 0.532799,-99) , 
NN(
NN(
0, 
0, 
-1, 4.16837, 1, 1, 0.927128,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366816,-99) , 
3, 1.86957, 0, 0, 0.441733,-99) , 
2, 3.39063, 0, 0, 0.463332,-99) , 
1, -0.72555, 0, 0, 0.520234,-99)    );
   return;
};
 
// Clean up
inline void ReadCUTS_10::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadCUTS_10::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
