// Class: ReadCUTS_5
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::CUTS_5
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : jlang
Date           : Tue Dec  8 16:22:08 2015
Host           : Linux ekpams2 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 21:44:51 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /usr/users/jlang/BDT/Test/BDT_Training
Training events: 1332
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "10" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "5" [Number of steps during node cut optimisation]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1332" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
v0                            v0                            v0                            v0                                                              'F'    [-0.490635514259,1.48405468464]
v1                            v1                            v1                            v1                                                              'F'    [-7.37883806229,7.25839614868]
v2                            v2                            v2                            v2                                                              'F'    [-1.8986569643,6.2026591301]
v3                            v3                            v3                            v3                                                              'F'    [1.46819293499,2.39548110962]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new CUTS_5Node
   
#ifndef CUTS_5Node__def
#define CUTS_5Node__def
   
class CUTS_5Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   CUTS_5Node ( CUTS_5Node* left,CUTS_5Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~CUTS_5Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   CUTS_5Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   CUTS_5Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   CUTS_5Node*   fLeft;     // pointer to the left daughter node
   CUTS_5Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   CUTS_5Node::~CUTS_5Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool CUTS_5Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool CUTS_5Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCUTS_5 : public IClassifierReader {

 public:

   // constructor
   ReadCUTS_5( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCUTS_5" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "v0", "v1", "v2", "v3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.490635514259338;
      fVmax[0] = 1.48405468463898;
      fVmin[1] = -7.37883806228638;
      fVmax[1] = 7.25839614868164;
      fVmin[2] = -1.89865696430206;
      fVmax[2] = 6.20265913009644;
      fVmin[3] = 1.46819293498993;
      fVmax[3] = 2.39548110961914;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCUTS_5() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<CUTS_5Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadCUTS_5::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      CUTS_5Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(CUTS_5Node*)current->GetRight();
         else current=(CUTS_5Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadCUTS_5::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(2.34032542097689);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.00914, 0, 1, 0.994118,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.185393,-99) , 
0, 0.506097, 1, 0, 0.412987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77688, 0, 0, 0.193431,-99) , 
3, 1.93184, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.99477);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424716,-99) , 
3, 1.94466, 0, 0, 0.772855,-99) , 
3, 2.00914, 0, 0, 0.94211,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77999, 0, 0, 0.440653,-99) , 
NN(
0, 
0, 
-1, 3.23525, 0, -1, 0.11309,-99) , 
0, 0.506282, 0, 0, 0.247743,-99) , 
3, 1.93184, 0, 0, 0.401519,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.36707);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.00914, 0, 1, 0.954468,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162237,-99) , 
0, 0.832139, 1, 0, 0.5298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.11281,-99) , 
0, -0.145567, 1, 0, 0.144732,-99) , 
2, 1.77287, 0, 0, 0.35307,-99) , 
3, 1.93184, 0, 0, 0.449256,-99)    );
  // itree = 3
  fBoostWeights.push_back(1.00332);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.00914, 0, 1, 0.842329,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33622,-99) , 
3, 1.8927, 0, 0, 0.463674,-99) , 
NN(
0, 
0, 
-1, 1.789, 0, -1, 0.19297,-99) , 
3, 1.85405, 0, 0, 0.328636,-99) , 
3, 1.93184, 0, 0, 0.387047,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.361305);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.81324, 0, -1, 0.4653,-99) , 
3, 1.9845, 0, 0, 0.490249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.453838,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.59064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255093,-99) , 
3, 1.81324, 0, 0, 0.555343,-99) , 
3, 1.9845, 0, 0, 0.572733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.536646,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.483767);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.978312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423113,-99) , 
2, 4.60562, 0, 0, 0.436587,-99) , 
3, 1.9845, 0, 0, 0.453455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.431255,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.436443);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492716,-99) , 
3, 1.88175, 1, 0, 0.575506,-99) , 
NN(
0, 
0, 
-1, 1.77311, 0, -1, 0.0577631,-99) , 
0, 1.15463, 1, 0, 0.562331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.54008,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.359969);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0651928,-99) , 
0, 1.15782, 1, 0, 0.543126,-99) , 
3, 1.9845, 0, 0, 0.556968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.538826,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.327037);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.938345,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448726,-99) , 
2, 4.60562, 0, 0, 0.456994,-99) , 
3, 1.9845, 0, 0, 0.470888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.457868,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.253869);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.932105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296754,-99) , 
1, 1.20793, 1, 0, 0.79595,-99) , 
NN(
0, 
0, 
-1, 1.9845, 0, 1, 0.526554,-99) , 
2, 3.65783, 0, 0, 0.546146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.533152,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.336871);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.914167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352302,-99) , 
1, 1.20793, 1, 0, 0.787708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453524,-99) , 
3, 1.9845, 0, 0, 0.463179,-99) , 
2, 3.65783, 0, 0, 0.484783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.474542,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.317511);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0118849,-99) , 
2, -0.159416, 0, 0, 0.547495,-99) , 
1, 2.81803, 0, 0, 0.558302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.548194,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.245207);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462263,-99) , 
3, 1.9845, 0, 0, 0.470302,-99) , 
1, 2.81803, 0, 0, 0.481204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.473677,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.34283);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.167471, 1, 1, 0.560842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78193, 0, 0, 0.551235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.900903,-99) , 
NN(
0, 
0, 
-1, 0.351579, 0, -1, 0.268186,-99) , 
1, 1.92426, 0, 0, 0.329737,-99) , 
2, 0.801782, 0, 0, 0.530904,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.4126);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43997,-99) , 
1, -0.940631, 1, 0, 0.520998,-99) , 
3, 1.93532, 0, 0, 0.545016,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394108,-99) , 
0, 0.714026, 0, 0, 0.435202,-99) , 
NN(
0, 
0, 
-1, 1.41114, 0, -1, 0.0070017,-99) , 
0, 1.26479, 1, 0, 0.428842,-99) , 
0, 0.167595, 1, 0, 0.461627,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.399729);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.51461, 0, 1, 0.607764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78193, 0, 0, 0.595232,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470838,-99) , 
1, 0.597841, 0, 0, 0.536023,-99) , 
NN(
0, 
0, 
-1, 1.19196, 1, -1, 0.378702,-99) , 
0, 0.606983, 1, 0, 0.469707,-99) , 
0, 0.167595, 1, 0, 0.50468,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.253531);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390011,-99) , 
1, 1.33227, 1, 0, 0.513943,-99) , 
1, 2.81803, 0, 0, 0.521878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.516606,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.129668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.15813, 1, -1, 0.471229,-99) , 
3, 2.08639, 0, 0, 0.47527,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.10603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.517047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.513028,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.132485,-99) , 
0, 1.15494, 1, 0, 0.507177,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.108142);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.998752,-99) , 
NN(
NN(
0, 
0, 
-1, 1.77729, 0, -1, 0.486812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0162115,-99) , 
1, 0.954443, 0, 0, 0.194375,-99) , 
2, 0.35051, 0, 0, 0.477975,-99) , 
2, 4.85244, 0, 0, 0.481665,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0705563);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498859,-99) , 
3, 1.9845, 0, 0, 0.504312,-99) , 
1, 2.81803, 0, 0, 0.511705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.507807,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.127897);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.528461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.524573,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.05413);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, -0.302034, 0, -1, 0.495101,-99) , 
3, 2.08639, 0, 0, 0.49837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.135554,-99) , 
0, 1.15494, 1, 0, 0.493084,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0921752);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.514924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.511729,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.134658,-99) , 
0, 1.15494, 1, 0, 0.506344,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0876058);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, -0.302034, 0, -1, 0.485873,-99) , 
3, 2.08639, 0, 0, 0.488969,-99) , 
NN(
0, 
0, 
-1, 1.90474, 0, -1, 0.133047,-99) , 
0, 1.15494, 1, 0, 0.484051,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.108716);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.513966,-99) , 
NN(
0, 
0, 
-1, 0.467103, 1, -1, 0.0249661,-99) , 
2, -0.23711, 0, 0, 0.510609,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.143481,-99) , 
0, 1.15494, 1, 0, 0.50569,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.194558);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.998869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471031,-99) , 
2, 1.11057, 1, 0, 0.485438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0148929,-99) , 
1, 0.954443, 0, 0, 0.170832,-99) , 
2, 0.35051, 0, 0, 0.476345,-99) , 
2, 4.85244, 0, 0, 0.479661,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.208977);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.98763, 0, 1, 0.53441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78193, 0, 0, 0.52967,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.223852,-99) , 
2, 0.435882, 0, 0, 0.453303,-99) , 
NN(
0, 
0, 
-1, -0.354667, 1, -1, 0.0774175,-99) , 
0, 0.818502, 1, 0, 0.3629,-99) , 
2, 0.801782, 0, 0, 0.515956,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.147998);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0.671934, 0, -1, 0.465638,-99) , 
3, 2.08639, 0, 0, 0.468586,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.220908);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.765401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323494,-99) , 
1, 1.20793, 1, 0, 0.650685,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465511,-99) , 
1, -0.060221, 1, 0, 0.4995,-99) , 
2, 3.62675, 0, 0, 0.509386,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.16062,-99) , 
0, 1.15494, 1, 0, 0.505139,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.165154);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.993406,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.029389,-99) , 
0, 0.513014, 1, 0, 0.668653,-99) , 
2, 2.82329, 0, 0, 0.728368,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.78193, 0, 0, 0.513642,-99) , 
NN(
0, 
0, 
-1, 0.351579, 0, -1, 0.34639,-99) , 
2, 0.801782, 0, 0, 0.501252,-99) , 
1, 2.37932, 0, 0, 0.509423,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.187592);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.992232,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0344846,-99) , 
0, 0.513014, 1, 0, 0.642182,-99) , 
2, 2.82329, 0, 0, 0.704472,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998851,-99) , 
NN(
0, 
0, 
-1, 0.35051, 0, -1, 0.463895,-99) , 
2, 4.85244, 0, 0, 0.466586,-99) , 
1, 2.37932, 0, 0, 0.474766,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.11849);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0247699,-99) , 
2, -0.302034, 0, 0, 0.519601,-99) , 
3, 2.08639, 0, 0, 0.522161,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.165465,-99) , 
0, 1.15494, 1, 0, 0.518279,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0785074);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488222,-99) , 
3, 1.98334, 0, 0, 0.490235,-99) , 
NN(
0, 
0, 
-1, 1.21377, 1, -1, 0.153868,-99) , 
0, 1.15813, 1, 0, 0.486728,-99) , 
3, 2.08639, 0, 0, 0.489336,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0616151);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, -0.200598, 1, 1, 0.509708,-99) , 
NN(
0, 
0, 
-1, 1.21377, 1, -1, 0.164369,-99) , 
0, 1.15813, 1, 0, 0.5062,-99) , 
3, 2.08639, 0, 0, 0.508614,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.147431);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 1.9491, 0, 1, 0.525665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342065,-99) , 
2, 1.62086, 0, 0, 0.461502,-99) , 
3, 1.88031, 0, 0, 0.491107,-99) , 
3, 2.08639, 0, 0, 0.493521,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.202528);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 2.82329, 0, 1, 0.650241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456395,-99) , 
3, 1.98334, 0, 0, 0.458293,-99) , 
1, 2.37932, 0, 0, 0.464262,-99) , 
3, 2.08639, 0, 0, 0.466629,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0983305);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.998786,-99) , 
NN(
NN(
0, 
0, 
-1, 1.11057, 1, 1, 0.516272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0277013,-99) , 
1, 0.954443, 0, 0, 0.25153,-99) , 
2, 0.35051, 0, 0, 0.511178,-99) , 
2, 4.85244, 0, 0, 0.513314,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.160072);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.998661,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47693,-99) , 
2, 1.11057, 1, 0, 0.491696,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0304764,-99) , 
1, 0.954443, 0, 0, 0.249155,-99) , 
2, 0.35051, 0, 0, 0.487174,-99) , 
2, 4.85244, 0, 0, 0.48931,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0937142);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.521556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.519533,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0952686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488692,-99) , 
0, -0.200598, 1, 0, 0.497431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00343604,-99) , 
0, 1.21377, 1, 0, 0.178543,-99) , 
0, 1.15813, 1, 0, 0.494305,-99) , 
3, 2.08639, 0, 0, 0.496295,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.106554);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.522078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.520329,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.182685,-99) , 
0, 1.15494, 1, 0, 0.517105,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0807266);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.998548,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.828837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490334,-99) , 
1, -2.49976, 1, 0, 0.494027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0300012,-99) , 
1, 0.954443, 0, 0, 0.225644,-99) , 
2, 0.35051, 0, 0, 0.489126,-99) , 
2, 4.85244, 0, 0, 0.490972,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.266442);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.79419, 0, 0, 0.54682,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431675,-99) , 
0, 0.331577, 1, 0, 0.485963,-99) , 
2, 2.3388, 0, 0, 0.513221,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.90474, 0, 0, 0.190443,-99) , 
0, 1.15494, 1, 0, 0.510299,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.513685);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465517,-99) , 
2, 2.58007, 1, 0, 0.558132,-99) , 
NN(
0, 
0, 
-1, 0.790245, 1, -1, 0.314366,-99) , 
2, 3.50222, 1, 0, 0.537863,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375057,-99) , 
0, 0.194039, 0, 0, 0.474653,-99) , 
NN(
0, 
0, 
-1, 0.386966, 0, -1, 0.369907,-99) , 
0, 0.332109, 1, 0, 0.446863,-99) , 
0, 0.49671, 0, 0, 0.484837,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.242041);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.552022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239198,-99) , 
0, 0.698779, 0, 0, 0.449938,-99) , 
0, 0.605701, 1, 0, 0.521085,-99) , 
NN(
0, 
0, 
-1, 1.90474, 0, -1, 0.144841,-99) , 
0, 1.15494, 1, 0, 0.517483,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.293201);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.119091,-99) , 
0, 0.761658, 1, 0, 0.577619,-99) , 
NN(
0, 
0, 
-1, 1.15813, 1, -1, 0.447919,-99) , 
2, 3.24252, 0, 0, 0.464217,-99) , 
3, 2.08639, 0, 0, 0.466226,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.107997);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.52545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.523764,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.101728);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427234,-99) , 
0, 0.168458, 1, 0, 0.501818,-99) , 
1, -0.126828, 1, 0, 0.610805,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.15813, 1, 0, 0.498734,-99) , 
NN(
0, 
0, 
-1, 0.954443, 0, -1, 0.163616,-99) , 
2, 0.549028, 0, 0, 0.489617,-99) , 
3, 1.93184, 0, 0, 0.496955,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.173759);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452291,-99) , 
0, 0.168458, 1, 0, 0.520883,-99) , 
1, -0.126828, 1, 0, 0.622539,-99) , 
NN(
0, 
0, 
-1, 0.549028, 0, -1, 0.465827,-99) , 
3, 1.93184, 0, 0, 0.475139,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.145616);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495443,-99) , 
0, 0.802005, 0, 0, 0.554343,-99) , 
1, -0.126828, 1, 0, 0.643619,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.15813, 1, 0, 0.517013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.954443, 0, 0, 0.204878,-99) , 
2, 0.549028, 0, 0, 0.509213,-99) , 
3, 1.93184, 0, 0, 0.516997,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.146929);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.760269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43854,-99) , 
2, 2.37727, 0, 0, 0.582951,-99) , 
1, -0.126828, 1, 0, 0.662152,-99) , 
NN(
0, 
0, 
-1, 0.549028, 0, -1, 0.474226,-99) , 
3, 1.93184, 0, 0, 0.484929,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.143705);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.126828, 1, 1, 0.663429,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.15813, 1, 0, 0.517693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.954443, 0, 0, 0.223556,-99) , 
2, 0.549028, 0, 0, 0.510934,-99) , 
3, 1.93184, 0, 0, 0.519388,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.120572);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493501,-99) , 
0, 0.168458, 1, 0, 0.553476,-99) , 
1, -0.126828, 1, 0, 0.630627,-99) , 
NN(
0, 
0, 
-1, 0.549028, 0, -1, 0.476224,-99) , 
3, 1.93184, 0, 0, 0.484626,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.113709);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.126828, 1, 1, 0.64691,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.15813, 1, 0, 0.512217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.954443, 0, 0, 0.237954,-99) , 
2, 0.549028, 0, 0, 0.506349,-99) , 
3, 1.93184, 0, 0, 0.513896,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.107733);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494752,-99) , 
0, 0.802005, 0, 0, 0.549089,-99) , 
1, -0.126828, 1, 0, 0.620525,-99) , 
NN(
0, 
0, 
-1, 0.549028, 0, -1, 0.47877,-99) , 
3, 1.93184, 0, 0, 0.486279,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.102222);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.126828, 1, 1, 0.635914,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.15813, 1, 0, 0.510933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.954443, 0, 0, 0.251543,-99) , 
2, 0.549028, 0, 0, 0.50569,-99) , 
3, 1.93184, 0, 0, 0.512513,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0990737);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49031,-99) , 
0, 0.168458, 1, 0, 0.545448,-99) , 
1, -0.126828, 1, 0, 0.611935,-99) , 
NN(
0, 
0, 
-1, 0.549028, 0, -1, 0.480821,-99) , 
3, 1.93184, 0, 0, 0.487612,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0584968);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.513236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.511777,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0572021);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.126828, 1, 1, 0.612671,-99) , 
NN(
NN(
0, 
0, 
-1, 1.15813, 1, -1, 0.495773,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 0.954443, 0, 0, 0.253188,-99) , 
2, 0.549028, 0, 0, 0.491042,-99) , 
3, 1.93184, 0, 0, 0.497238,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0500653);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.511197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.50982,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0703262);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999483,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491055,-99) , 
1, 2.81803, 0, 0, 0.497281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.495971,-99) , 
2, 4.85244, 0, 0, 0.497372,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0679364);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.515748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.514439,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.039734);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999446,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493759,-99) , 
3, 1.98334, 0, 0, 0.494993,-99) , 
3, 2.08639, 0, 0, 0.496237,-99) , 
2, 4.85244, 0, 0, 0.497544,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0389599);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.508555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.507331,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0382153);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494,-99) , 
3, 1.98334, 0, 0, 0.495186,-99) , 
3, 2.08639, 0, 0, 0.496381,-99) , 
2, 4.85244, 0, 0, 0.497638,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0374987);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.508234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.507056,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0368085);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999401,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494222,-99) , 
3, 1.98334, 0, 0, 0.495364,-99) , 
3, 2.08639, 0, 0, 0.496514,-99) , 
2, 4.85244, 0, 0, 0.497725,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0361433);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.507936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.506801,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0790758);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452669,-99) , 
2, 1.47509, 0, 0, 0.495529,-99) , 
3, 2.08639, 0, 0, 0.496638,-99) , 
2, 4.85244, 0, 0, 0.497806,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0770788);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999327,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483862,-99) , 
3, 1.98334, 0, 0, 0.484955,-99) , 
3, 2.08639, 0, 0, 0.486045,-99) , 
2, 4.85244, 0, 0, 0.487191,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0387833);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499318,-99) , 
3, 1.9845, 0, 0, 0.501205,-99) , 
1, 2.81803, 0, 0, 0.507299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.506212,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0708554);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.51669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.515604,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.104554);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49623,-99) , 
2, 2.89922, 0, 0, 0.506998,-99) , 
NN(
0, 
0, 
-1, 0.514348, 1, -1, 0.0524343,-99) , 
2, -0.0995455, 0, 0, 0.505365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0.87897, 1, -1, 0.387076,-99) , 
0, -0.161501, 1, 0, 0.424307,-99) , 
2, 3.50222, 1, 0, 0.49797,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0766384);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.518211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.517201,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0829705);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999359,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266133,-99) , 
0, 0.356236, 1, 0, 0.730392,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442085,-99) , 
1, -0.861227, 0, 0, 0.494925,-99) , 
1, -2.49976, 1, 0, 0.49706,-99) , 
2, 4.85244, 0, 0, 0.498123,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0972927);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282649,-99) , 
0, 0.356236, 1, 0, 0.732653,-99) , 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480836,-99) , 
3, 2.08639, 0, 0, 0.481791,-99) , 
2, 4.85244, 0, 0, 0.482851,-99) , 
1, -2.49976, 1, 0, 0.48504,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.115815);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.7003, 1, 1, 0.51796,-99) , 
NN(
0, 
0, 
-1, 0.514348, 1, -1, 0.0532692,-99) , 
2, -0.0995455, 0, 0, 0.516358,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0.87897, 1, -1, 0.399498,-99) , 
0, -0.161501, 1, 0, 0.434441,-99) , 
2, 3.50222, 1, 0, 0.508911,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0823288);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482151,-99) , 
3, 1.98334, 0, 0, 0.483135,-99) , 
3, 2.08639, 0, 0, 0.484032,-99) , 
2, 4.85244, 0, 0, 0.485073,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0329338);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999245,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499512,-99) , 
1, 2.81803, 0, 0, 0.505398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.50446,-99) , 
2, 4.85244, 0, 0, 0.505421,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0610409);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.51437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.513432,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0592325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.99922,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492486,-99) , 
1, 2.81803, 0, 0, 0.498183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.4973,-99) , 
2, 4.85244, 0, 0, 0.498231,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0575283);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.513542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.51266,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0340974);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999173,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291818,-99) , 
0, 0.356236, 1, 0, 0.723968,-99) , 
NN(
0, 
0, 
-1, 1.77729, 0, -1, 0.495537,-99) , 
1, -2.49976, 1, 0, 0.497452,-99) , 
2, 4.85244, 0, 0, 0.49833,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0335257);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.507572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.506738,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0269828);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999144,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495798,-99) , 
3, 1.98334, 0, 0, 0.496708,-99) , 
3, 2.08639, 0, 0, 0.497536,-99) , 
2, 4.85244, 0, 0, 0.498385,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0292577);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999121,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499665,-99) , 
1, 2.81803, 0, 0, 0.505041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.504235,-99) , 
2, 4.85244, 0, 0, 0.505062,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0550859);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.513003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.512197,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.12341);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306678,-99) , 
3, 1.81155, 0, 0, 0.496771,-99) , 
3, 1.98334, 0, 0, 0.49766,-99) , 
3, 2.08639, 0, 0, 0.498471,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.140113);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999126,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.277132,-99) , 
0, 0.356236, 1, 0, 0.703645,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469254,-99) , 
3, 2.08639, 0, 0, 0.470039,-99) , 
1, -2.49976, 1, 0, 0.471885,-99) , 
2, 4.85244, 0, 0, 0.472709,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0889716);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.998994,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492003,-99) , 
2, 1.85823, 1, 0, 0.508659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00905756,-99) , 
2, -0.0340656, 1, 0, 0.32974,-99) , 
2, 0.35051, 0, 0, 0.506459,-99) , 
2, 4.85244, 0, 0, 0.507178,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0565121);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.81803, 0, 1, 0.513472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 1.77729, 0, 0, 0.512783,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0888439);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352288,-99) , 
3, 1.81155, 0, 0, 0.497093,-99) , 
3, 1.98334, 0, 0, 0.497985,-99) , 
3, 2.08639, 0, 0, 0.498696,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0923074);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.81155, 0, -1, 0.478399,-99) , 
3, 1.98334, 0, 0, 0.479285,-99) , 
3, 2.08639, 0, 0, 0.479991,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.185466);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142494, 0, 1, 0.999023,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495456,-99) , 
0, 0.825825, 0, 0, 0.515687,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0238163,-99) , 
0, 0.816657, 1, 0, 0.457373,-99) , 
2, 1.47509, 0, 0, 0.502221,-99) , 
2, 4.85244, 0, 0, 0.502917,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.421155);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232066,-99) , 
1, 1.20793, 1, 0, 0.756453,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381404,-99) , 
0, 0.603826, 1, 0, 0.520815,-99) , 
2, 3.67083, 0, 0, 0.532925,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0541776,-99) , 
2, 3.27052, 1, 0, 0.565107,-99) , 
NN(
0, 
0, 
-1, 1.89525, 0, -1, 0.0273271,-99) , 
2, 1.5381, 0, 0, 0.450566,-99) , 
0, 0.825825, 1, 0, 0.51822,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.366494);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.67083, 0, 1, 0.54902,-99) , 
NN(
0, 
0, 
-1, 1.5381, 0, -1, 0.402643,-99) , 
0, 0.826344, 1, 0, 0.488166,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459374,-99) , 
2, 4.2634, 0, 0, 0.5373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37969,-99) , 
2, 2.70316, 0, 0, 0.412007,-99) , 
2, 3.48106, 0, 0, 0.423339,-99) , 
0, 0.49671, 0, 0, 0.449482,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.152642);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322585,-99) , 
0, 0.356236, 1, 0, 0.715891,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46534,-99) , 
2, 3.24252, 0, 0, 0.473034,-99) , 
3, 2.08639, 0, 0, 0.473741,-99) , 
1, -2.49976, 1, 0, 0.475703,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0765956);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466567,-99) , 
0, 0.802005, 0, 0, 0.518513,-99) , 
1, -0.126828, 1, 0, 0.588183,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.15813, 1, 0, 0.505161,-99) , 
NN(
0, 
0, 
-1, 0.139347, 1, -1, 0.228598,-99) , 
2, 0.549028, 0, 0, 0.500578,-99) , 
3, 1.93184, 0, 0, 0.505131,-99)    );
   return;
};
 
// Clean up
inline void ReadCUTS_5::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadCUTS_5::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
