// Class: ReadBDTMC
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTMC
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : jlang
Date           : Tue Dec  8 16:30:03 2015
Host           : Linux ekpams2 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 21:44:51 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /usr/users/jlang/BDT/Test/BDT_Training
Training events: 1332
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "10" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1332" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
v0                            v0                            v0                            v0                                                              'F'    [-0.490635514259,1.48405468464]
v1                            v1                            v1                            v1                                                              'F'    [-7.37883806229,7.25839614868]
v2                            v2                            v2                            v2                                                              'F'    [-1.8986569643,6.2026591301]
v3                            v3                            v3                            v3                                                              'F'    [1.46819293499,2.39548110962]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTMCNode
   
#ifndef BDTMCNode__def
#define BDTMCNode__def
   
class BDTMCNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTMCNode ( BDTMCNode* left,BDTMCNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTMCNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTMCNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTMCNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTMCNode*   fLeft;     // pointer to the left daughter node
   BDTMCNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTMCNode::~BDTMCNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTMCNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTMCNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTMC : public IClassifierReader {

 public:

   // constructor
   ReadBDTMC( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTMC" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "v0", "v1", "v2", "v3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.490635514259338;
      fVmax[0] = 1.48405468463898;
      fVmin[1] = -7.37883806228638;
      fVmax[1] = 7.25839614868164;
      fVmin[2] = -1.89865696430206;
      fVmax[2] = 6.20265913009644;
      fVmin[3] = 1.46819293498993;
      fVmax[3] = 2.39548110961914;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTMC() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTMCNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTMC::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTMCNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTMCNode*)current->GetRight();
         else current=(BDTMCNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTMC::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,1) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.939394,0.878788) , 
3, 1.95556, 0, 0, 0.99604,0.49604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909091,0.818182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595238,0.190476) , 
2, 3.02924, 0, 0, 0.703125,0.203125) , 
3, 1.93313, 0, 0, 0.963093,0.463093) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619632,0.239264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.131579,-0.736842) , 
0, 0.601282, 1, 0, 0.418773,-0.0812274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0606061,-0.878788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-1) , 
3, 1.7884, 0, 0, 0.00411523,-0.495885) , 
3, 1.80449, 0, 0, 0.154653,-0.345347) , 
3, 1.90976, 0, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930841,0.458779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473684,-0.163276) , 
0, 1.06866, 1, 0, 0.915162,0.112449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.567941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291667,-0.504404) , 
3, 1.94115, 0, 0, 0.736434,-0.00534123) , 
2, 1.41639, 0, 0, 0.881406,0.0902017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647059,0.784373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188406,-0.185315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0329412,-0.554956) , 
2, 2.00449, 0, 0, 0.0838608,-0.108109) , 
2, 3.97611, 0, 0, 0.0986133,-0.0979877) , 
3, 1.8656, 0, 0, 0.5,-0.00149118)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.526352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.819672,0.532808) , 
3, 1.94461, 0, 0, 0.938202,0.100058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.529899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476534,-0.0944299) , 
3, 1.95841, 0, 0, 0.770932,0.0168065) , 
0, -0.0320195, 1, 0, 0.807645,0.0350786) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130435,-0.0797186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0220588,-0.539613) , 
1, -1.30308, 1, 0, 0.0377358,-0.0884436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119048,-0.00542001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.522592) , 
3, 1.78737, 0, 0, 0.0138122,-0.0380973) , 
2, 2.01785, 0, 0, 0.0211132,-0.0534621) , 
3, 1.82145, 0, 0, 0.5,0.000446697)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929688,0.188497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537037,0.502131) , 
3, 1.85333, 0, 0, 0.881279,0.0378921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.583267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.521603) , 
2, 3.47284, 0, 0, 0,-0.0420626) , 
3, 1.7941, 0, 0, 0.736641,0.0247698) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952381,0.891303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931915,0.0816279) , 
1, 2.08632, 0, 0, 0.933594,0.0156621) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245098,-0.335135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0355556,-0.186381) , 
3, 1.84275, 0, 0, 0.0742754,-0.0291349) , 
3, 1.90615, 0, 0, 0.346535,-0.0149418) , 
2, 2.34489, 0, 0, 0.5,0.000680454)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.508937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73913,-0.637031) , 
3, 1.93736, 0, 0, 0.978799,0.0035411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685185,0.211902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.51059) , 
3, 1.78814, 0, 0, 0.41573,0.0345578) , 
3, 1.91341, 0, 0, 0.761388,0.0155172) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.508483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.522529) , 
3, 1.96911, 0, 0, 1,0.0152111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361111,0.229956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.120462,-0.207077) , 
0, 0.320216, 1, 0, 0.133956,-0.019213) , 
3, 1.9465, 0, 0, 0.361653,-0.0101623) , 
0, 0.261627, 1, 0, 0.5,-0.00127475)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.50232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909091,0.766889) , 
3, 1.95216, 0, 0, 0.954545,0.0789419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822281,0.0943687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0183908,-0.231228) , 
3, 1.82145, 0, 0, 0.528175,0.00347179) , 
2, 4.82822, 0, 0, 0.535921,0.00484285) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.502293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.804747) , 
3, 1.93938, 0, 0, 0.444444,-0.0687097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,0.652822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.539937) , 
1, 1.54581, 0, 0, 0.0117647,-0.00674855) , 
3, 1.8328, 0, 0, 0.140496,-0.0251833) , 
2, 0.416005, 0, 0, 0.5,0.00211525)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967213,0.152572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609756,0.480674) , 
3, 1.90943, 0, 0, 0.877301,0.0320401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.05,-0.42982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.505531) , 
2, 2.13799, 0, 0, 0.012987,-0.00928034) , 
3, 1.80571, 0, 0, 0.6,0.0187831) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.516481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.762492) , 
1, -0.0328883, 1, 0, 0.95,0.0467707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.502444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201964,-0.102239) , 
3, 1.95392, 0, 0, 0.469216,-0.00627665) , 
0, -0.396603, 1, 0, 0.478022,-0.00530508) , 
1, -1.10574, 1, 0, 0.5,-0.000964866)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.501653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.648055) , 
3, 1.9226, 0, 0, 1,0.0406708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.889922,-0.0535122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107584,0.109481) , 
3, 1.8656, 0, 0, 0.523927,0.00142003) , 
2, 4.72969, 0, 0, 0.533549,0.0022133) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.67505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769231,-0.521694) , 
2, 2.23434, 0, 0, 0.26087,-0.0553556) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.519367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.52986) , 
3, 1.78186, 0, 0, 0,-0.00947279) , 
3, 1.84936, 0, 0, 0.0631579,-0.0205813) , 
0, 1.20196, 1, 0, 0.5,0.000587561)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85,0.315485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62963,-1.27479) , 
0, -0.215957, 1, 0, 0.723404,-0.074541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.859649,0.535997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40625,-0.156511) , 
0, 0.26087, 1, 0, 0.498221,0.00234308) , 
0, -0.0240374, 1, 0, 0.530488,-0.00867384) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730978,-0.0344052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486989,0.328023) , 
2, 2.45972, 0, 0, 0.627943,0.00966505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307692,-0.485547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228137,-0.0298601) , 
2, 1.24199, 0, 0, 0.250681,-0.00984767) , 
2, 1.57334, 0, 0, 0.49004,0.00253241) , 
1, 0.985296, 0, 0, 0.5,-0.000227086)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763214,-0.0938192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412162,0.0602735) , 
0, 0.35566, 1, 0, 0.568075,-0.000435537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,0.0901555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,0.856518) , 
2, 0.900334, 1, 0, 0.30137,0.0161521) , 
2, 0.979773, 0, 0, 0.535921,0.00156429) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484848,-0.511938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0714286,-0.494518) , 
3, 1.84707, 0, 0, 0.361702,-0.0292084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.512752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.502371) , 
1, 1.078, 0, 0, 0,-0.00370382) , 
3, 1.7901, 0, 0, 0.140496,-0.0136106) , 
2, 0.416005, 0, 0, 0.5,0.000185796)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.55519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852459,-0.833807) , 
1, -0.383099, 1, 0, 0.914286,-0.0127417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.506757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393443,0.478113) , 
3, 1.9385, 0, 0, 0.699187,0.0352579) , 
2, 2.35995, 0, 0, 0.798246,0.0131528) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924528,0.381131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609756,-0.0287039) , 
0, 0.33361, 1, 0, 0.717042,0.00773496) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591304,-0.468632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284661,-0.0317864) , 
0, 0.197493, 1, 0, 0.32913,-0.0083523) , 
2, 2.73067, 0, 0, 0.438406,-0.00382047) , 
0, -0.0204712, 1, 0, 0.5,-0.000915143)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.77418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826087,0.0829337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479263,-0.117776) , 
2, 1.47655, 0, 0, 0.74095,0.00378951) , 
1, 2.81803, 0, 0, 0.744134,0.00564001) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.503981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.510401) , 
1, 0.189996, 0, 0, 0,-0.00783021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.504005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.502538) , 
2, 0.318757, 0, 0, 0,-0.0032566) , 
2, 1.69148, 0, 0, 0,-0.0051928) , 
3, 1.77729, 0, 0, 0.5,0.002086)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.527639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791667,0.210584) , 
3, 1.9463, 0, 0, 0.953988,0.0134533) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363636,-1.09135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290323,-0.0288452) , 
0, -0.327708, 1, 0, 0.296296,-0.01246) , 
3, 1.86958, 0, 0, 0.761388,0.00586484) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57971,-0.391323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549091,-0.0228176) , 
1, 0.721156, 0, 0, 0.559322,-0.0116977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282609,1.17187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17233,-0.0146067) , 
1, 1.68231, 0, 0, 0.183406,0.00396299) , 
2, 1.95911, 0, 0, 0.361653,-0.00346282) , 
0, 0.261627, 1, 0, 0.5,-0.000234552)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.505721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500689) , 
2, 2.76029, 0, 0, 1,0.00131828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73913,0.625969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,0.0377506) , 
2, 1.82196, 0, 0, 0.609756,0.0458467) , 
3, 1.93674, 0, 0, 0.841584,0.0193942) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939394,0.532598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.442034) , 
0, 0.73965, 1, 0, 0.884615,0.0144934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463519,0.0471846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430859,-0.0887563) , 
1, 0.288285, 0, 0, 0.444059,-0.00211154) , 
2, 3.888, 0, 0, 0.471974,-0.0010594) , 
0, -0.208537, 1, 0, 0.5,0.000491512)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884615,-0.16061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860465,0.268041) , 
1, 1.58664, 0, 0, 0.873684,0.00357809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.304642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.517735) , 
3, 1.77928, 0, 0, 0.057971,-0.0207439) , 
3, 1.8533, 0, 0, 0.530488,-0.00665495) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703448,0.380468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28125,-0.218065) , 
2, 1.76627, 0, 0, 0.505495,0.012976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717241,-0.16002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331066,0.0981207) , 
2, 2.34489, 0, 0, 0.484268,-0.000785967) , 
1, 0.183874, 0, 0, 0.49004,0.00295608) , 
1, 0.985296, 0, 0, 0.5,0.000589399)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777228,0.0120582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486486,-0.533461) , 
0, 0.358382, 1, 0, 0.732218,-0.0055151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598131,0.315426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.503174) , 
3, 1.77506, 0, 0, 0.31068,0.0186838) , 
0, 0.448466, 1, 0, 0.537079,0.00568707) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694444,0.128692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,-0.0885508) , 
1, 0.699385, 0, 0, 0.645594,0.00152403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344444,-0.475819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214545,-0.0490973) , 
0, 0.685887, 1, 0, 0.246575,-0.009211) , 
0, 0.552842, 1, 0, 0.481398,-0.00289343) , 
1, -0.408727, 1, 0, 0.5,-2.68216e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825397,-0.307527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,0.695303) , 
0, 0.892512, 1, 0, 0.777778,-0.0109601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857143,0.330796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282609,-0.135321) , 
0, 0.82114, 1, 0, 0.751004,0.0133404) , 
1, 0.364751, 0, 0, 0.760814,0.00443642) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59375,-0.107354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3,-0.741988) , 
0, 0.629248, 1, 0, 0.52381,-0.018792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81337,-0.0755269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0625,0.0818071) , 
3, 1.86236, 0, 0, 0.377778,-0.000499055) , 
1, -1.80275, 1, 0, 0.390841,-0.00213548) , 
2, 2.73067, 0, 0, 0.5,-0.000196476)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939759,0.143275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571429,0.386635) , 
3, 1.88349, 0, 0, 0.886598,0.0213494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0833333,0.299502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.554066) , 
1, 2.38962, 0, 0, 0.0227273,-0.0154579) , 
3, 1.82343, 0, 0, 0.617021,0.00986342) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563636,-0.0815515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453526,0.0633618) , 
1, -0.748518, 1, 0, 0.491614,0.00120914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545455,-1.30134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460177,-0.0461921) , 
1, 0.861686, 1, 0, 0.464135,-0.00876884) , 
1, 0.818053, 1, 0, 0.486146,-0.000776401) , 
1, 1.68231, 0, 0, 0.5,0.000349887)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866667,0.572587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.147797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.585538) , 
2, 0.938518, 1, 0, 0.481481,-0.0474975) , 
2, 2.13092, 0, 0, 0.619048,-0.0184964) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531746,0.315896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517123,-0.0187097) , 
1, 0.964284, 1, 0, 0.521531,0.00556846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637097,0.205407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458556,-0.0586308) , 
1, -1.73712, 1, 0, 0.483945,-0.00147688) , 
1, 0.5202, 0, 0, 0.496124,0.000806026) , 
1, 2.37932, 0, 0, 0.5,0.000197391)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.525313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.21141) , 
2, 2.21947, 0, 0, 0.863636,0.00791475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,-0.665928) , 
0, 0.462223, 1, 0, 0.787879,-0.0152698) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866667,0.673124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694836,-0.0516033) , 
1, 2.6202, 0, 0, 0.698777,-0.00232764) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396285,0.182442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170807,-0.0786114) , 
0, 0.795762, 1, 0, 0.283721,0.00343574) , 
0, 0.449693, 1, 0, 0.492687,0.000534086) , 
1, -2.49976, 1, 0, 0.5,0.000142547)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809339,0.127112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,-0.614092) , 
0, 0.0187051, 1, 0, 0.794224,0.00119219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.742749) , 
3, 1.91795, 0, 0, 0.793103,0.0458257) , 
0, 0.0459939, 1, 0, 0.794118,0.00542216) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589286,-0.0141549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318584,-0.399758) , 
0, 0.561856, 1, 0, 0.539708,-0.00549873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711864,0.237814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0206186,-0.116306) , 
3, 1.87394, 0, 0, 0.220049,0.00465432) , 
0, 0.678201, 1, 0, 0.412281,-0.00145136) , 
0, 0.0735617, 1, 0, 0.5,0.000127689)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939252,0.173126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168605,-0.120698) , 
3, 1.88835, 0, 0, 0.595855,0.00132576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,1.96747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146341,-0.205653) , 
1, -0.733426, 0, 0, 0.152542,0.0306347) , 
0, 1.01193, 1, 0, 0.537079,0.00521166) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772152,-0.316068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549669,0.0413278) , 
0, -0.161275, 1, 0, 0.575403,0.000184639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181818,-0.0948871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.131148,-0.632528) , 
1, 0.10936, 0, 0, 0.166667,-0.0118939) , 
0, 0.832206, 1, 0, 0.481398,-0.00259328) , 
1, -0.408727, 1, 0, 0.5,1.42235e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945887,-0.0146248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268085,0.116304) , 
3, 1.88009, 0, 0, 0.71736,0.00356517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409836,-0.277808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297727,-0.0166733) , 
2, 1.62833, 0, 0, 0.311377,-0.00324875) , 
2, 1.78682, 0, 0, 0.547579,0.000715607) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4375,-0.77768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.519709) , 
3, 1.80681, 0, 0, 0.194444,-0.0518711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0454545,-0.243426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.512183) , 
1, -0.30553, 0, 0, 0.0306122,-0.00297947) , 
2, 2.34423, 0, 0, 0.0746269,-0.0161145) , 
0, 1.10792, 1, 0, 0.5,-0.000977514)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.878788,0.510292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,-0.255638) , 
1, 0.258344, 1, 0, 0.866667,-0.000733026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777778,0.749749) , 
2, 1.67713, 0, 0, 0.84127,0.0191026) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.569102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.51139) , 
0, 1.02225, 0, 0, 1,0.00415133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918919,0.222757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176545,-0.0674652) , 
3, 1.93061, 0, 0, 0.209639,-0.00378909) , 
3, 1.95392, 0, 0, 0.483058,-0.00104217) , 
0, -0.30257, 1, 0, 0.5,-8.93757e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.99591,0.127397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714286,-0.0947858) , 
3, 1.93313, 0, 0, 0.963768,-0.00139744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,0.211308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14239,0.0112326) , 
3, 1.88856, 0, 0, 0.177542,0.00410814) , 
3, 1.90976, 0, 0, 0.535921,0.00159858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.622798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.506103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0989011,-0.250863) , 
1, -1.44249, 1, 0, 0.106796,-0.00185228) , 
0, 0.0544467, 1, 0, 0.140496,-0.00623229) , 
2, 0.416005, 0, 0, 0.5,0.000887218)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974138,-0.130356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709677,0.689835) , 
3, 1.91899, 0, 0, 0.918367,0.0136058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.838153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0481928,-0.544184) , 
2, 3.05509, 0, 0, 0.0967742,-0.00935658) , 
3, 1.84703, 0, 0, 0.6,0.00470788) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.969767,0.0480151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487179,-0.107889) , 
3, 1.9161, 0, 0, 0.866545,-0.00391858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0967742,-0.515351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0875486,0.0691985) , 
1, -0.871798, 1, 0, 0.0880734,0.00161317) , 
3, 1.8656, 0, 0, 0.478022,-0.00115777) , 
1, -1.10574, 1, 0, 0.5,-0.000100897)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.698065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793103,-0.236259) , 
2, 3.12665, 0, 0, 0.866667,0.00137835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777778,0.570659) , 
2, 1.67713, 0, 0, 0.84127,0.00955329) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595838,-0.00230094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361111,0.973304) , 
0, 0.750773, 1, 0, 0.586934,0.00114813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.441187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.00171753) , 
2, 3.011, 0, 0, 0.175,-0.00447341) , 
0, 0.803618, 1, 0, 0.483058,-0.000269436) , 
0, -0.30257, 1, 0, 0.5,0.000195152)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.515847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.661762) , 
3, 1.92447, 0, 0, 0.868421,-0.0194085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761905,-0.361107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678105,0.0820296) , 
1, 2.0436, 0, 0, 0.683486,0.00361068) , 
1, -2.10546, 1, 0, 0.693642,0.00234662) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,-0.127495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,0.46001) , 
0, -0.163163, 1, 0, 0.651163,0.010665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561947,-0.118822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00914634,-0.0454615) , 
3, 1.81856, 0, 0, 0.234657,-0.00485037) , 
0, -0.00588528, 1, 0, 0.290625,-0.00276549) , 
2, 1.95911, 0, 0, 0.5,-0.000109649)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939759,0.174069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571429,0.299806) , 
3, 1.88349, 0, 0, 0.886598,0.0159678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0588235,-0.399393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.513969) , 
2, 1.08765, 1, 0, 0.0227273,-0.00893559) , 
3, 1.82343, 0, 0, 0.617021,0.0081965) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932624,0.245587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127389,-0.0728662) , 
3, 1.88835, 0, 0, 0.508389,0.00223777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672355,-0.178248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261589,0.0536585) , 
0, 0.462488, 1, 0, 0.463866,-0.00394078) , 
1, -0.0447773, 1, 0, 0.486146,-0.000848914) , 
1, 1.68231, 0, 0, 0.5,0.000108596)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.951009,0.12872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.884146,-0.192086) , 
0, 0.297257, 1, 0, 0.92955,-0.00118788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554455,0.152688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.515804) , 
3, 1.78975, 0, 0, 0.197183,0.00825911) , 
3, 1.8656, 0, 0, 0.667925,0.00218689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,0.572005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256906,-0.0167641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233129,-0.244309) , 
1, -0.371891, 0, 0, 0.249524,-0.00392957) , 
1, -2.35488, 1, 0, 0.251397,-0.00310375) , 
0, 0.543726, 1, 0, 0.5,5.39522e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.800525,-0.0840354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.785121) , 
0, 0.225359, 1, 0, 0.797531,-0.00203583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,-0.647631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,0.450378) , 
3, 1.8328, 0, 0, 0.5,-0.0196844) , 
2, 0.79467, 0, 0, 0.761388,-0.00417969) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550562,0.219961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497674,-0.0259892) , 
1, 0.280671, 0, 0, 0.521628,0.00594127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.315727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222749,0.0231553) , 
0, 0.652796, 1, 0, 0.230126,-0.00120563) , 
0, 0.611176, 1, 0, 0.361653,0.00201909) , 
0, 0.261627, 1, 0, 0.5,-0.000126286)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.511195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.321514) , 
3, 1.92079, 0, 0, 0.76,-0.0146622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560976,0.19955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272727,-0.24303) , 
0, 0.591927, 1, 0, 0.389163,6.3169e-05) , 
0, 0.333926, 1, 0, 0.530488,-0.00554865) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833037,0.0202207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244681,0.118978) , 
3, 1.84163, 0, 0, 0.748858,0.00333895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.509903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.504017) , 
2, 3.32336, 0, 0, 0,-0.0013949) , 
3, 1.78193, 0, 0, 0.49004,0.00170284) , 
1, 0.985296, 0, 0, 0.5,-8.28073e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.502108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486842,0.216404) , 
3, 1.96599, 0, 0, 0.778409,0.0095613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940476,0.295383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664062,-0.176451) , 
2, 2.5974, 0, 0, 0.773585,-0.00150014) , 
1, 0.0890321, 0, 0, 0.775773,0.00351742) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806452,0.385147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.883501) , 
0, 0.195096, 0, 0, 0.693878,-0.0180653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936455,0.131306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0855705,-0.075076) , 
3, 1.90302, 0, 0, 0.369832,-0.000623517) , 
0, 0.231095, 1, 0, 0.386653,-0.00152887) , 
0, 0.167595, 1, 0, 0.5,-5.8925e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.941176,0.484237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.87156,0.0858464) , 
2, 3.76349, 1, 0, 0.880952,0.00609904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.842105,0.340727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,-1.5223) , 
2, 3.56282, 1, 0, 0.735294,-0.0466023) , 
2, 3.63634, 0, 0, 0.85,-0.0051) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689769,-0.0119422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,-0.410093) , 
2, 2.52207, 0, 0, 0.687307,-0.00362246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638889,0.443174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337194,-0.00195389) , 
2, 2.26056, 0, 0, 0.36278,0.00243323) , 
2, 2.47061, 0, 0, 0.452218,0.000764302) , 
2, 3.50222, 0, 0, 0.5,5.98814e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87619,0.154394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791667,-0.34255) , 
1, -0.684135, 1, 0, 0.860465,-0.00172913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361702,0.244279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.500828) , 
3, 1.77492, 0, 0, 0.0909091,0.00848191) , 
3, 1.84703, 0, 0, 0.537079,0.0025618) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.934426,-0.112136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.839695,0.112003) , 
2, 2.85641, 0, 0, 0.878652,0.00236903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328947,-0.157908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0300546,-0.0832974) , 
3, 1.82753, 0, 0, 0.081448,-0.00477608) , 
3, 1.8656, 0, 0, 0.481398,-0.00119144) , 
1, -0.408727, 1, 0, 0.5,6.2458e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980469,0.0302101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483221,0.120093) , 
3, 1.91341, 0, 0, 0.797531,0.0040324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962963,0.451636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0689655,-0.452997) , 
3, 1.9182, 0, 0, 0.5,-0.0086465) , 
2, 0.79467, 0, 0, 0.761388,0.00249223) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703704,-0.354126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464286,0.58504) , 
2, 2.0311, 0, 0, 0.581818,0.0121272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544118,-0.311819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328877,-0.0206389) , 
0, 0.376065, 1, 0, 0.346814,-0.00222775) , 
0, 0.320216, 1, 0, 0.361653,-0.0013213) , 
0, 0.261627, 1, 0, 0.5,-1.45064e-06)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818182,0.663016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885321,0.161409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3,-0.368928) , 
0, 0.848696, 1, 0, 0.814516,0.00202221) , 
1, 2.34054, 0, 0, 0.814672,0.00453747) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.931818,0.91869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465116,-0.245246) , 
0, 0.456687, 1, 0, 0.701149,0.00669748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,-0.109686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220729,0.0672822) , 
0, 0.449693, 1, 0, 0.399594,-0.0016512) , 
2, 2.87659, 0, 0, 0.424045,-0.000974279) , 
2, 3.11644, 0, 0, 0.5,9.74507e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.50164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.59921) , 
2, 3.51314, 0, 0, 1,0.0110999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671642,-0.165158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310345,-0.332634) , 
0, 0.593188, 1, 0, 0.5625,-0.00747594) , 
2, 3.18998, 0, 0, 0.641026,-0.00414182) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,-0.764442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546185,-0.0440165) , 
2, 4.12514, 0, 0, 0.559387,-0.00337162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480418,0.157048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457093,-0.0268313) , 
1, 0.0702516, 0, 0, 0.466457,0.00201881) , 
1, 1.22098, 0, 0, 0.48642,0.000860865) , 
1, -1.80275, 1, 0, 0.5,0.00042144)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926641,-0.00928766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.323618) , 
0, 0.890682, 1, 0, 0.905263,0.00211799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275,-0.190029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.505311) , 
3, 1.7897, 0, 0, 0.0866142,-0.00730583) , 
3, 1.8656, 0, 0, 0.519481,-0.00232292) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851351,-0.201022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684211,0.160251) , 
0, -0.168833, 1, 0, 0.720588,0.00459396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509259,-0.258326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249275,0.090259) , 
0, 0.517939, 1, 0, 0.311258,-0.000808092) , 
0, 0.355502, 1, 0, 0.486759,0.00150805) , 
1, 0.288285, 0, 0, 0.5,-4.21701e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933185,-0.0669164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231818,0.111187) , 
3, 1.86958, 0, 0, 0.702541,0.000867614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,1.04294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474138,0.0731429) , 
0, 0.534112, 0, 0, 0.484127,0.01104) , 
0, 0.444987, 1, 0, 0.667925,0.00247983) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319261,-0.09874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1,-0.724602) , 
0, 1.05723, 1, 0, 0.313625,-0.00595255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230769,0.600344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0740741,-0.154613) , 
0, 1.10467, 1, 0, 0.0878378,0.00159046) , 
0, 1.08317, 1, 0, 0.251397,-0.00387365) , 
0, 0.543726, 1, 0, 0.5,-8.15937e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.412466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,-0.765373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576271,0.155722) , 
0, 0.0526581, 1, 0, 0.607692,0.00287511) , 
0, -0.1139, 1, 0, 0.617021,0.00519865) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897778,0.153379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.862534,-0.0408984) , 
1, 0.205913, 0, 0, 0.875839,0.00141225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.104077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0306122,-0.0269686) , 
3, 1.82758, 0, 0, 0.0957983,-0.00246319) , 
3, 1.8656, 0, 0, 0.486146,-0.000523842) , 
1, 1.68231, 0, 0, 0.5,8.19169e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.556519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84,-0.310249) , 
2, 3.13256, 0, 0, 0.902439,-0.000382774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0610031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.652204) , 
1, -0.0835793, 0, 0, 0.727273,0.0242192) , 
2, 1.94622, 0, 0, 0.84127,0.00820838) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.920844,0.0994267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0854701,-0.246889) , 
3, 1.83706, 0, 0, 0.72379,0.0016976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387524,-0.0897305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20082,0.181702) , 
2, 0.928157, 0, 0, 0.32859,-0.00176247) , 
2, 2.34489, 0, 0, 0.483058,-0.000410072) , 
0, -0.30257, 1, 0, 0.5,-2.44215e-06)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66881,0.0824598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307692,1.64439) , 
0, 0.667217, 1, 0, 0.654321,0.00516372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26,-0.531156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197183,0.162481) , 
0, 0.914098, 1, 0, 0.22314,-0.0043871) , 
0, 0.730196, 1, 0, 0.537079,0.00256675) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.934343,-0.0200267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.190018) , 
3, 1.89087, 0, 0, 0.878652,-0.00385613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320755,0.109919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00595238,-0.387797) , 
3, 1.80861, 0, 0, 0.081448,0.0015711) , 
3, 1.8656, 0, 0, 0.481398,-0.0011517) , 
1, -0.408727, 1, 0, 0.5,9.05786e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.878788,0.316697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651206,-0.0272431) , 
2, 3.61461, 0, 0, 0.695976,0.00019856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.309077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366197,-0.00195594) , 
2, 1.89246, 0, 0, 0.397849,0.00523887) , 
2, 2.01938, 0, 0, 0.631272,0.00129249) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464286,0.497805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283582,-0.25262) , 
2, 1.50995, 0, 0, 0.305677,-0.00625582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304054,-0.128064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102041,0.244264) , 
0, 0.726755, 1, 0, 0.223577,0.000392334) , 
2, 0.911392, 0, 0, 0.263158,-0.00281278) , 
2, 1.57334, 0, 0, 0.5,-0.000171476)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857143,0.32623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,-0.581519) , 
2, 2.35747, 0, 0, 0.780822,-0.00272888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789474,0.374978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306122,0.308179) , 
0, 0.154293, 1, 0, 0.441176,0.0129704) , 
2, 1.98967, 0, 0, 0.617021,0.00484242) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581395,0.223332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43662,-0.668614) , 
1, 1.41421, 1, 0, 0.491228,-0.00674783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803459,-0.0290373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0272109,0.225005) , 
3, 1.82576, 0, 0, 0.485608,0.000182111) , 
1, 1.24947, 0, 0, 0.486146,-0.000481208) , 
1, 1.68231, 0, 0, 0.5,8.2329e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.997976,0.27372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716981,-0.12667) , 
3, 1.93923, 0, 0, 0.97075,-0.000776927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567308,0.154401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.25803) , 
3, 1.88001, 0, 0, 0.522059,0.0086594) , 
3, 1.9161, 0, 0, 0.881406,0.00110205) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595238,0.0837482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126761,-0.346129) , 
2, 1.7996, 0, 0, 0.380645,-0.00775988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204082,-0.465951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00576369,0.626606) , 
2, 2.01785, 0, 0, 0.0101215,0.000207154) , 
3, 1.80867, 0, 0, 0.0986133,-0.0016956) , 
3, 1.8656, 0, 0, 0.5,-0.000261072)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.598329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.995192,-0.187401) , 
0, 0.800717, 0, 0, 0.995652,0.000687571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784314,-0.453895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267857,-0.0259298) , 
0, 0.269739, 1, 0, 0.429448,-0.00918546) , 
3, 1.92304, 0, 0, 0.760814,-0.00340735) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808153,0.0929685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320513,-0.16178) , 
0, 0.864006, 1, 0, 0.731313,0.00335234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148148,-0.238389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00239808,-0.169942) , 
3, 1.80179, 0, 0, 0.0112613,-0.0017618) , 
3, 1.81856, 0, 0, 0.390841,0.000934155) , 
2, 2.73067, 0, 0, 0.5,-0.000346785)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.636857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.965517,-0.514469) , 
2, 2.05551, 0, 0, 0.987552,0.000116436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731707,0.156535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461538,-0.270928) , 
3, 1.809, 0, 0, 0.428571,0.00782554) , 
3, 1.91341, 0, 0, 0.775773,0.00303715) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806452,0.0946676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.538332) , 
0, 0.195096, 0, 0, 0.693878,-0.0106522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581818,0.217124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355952,-0.0350425) , 
0, 0.292016, 1, 0, 0.369832,-0.000613779) , 
0, 0.231095, 1, 0, 0.386653,-0.00113484) , 
0, 0.167595, 1, 0, 0.5,8.04224e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.535139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.928571,-0.305242) , 
0, 0.339578, 1, 0, 0.96,0.00332386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117647,-0.383128) , 
3, 1.9049, 0, 0, 0.619048,-0.00875502) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874804,-0.0385803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0343643,0.175297) , 
3, 1.82145, 0, 0, 0.611828,-0.000491817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449367,0.1365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.508943) , 
3, 1.80714, 0, 0, 0.197222,0.0025531) , 
0, 0.731792, 1, 0, 0.496124,0.000357927) , 
1, 2.37932, 0, 0, 0.5,7.05816e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905172,-0.00705038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793103,-0.358372) , 
1, 1.01162, 1, 0, 0.882759,-0.00354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829032,0.128861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400844,-0.0568287) , 
0, 0.551793, 1, 0, 0.64351,0.00209325) , 
0, -0.021085, 1, 0, 0.693642,0.000912871) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681818,0.502454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640625,0.0447454) , 
0, -0.097093, 0, 0, 0.651163,0.00616702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561947,-0.0974269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00914634,-0.0268817) , 
3, 1.81856, 0, 0, 0.234657,-0.00230929) , 
0, -0.00588528, 1, 0, 0.290625,-0.00117028) , 
2, 1.95911, 0, 0, 0.5,-8.80441e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.996324,-0.113338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.8125,-0.268) , 
3, 1.93313, 0, 0, 0.976974,-0.00233855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.995708,0.184396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59375,0.211006) , 
3, 1.93342, 0, 0, 0.94717,0.00519766) , 
2, 2.44202, 0, 0, 0.963093,0.00117128) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545455,0.251085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.538224) , 
0, -0.299466, 1, 0, 0.473684,-0.0110045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454545,0.304285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117474,-0.0303995) , 
0, -0.0278774, 1, 0, 0.137931,-0.000222045) , 
0, -0.192128, 1, 0, 0.154653,-0.000759049) , 
3, 1.90976, 0, 0, 0.5,6.55452e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473684,-0.383562) , 
3, 1.95568, 0, 0, 0.791667,-0.00630716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756757,0.588678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615285,0.0270072) , 
1, -1.72185, 1, 0, 0.621755,0.00161515) , 
1, -2.10546, 1, 0, 0.631272,0.00117142) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411765,-0.00751964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3125,-0.486538) , 
2, 1.49574, 0, 0, 0.363636,-0.00979842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286624,-0.241863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222222,0.0923411) , 
2, 0.934968, 0, 0, 0.246944,-0.000884114) , 
2, 1.40728, 0, 0, 0.263158,-0.00212273) , 
2, 1.57334, 0, 0, 0.5,-3.29463e-06)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.484449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633333,0.145385) , 
1, 1.89222, 0, 0, 0.658537,0.0103615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837838,0.30803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460317,-0.225871) , 
0, 0.305468, 1, 0, 0.6,0.00127788) , 
1, 1.95066, 1, 0, 0.617021,0.00391921) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.970492,0.154798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947644,-0.0900557) , 
1, -0.531573, 0, 0, 0.961694,0.0009836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419811,-0.0687114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0269151,0.111179) , 
3, 1.8255, 0, 0, 0.146763,-0.00141913) , 
3, 1.90976, 0, 0, 0.486146,-0.000418499) , 
1, 1.68231, 0, 0, 0.5,4.06738e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981481,0.21243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325581,-0.37552) , 
3, 1.87266, 0, 0, 0.794702,-0.00369135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665996,0.0251379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659091,0.407904) , 
1, -0.649903, 0, 0, 0.665434,0.00245659) , 
1, -0.974812, 1, 0, 0.693642,0.00111506) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461538,-0.225459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298343,0.154709) , 
2, 1.76176, 0, 0, 0.318841,0.00239069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329949,0.0205771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233051,-0.248729) , 
1, 0.695956, 0, 0, 0.277136,-0.00270532) , 
1, -0.408727, 1, 0, 0.290625,-0.00105708) , 
2, 1.95911, 0, 0, 0.5,7.13892e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8,0.422652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609756,-0.131063) , 
1, 2.7807, 0, 0, 0.62069,-0.00290058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272727,0.705075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160714,-0.0442587) , 
1, 1.11288, 1, 0, 0.179104,0.00437952) , 
0, 0.870871, 1, 0, 0.530488,-0.00141348) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.931298,0.350223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112676,-0.0635207) , 
3, 1.87094, 0, 0, 0.505495,0.00344938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580357,0.0165703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169591,-0.201449) , 
0, 0.825578, 1, 0, 0.484268,-0.000641913) , 
1, 0.183874, 0, 0, 0.49004,0.00047056) , 
1, 0.985296, 0, 0, 0.5,6.62107e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.96648,0.115079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926829,-0.422021) , 
1, 1.21953, 1, 0, 0.959091,-0.000149366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769231,0.27265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0425532,-0.399929) , 
3, 1.81261, 0, 0, 0.372093,0.00612272) , 
3, 1.86958, 0, 0, 0.794118,0.00161338) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.501784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.404759) , 
3, 1.93467, 0, 0, 0.87037,0.00552693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441212,-0.0359787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0816327,0.253281) , 
0, 1.08113, 1, 0, 0.386831,-0.000620333) , 
2, 3.888, 0, 0, 0.412281,-0.000296793) , 
0, 0.0735617, 1, 0, 0.5,0.000142029)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913907,-0.0756292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0729927,0.151212) , 
3, 1.82576, 0, 0, 0.718644,-0.000862658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450739,0.0964385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121212,-0.533318) , 
0, 0.78104, 1, 0, 0.425968,0.00226183) , 
0, 0.384934, 1, 0, 0.59378,0.000470335) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.555431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.647755) , 
3, 1.90473, 0, 0, 0.4,-0.0146066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186047,0.123853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769231,-0.33591) , 
2, 1.13953, 0, 0, 0.148289,0.000532007) , 
2, 3.011, 0, 0, 0.181518,-0.00146648) , 
0, 0.825825, 1, 0, 0.5,2.97528e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93787,0.15124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0895522,-0.221941) , 
3, 1.82576, 0, 0, 0.797531,0.00175904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962963,0.248894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0689655,-0.40419) , 
3, 1.9182, 0, 0, 0.5,-0.00625042) , 
2, 0.79467, 0, 0, 0.761388,0.000786093) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785714,0.382415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512195,-0.194492) , 
1, -0.61091, 1, 0, 0.581818,-0.00689767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61244,-0.0752896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255354,0.0156709) , 
2, 2.73067, 0, 0, 0.346814,-0.000369465) , 
0, 0.320216, 1, 0, 0.361653,-0.000781694) , 
0, 0.261627, 1, 0, 0.5,-0.000239089)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765957,0.118586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721429,-0.0674917) , 
1, 0.155834, 0, 0, 0.741748,0.000654077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544218,-0.206004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367052,0.00779126) , 
2, 2.0401, 0, 0, 0.419878,-0.0014392) , 
2, 2.38229, 0, 0, 0.584325,-0.000369717) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628319,0.0208751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,0.392834) , 
3, 1.84639, 0, 0, 0.580153,0.00466787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0416667,-0.270023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.502429) , 
3, 1.78439, 0, 0, 0.00518135,-0.00130669) , 
3, 1.81856, 0, 0, 0.237654,0.00110895) , 
2, 1.18756, 0, 0, 0.5,-1.00417e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.504941) , 
3, 1.92064, 0, 0, 1,0.000413328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785714,-0.275782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.501122) , 
3, 1.76635, 0, 0, 0.407407,-0.0112634) , 
3, 1.86534, 0, 0, 0.841584,-0.00270817) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.823232,0.0872247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395437,-0.0715593) , 
2, 1.81531, 0, 0, 0.652504,0.000910288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291188,-0.17617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241158,0.049204) , 
1, 0.157103, 0, 0, 0.263986,-0.000719153) , 
0, 0.517492, 1, 0, 0.471974,0.000153147) , 
0, -0.208537, 1, 0, 0.5,-6.38141e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.31114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630435,-0.0535855) , 
1, 1.95066, 1, 0, 0.648855,0.00169141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,0.503586) , 
2, 0.430663, 0, 0, 0.617021,0.0026072) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932624,0.125445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127389,-0.0416126) , 
3, 1.88835, 0, 0, 0.508389,0.000575765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472727,-0.027262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355556,-0.530872) , 
1, 1.51659, 1, 0, 0.463866,-0.00122072) , 
1, -0.0447773, 1, 0, 0.486146,-0.000321725) , 
1, 1.68231, 0, 0, 0.5,-1.16817e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.538077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.995272,-0.0751256) , 
2, 1.41639, 1, 0, 0.99604,0.00029667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769231,0.166475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657895,-0.198633) , 
1, 0.107521, 0, 0, 0.703125,-0.0125318) , 
3, 1.93313, 0, 0, 0.963093,-0.00114625) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733333,-0.450127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304348,0.131294) , 
3, 1.84675, 0, 0, 0.473684,-0.00585316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432099,0.0667326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.053286,-0.00390372) , 
3, 1.84595, 0, 0, 0.137931,0.00117837) , 
0, -0.192128, 1, 0, 0.154653,0.000828179) , 
3, 1.90976, 0, 0, 0.5,-1.52525e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731563,0.0178003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314928,-0.0392154) , 
2, 1.78682, 0, 0, 0.556984,-3.1379e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,0.317438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0851064,-0.466621) , 
1, -0.445794, 1, 0, 0.142857,0.0033407) , 
0, 1.03671, 1, 0, 0.533549,0.000159442) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.0165162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111111,-0.509799) , 
1, 0.34049, 0, 0, 0.181818,-0.00512784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.500064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.500346) , 
1, -0.531569, 0, 0, 0,-3.5607e-05) , 
3, 1.77158, 0, 0, 0.0631579,-0.00180449) , 
0, 1.20196, 1, 0, 0.5,1.9372e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948235,-0.0308189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.811159,0.0817336) , 
0, 0.426597, 1, 0, 0.899696,0.000689782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.387128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405594,-0.117649) , 
3, 1.827, 1, 0, 0.411765,-0.00519436) , 
3, 1.87646, 0, 0, 0.807645,-0.000420297) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.00111665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,0.806298) , 
3, 1.7939, 0, 0, 0.15493,0.0058758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.51321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.501731) , 
3, 1.77176, 0, 0, 0,-0.000296019) , 
3, 1.78746, 0, 0, 0.0211132,0.000545054) , 
3, 1.82145, 0, 0, 0.5,-4.27086e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.520445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977778,-0.298314) , 
1, 1.39152, 0, 0, 0.981132,-3.99061e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459459,0.350155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0959996) , 
1, 1.03625, 1, 0, 0.408163,0.00733098) , 
3, 1.88195, 0, 0, 0.8,0.00229025) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.902778,-0.257833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616129,0.0774987) , 
0, 0.262138, 1, 0, 0.707048,0.000511595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359026,-0.0709313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191304,0.101518) , 
2, 0.928157, 0, 0, 0.305671,-0.000771148) , 
2, 2.34489, 0, 0, 0.460493,-0.00027636) , 
0, -0.114504, 1, 0, 0.5,2.23065e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.510677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73913,-0.126521) , 
3, 1.93736, 0, 0, 0.978799,5.31925e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658824,0.221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193548,-0.0260245) , 
2, 1.90587, 0, 0, 0.41573,0.00383226) , 
3, 1.91341, 0, 0, 0.761388,0.00151236) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550562,0.159648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241758,-0.257216) , 
0, 0.611176, 1, 0, 0.394444,0.000619309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.0877407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220339,-0.0106298) , 
0, 0.611796, 1, 0, 0.338552,-0.00166418) , 
1, 0.288285, 0, 0, 0.361653,-0.000720376) , 
0, 0.261627, 1, 0, 0.5,5.23643e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73224,0.00917238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527473,-0.143169) , 
2, 2.28466, 0, 0, 0.703125,-0.00031427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362812,0.0160564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241379,0.567936) , 
2, 0.924932, 0, 0, 0.355319,0.00131794) , 
2, 2.0883, 0, 0, 0.555856,0.000376847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.429925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545455,0.475141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193878,-0.159648) , 
1, 2.15248, 0, 0, 0.21256,-0.000853024) , 
1, -2.06278, 1, 0, 0.220721,-0.00154992) , 
2, 0.801782, 0, 0, 0.5,5.57198e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.501522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.49901) , 
3, 1.87747, 0, 0, 0.861538,0.0046685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615385,-0.5213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493827,0.0997801) , 
2, 2.66647, 0, 0, 0.502857,0.000149077) , 
2, 2.88848, 0, 0, 0.6,0.00137309) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741071,-0.0216246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,-0.489952) , 
2, 2.67333, 0, 0, 0.72,-0.00213113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644068,0.249953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325228,-0.00308636) , 
2, 2.29547, 0, 0, 0.351464,0.000675373) , 
2, 2.50807, 0, 0, 0.478022,-0.000288398) , 
1, -1.10574, 1, 0, 0.5,1.09683e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790566,0.0223673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655172,0.215966) , 
2, 2.06991, 0, 0, 0.777211,0.00120119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.223185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329923,0.010148) , 
2, 1.70594, 0, 0, 0.349206,-0.000558718) , 
2, 1.86237, 0, 0, 0.59378,0.000446944) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52,0.187898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.577133) , 
3, 1.8434, 0, 0, 0.18705,0.00100633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27451,-0.379839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132743,0.0202558) , 
2, 2.35638, 0, 0, 0.176829,-0.00386712) , 
1, 0.147059, 0, 0, 0.181518,-0.00163145) , 
0, 0.825825, 1, 0, 0.5,-2.58432e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795009,0.0459065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.171185) , 
0, 0.583537, 1, 0, 0.705234,-1.70291e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,0.210123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117647,-0.182612) , 
0, 1.13491, 1, 0, 0.221374,0.00289465) , 
0, 0.919858, 1, 0, 0.631272,0.000428047) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.57113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302419,-0.051193) , 
2, 0.831555, 1, 0, 0.305147,-0.00206547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317073,0.304199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179012,-0.282642) , 
2, 0.616098, 0, 0, 0.206897,0.000379319) , 
2, 0.746095, 0, 0, 0.263158,-0.00102065) , 
2, 1.57334, 0, 0, 0.5,-8.85672e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86,0.0574381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553571,-0.463228) , 
0, 0.250846, 1, 0, 0.698113,-0.00330769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918182,-0.251489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614853,0.0139922) , 
2, 3.48106, 0, 0, 0.66328,-9.63136e-05) , 
1, 1.54935, 0, 0, 0.667925,-0.000524498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.40056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533333,-0.128306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198257,0.0549953) , 
2, 3.03013, 0, 0, 0.236994,0.000296262) , 
2, 3.888, 0, 0, 0.251397,0.000548417) , 
0, 0.543726, 1, 0, 0.5,-9.19487e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988439,0.14111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,-0.233343) , 
3, 1.90833, 0, 0, 0.958974,-0.000310934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741935,0.291012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.030303,-0.499595) , 
3, 1.80678, 0, 0, 0.375,0.00628125) , 
3, 1.88072, 0, 0, 0.814672,0.00131802) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614458,0.232457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32,-0.171372) , 
2, 1.03654, 0, 0, 0.546296,0.00197952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.509779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153274,-0.0426893) , 
3, 1.94995, 0, 0, 0.410363,-0.000646704) , 
1, 1.68231, 0, 0, 0.424045,-0.000382368) , 
2, 3.11644, 0, 0, 0.5,-5.17364e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614017,0.000914534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,0.348639) , 
0, 0.72411, 1, 0, 0.590649,0.000374005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,0.432974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.418505) , 
1, 0.789278, 0, 0, 0.192982,-0.00229243) , 
0, 0.85208, 1, 0, 0.570136,0.00023646) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.52537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157895,-0.360003) , 
3, 1.92625, 0, 0, 0.666667,-0.00551305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114286,0.320763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.532692) , 
3, 1.82829, 0, 0, 0.0223464,0.000600338) , 
3, 1.88516, 0, 0, 0.15859,-0.00069236) , 
0, 0.919858, 1, 0, 0.5,7.81699e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930348,0.25012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57971,-0.125561) , 
0, 0.437954, 1, 0, 0.787611,0.00019365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782609,-0.355725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451613,0.0863446) , 
0, 0.376083, 1, 0, 0.592593,-0.00685647) , 
2, 2.89852, 0, 0, 0.760814,-0.000775069) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684211,0.316457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659259,0.0252613) , 
2, 2.68594, 0, 0, 0.662338,0.00236698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577181,0.0729044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190965,-0.0880191) , 
0, 0.35566, 1, 0, 0.33758,-0.00011651) , 
2, 2.28672, 0, 0, 0.390841,0.000290794) , 
2, 2.73067, 0, 0, 0.5,-2.36837e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500259) , 
0, 0.103956, 0, 0, 1,4.28014e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595745,0.181569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460317,-0.126454) , 
1, -0.910444, 1, 0, 0.49711,-0.00278712) , 
3, 1.95723, 0, 0, 0.775773,-0.00121899) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.99278,0.0535663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452055,0.0877257) , 
3, 1.93476, 0, 0, 0.806147,0.00224751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.107446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0132743,-0.0317345) , 
3, 1.82221, 0, 0, 0.0460653,-0.000884407) , 
3, 1.85953, 0, 0, 0.386653,0.000518984) , 
0, 0.167595, 1, 0, 0.5,1.27259e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.96745,-0.0098368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634921,0.112315) , 
3, 1.91516, 0, 0, 0.933442,0.000573271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785714,0.302104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301887,-0.266528) , 
2, 2.9655, 0, 0, 0.402985,-0.0106011) , 
3, 1.89087, 0, 0, 0.881406,-0.000522899) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69697,0.195896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133333,-0.175654) , 
0, 0.47029, 1, 0, 0.428571,0.00447141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297297,0.194394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0473588,-0.0139279) , 
0, -0.0947295, 1, 0, 0.0631399,0.000133681) , 
3, 1.8465, 0, 0, 0.0986133,0.000554755) , 
3, 1.8656, 0, 0, 0.5,2.17373e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735632,-0.0867721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388889,-0.46855) , 
0, 0.403067, 1, 0, 0.713262,-0.00202858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906897,-0.0443232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122642,0.165294) , 
3, 1.83714, 0, 0, 0.69697,0.000325706) , 
1, -0.212385, 1, 0, 0.703704,-0.000647398) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72973,0.116695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.464896) , 
2, 3.63707, 0, 0, 0.653846,-0.00396067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720588,0.118921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0249377,-0.026863) , 
3, 1.85953, 0, 0, 0.259504,0.00103788) , 
2, 3.50222, 0, 0, 0.290715,0.000642258) , 
0, 0.449693, 1, 0, 0.5,-1.1284e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.494874) , 
3, 1.87747, 0, 0, 0.861538,0.00319766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515625,-0.208019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495495,0.188852) , 
1, -2.00359, 1, 0, 0.502857,0.000121443) , 
2, 2.88848, 0, 0, 0.6,0.000954585) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541667,0.337163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467532,-0.215596) , 
1, -0.782285, 0, 0, 0.485149,-0.00232998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485981,-0.0258464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422222,0.0900692) , 
1, -0.320694, 0, 0, 0.477296,-6.7365e-05) , 
1, -0.706392, 1, 0, 0.478022,-0.000276637) , 
1, -1.10574, 1, 0, 0.5,-5.47948e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866667,-0.249141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.767442,0.252796) , 
2, 1.94444, 0, 0, 0.830508,-0.00105292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.901079,0.0682348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408759,-0.0283792) , 
3, 1.87646, 0, 0, 0.803752,0.000603696) , 
1, 1.54935, 0, 0, 0.807645,0.00036266) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.132948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,0.332341) , 
3, 1.7939, 0, 0, 0.15493,-0.00270142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.503716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.500625) , 
3, 1.77176, 0, 0, 0,-8.97135e-05) , 
3, 1.78746, 0, 0, 0.0211132,-0.000445628) , 
3, 1.82145, 0, 0, 0.5,4.6505e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825397,-0.0180749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.566105) , 
2, 3.02945, 0, 0, 0.794872,0.0037081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857143,-0.211296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744898,0.0376766) , 
1, 0.89027, 0, 0, 0.752381,-0.00011619) , 
1, 1.15507, 0, 0, 0.760814,0.000642829) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.867816,0.21863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0555556,-0.118871) , 
3, 1.86236, 0, 0, 0.417949,0.000554386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722222,0.178925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302832,-0.0890294) , 
0, -0.0205591, 1, 0, 0.371585,-0.000877851) , 
1, 0.288285, 0, 0, 0.390841,-0.000282992) , 
2, 2.73067, 0, 0, 0.5,-9.83313e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.504329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500297) , 
0, 0.334873, 0, 0, 1,0.000206455) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642857,-0.0325353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454545,-0.323511) , 
3, 1.87042, 0, 0, 0.633484,-0.00216293) , 
3, 1.96656, 0, 0, 0.881406,-0.000560212) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661765,0.180112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16092,-0.0434388) , 
2, 2.09336, 0, 0, 0.380645,0.00412623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0416667,0.496166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00851064,-0.224416) , 
0, -0.0947295, 1, 0, 0.0101215,-0.000276075) , 
3, 1.80867, 0, 0, 0.0986133,0.000775322) , 
3, 1.8656, 0, 0, 0.5,9.05102e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992188,0.0178481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.220592) , 
3, 1.89637, 0, 0, 0.842391,-0.00164572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688129,0.0424527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281346,-0.0944062) , 
0, 0.624412, 1, 0, 0.526699,0.000133159) , 
0, -0.0204712, 1, 0, 0.584325,-0.000191557) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6875,0.553341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566667,0.0430573) , 
2, 0.911015, 0, 0, 0.608696,0.00362939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23871,-0.075152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.097561,0.266069) , 
0, 0.693935, 1, 0, 0.176259,0.000249013) , 
0, -0.00722063, 1, 0, 0.237654,0.000728943) , 
2, 1.18756, 0, 0, 0.5,3.23483e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.509165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.932331,0.0222211) , 
1, 1.94538, 0, 0, 0.937063,0.000443371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117647,-0.582252) , 
3, 1.81591, 0, 0, 0.85,-0.000537561) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.96,0.142783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315789,0.430969) , 
3, 1.893, 0, 0, 0.782609,0.00263266) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65678,-0.0756437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370242,0.0277665) , 
2, 2.50661, 0, 0, 0.43155,-4.37761e-05) , 
2, 3.24166, 0, 0, 0.452218,0.000113796) , 
2, 3.50222, 0, 0, 0.5,3.55546e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,-0.375672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,0.511633) , 
2, 1.97741, 0, 0, 0.675676,-0.00185059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84375,-0.122952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584733,0.0432241) , 
2, 3.56059, 0, 0, 0.627075,0.000468018) , 
1, 1.8518, 0, 0, 0.631272,0.000267812) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365672,0.167999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116667,-0.521179) , 
0, 0.724646, 1, 0, 0.28866,0.000370894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30137,-0.314908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225962,0.012494) , 
2, 1.24037, 0, 0, 0.245552,-0.00107322) , 
1, 0.288285, 0, 0, 0.263158,-0.000483413) , 
2, 1.57334, 0, 0, 0.5,-8.00412e-08)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.536266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.923077,0.0438302) , 
0, 0.361378, 0, 0, 0.92511,0.00156988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621622,-0.0290715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448718,-0.276933) , 
0, 0.358382, 1, 0, 0.591518,-0.00147295) , 
2, 2.768, 0, 0, 0.703704,-0.000449657) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496689,0.133457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.449311) , 
0, 0.584356, 1, 0, 0.46988,0.0014745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.142523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218673,0.0388982) , 
0, 0.684595, 1, 0, 0.230143,-5.40759e-05) , 
0, 0.599107, 1, 0, 0.290715,0.000332139) , 
0, 0.449693, 1, 0, 0.5,-6.40413e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.995984,0.267159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405405,-0.0613178) , 
3, 1.92297, 0, 0, 0.74424,-0.000317594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851724,0.0999841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0669014,-0.0339254) , 
3, 1.85728, 0, 0, 0.463415,0.000661805) , 
2, 2.62107, 0, 0, 0.584325,0.00024012) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84058,0.170576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387097,-0.383294) , 
0, 0.490878, 1, 0, 0.7,-0.00237333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,-0.285495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0247525,0.196131) , 
2, 1.03359, 0, 0, 0.03125,0.000257295) , 
3, 1.86236, 0, 0, 0.237654,-0.000554626) , 
2, 1.18756, 0, 0, 0.5,4.6803e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967662,0.014865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354037,0.0777561) , 
3, 1.88009, 0, 0, 0.792185,0.000664388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301587,0.0376633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227273,-0.233365) , 
1, 0.128079, 0, 0, 0.263566,-0.00130556) , 
0, 0.824106, 1, 0, 0.693642,0.000297158) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663158,0.154487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34413,-0.127054) , 
0, 0.0100667, 1, 0, 0.432749,-0.00108889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.942857,0.384715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0190114,-0.0126856) , 
3, 1.91722, 0, 0, 0.127517,0.000487492) , 
0, 0.552842, 1, 0, 0.290625,-0.000354885) , 
2, 1.95911, 0, 0, 0.5,-1.61355e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.965986,0.0493989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84375,-0.514354) , 
2, 0.829689, 0, 0, 0.953988,-0.000105219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,-0.205979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230089,-0.0202595) , 
3, 1.85079, 0, 0, 0.296296,-0.0016081) , 
3, 1.86958, 0, 0, 0.761388,-0.000545325) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651163,-0.229623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344444,-0.0303711) , 
0, 0.425709, 1, 0, 0.403587,-0.000848258) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551724,0.116989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28827,0.0110648) , 
0, 0.437471, 1, 0, 0.347222,0.000693706) , 
1, 0.985296, 0, 0, 0.361653,0.000298921) , 
0, 0.261627, 1, 0, 0.5,6.73082e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905172,0.305034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527363,-0.0146165) , 
2, 3.67083, 0, 0, 0.566459,-4.68641e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,-0.533191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1,0.499762) , 
3, 1.91637, 0, 0, 0.375,-0.00304277) , 
0, 0.942107, 1, 0, 0.561145,-0.000130012) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1875,0.536814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128205,-0.201034) , 
1, -0.763439, 0, 0, 0.145455,0.00289996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55,-0.479747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.500654) , 
3, 1.88229, 0, 0, 0.0887097,-0.000448443) , 
1, -0.445794, 1, 0, 0.106145,0.000580396) , 
0, 1.01389, 1, 0, 0.5,-3.45439e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.961877,-0.0404632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0662423) , 
3, 1.89108, 0, 0, 0.923833,0.000278388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.406875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0560748,-0.164816) , 
3, 1.81985, 0, 0, 0.0854701,-0.00239529) , 
3, 1.83706, 0, 0, 0.736641,-0.000318598) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.802632,0.375792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364583,-0.125676) , 
0, 0.354555, 1, 0, 0.55814,0.000921686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514894,-0.048516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157107,0.0785227) , 
0, 0.3666, 1, 0, 0.289308,6.40268e-05) , 
2, 1.94035, 0, 0, 0.346535,0.000246598) , 
2, 2.34489, 0, 0, 0.5,2.42536e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948235,-0.0672238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.811159,0.079071) , 
0, 0.426597, 1, 0, 0.899696,0.000143128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.0945277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292035,-0.106365) , 
0, 0.0950596, 1, 0, 0.411765,-0.00173355) , 
3, 1.87646, 0, 0, 0.807645,-0.000210919) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473684,0.242077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.522811) , 
0, 0.653757, 1, 0, 0.243243,0.00617081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0285714,-0.508494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00222717,0.122961) , 
0, -0.0018598, 1, 0, 0.00413223,-7.27167e-05) , 
3, 1.80427, 0, 0, 0.0211132,0.000370681) , 
3, 1.82145, 0, 0, 0.5,1.65687e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990291,-0.0750681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619048,-0.195637) , 
3, 1.91033, 0, 0, 0.882759,-0.000925012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649718,-0.0710377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640541,0.0932312) , 
1, -0.409489, 1, 0, 0.64351,0.000598891) , 
0, -0.021085, 1, 0, 0.693642,0.000279576) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69863,-0.193855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609302,0.0177358) , 
2, 1.62992, 0, 0, 0.631944,-0.000912736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.037037,0.25067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00369004,-0.259944) , 
2, 1.58882, 0, 0, 0.0113636,9.94479e-05) , 
3, 1.81856, 0, 0, 0.290625,-0.000356035) , 
2, 1.95911, 0, 0, 0.5,-2.58224e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857143,0.319046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498221,-0.0495609) , 
0, 0.00655254, 1, 0, 0.595855,8.83987e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461538,0.520898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0652174,0.100668) , 
0, 1.1027, 1, 0, 0.152542,0.00225625) , 
0, 1.01193, 1, 0, 0.537079,0.000375821) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521822,0.0186313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416667,-0.165688) , 
1, 0.30903, 0, 0, 0.492476,-0.000520275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735849,-0.139423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271845,0.29631) , 
2, 2.47609, 0, 0, 0.429487,0.00127012) , 
1, -0.0395444, 0, 0, 0.481398,-0.000205391) , 
1, -0.408727, 1, 0, 0.5,-1.12174e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757143,0.0336867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.155274) , 
2, 2.57013, 0, 0, 0.631387,-0.00032644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820513,-0.237717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617647,0.0589967) , 
1, -2.19676, 1, 0, 0.631218,0.000536395) , 
1, 0.721156, 0, 0, 0.631272,0.00026053) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777778,0.481679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481481,-0.508819) , 
0, -0.298637, 1, 0, 0.6,-0.00219385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.126856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153846,-0.0768936) , 
0, 0.272215, 1, 0, 0.227907,-0.000103672) , 
0, -0.103449, 1, 0, 0.263158,-0.000301689) , 
2, 1.57334, 0, 0, 0.5,6.00388e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933649,0.231521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,-0.128062) , 
2, 2.87997, 0, 0, 0.914894,0.000430378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,-0.512776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510949,0.0194704) , 
0, 0.503799, 1, 0, 0.531646,-0.0013174) , 
0, 0.452542, 1, 0, 0.760814,-0.00027229) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60687,-0.0277986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505747,0.187353) , 
2, 2.05708, 0, 0, 0.581662,0.000463178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572414,-0.151839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182022,0.0303387) , 
0, 0.180357, 1, 0, 0.277966,-0.000154319) , 
2, 1.84616, 0, 0, 0.390841,7.51874e-05) , 
2, 2.73067, 0, 0, 0.5,-2.73341e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831461,-0.112249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60177,0.231695) , 
2, 2.63273, 0, 0, 0.70297,0.000495296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577488,0.00568166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481865,-0.122183) , 
1, -0.199448, 0, 0, 0.554591,-0.000330263) , 
1, -0.988006, 1, 0, 0.584325,-0.000164824) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416667,0.471601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.436092) , 
2, 1.15102, 0, 0, 0.375,0.00211718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.198894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201493,-0.0136663) , 
1, 2.19006, 0, 0, 0.21831,9.12711e-05) , 
2, 1.03785, 0, 0, 0.237654,0.000341383) , 
2, 1.18756, 0, 0, 0.5,-4.16924e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.520724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541401,-0.145291) , 
2, 3.45035, 0, 0, 0.588571,-0.000301657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640212,0.116027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185185,-0.112042) , 
0, 0.730196, 1, 0, 0.503704,0.000713671) , 
1, -1.4087, 1, 0, 0.537079,0.000314384) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.49637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642857,-0.171138) , 
0, 0.45388, 1, 0, 0.709677,0.00208492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473934,-0.0155901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416667,-0.329493) , 
1, 2.36788, 1, 0, 0.473131,-0.00020554) , 
1, 2.51473, 0, 0, 0.481398,-0.00012549) , 
1, -0.408727, 1, 0, 0.5,2.14649e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776,-0.037105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706897,-0.24481) , 
0, 0.155652, 1, 0, 0.766744,-0.000463627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.500003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,0.386475) , 
3, 1.9654, 0, 0, 0.678571,0.00184738) , 
0, 0.225359, 1, 0, 0.761388,-0.000323263) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653846,-0.113912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517241,0.316891) , 
0, 0.286885, 0, 0, 0.581818,0.00253895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605536,0.0819469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204934,-0.062792) , 
2, 2.34489, 0, 0, 0.346814,4.87557e-05) , 
0, 0.320216, 1, 0, 0.361653,0.000206001) , 
0, 0.261627, 1, 0, 0.5,2.2825e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862385,-0.053088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514286,-0.390724) , 
0, 0.620991, 1, 0, 0.777778,-0.0017478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975904,0.203875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301205,-0.0713181) , 
3, 1.88196, 0, 0, 0.751004,0.000171296) , 
1, 0.364751, 0, 0, 0.760814,-0.000531884) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759465,0.0595144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456522,-0.486123) , 
2, 0.548703, 0, 0, 0.731313,0.000595222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148148,-0.146361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00239808,0.06181) , 
3, 1.80179, 0, 0, 0.0112613,-0.000129214) , 
3, 1.81856, 0, 0, 0.390841,0.000252677) , 
2, 2.73067, 0, 0, 0.5,2.11961e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.997976,0.206541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672131,-0.0382593) , 
3, 1.93918, 0, 0, 0.933442,-0.000119032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736842,0.222852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270833,-0.193062) , 
0, 0.232222, 1, 0, 0.402985,-0.00258576) , 
3, 1.89087, 0, 0, 0.881406,-0.00036101) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609375,-0.0584543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19084,0.127997) , 
0, 0.29948, 1, 0, 0.328205,0.00115254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.502146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.500589) , 
3, 1.77397, 0, 0, 0,-5.80812e-05) , 
3, 1.78975, 0, 0, 0.0986133,0.000305666) , 
3, 1.8656, 0, 0, 0.5,-3.61805e-05)    );
   return;
};
 
// Clean up
inline void ReadBDTMC::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTMC::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
